/* Yeni eklenen türler için akademik veri katmanı (özet düzeyinde). */
import type { Academic } from '../../contracts/species';

const R_GUNER = 'Güner, A. et al. (2012). Türkiye Bitkileri Listesi (Damarlı Bitkiler). Nezahat Gökyiğit Botanik Bahçesi Yayınları, İstanbul.';
const R_DAVIS = 'Davis, P.H. (ed.) (1965–1988). Flora of Turkey and the East Aegean Islands, Vol. 1–10. Edinburgh University Press.';
const R_YALT = 'Yaltırık, F. & Efe, A. (1989). Türkiye’nin Önemli Orman Ağaçları ve Yüzeyleri. İ.Ü. Orman Fakültesi Yayınları.';
const R_ANSIN = 'Ansin, R. & Özkan, Z.C. (2006). Tohumlu Bitkiler (Spermatophyta); Odunsu Taksonlar. KTÜ Orman Fakültesi.';
const R_GBIF = 'GBIF — Global Biodiversity Information Facility, tür dağılım kayıtları (gbif.org).';
const R_IUCN = 'IUCN Red List of Threatened Species (iucnredlist.org).';
const R_TARIM = 'T.C. Tarım ve Orman Bakanlığı, bitkisel üretim ve tescil kayıtları.';
const REFS_ORMAN = [R_YALT, R_DAVIS, R_GBIF];
const REFS_BOT = [R_GUNER, R_DAVIS, R_GBIF];
const REFS_TARIM = [R_TARIM, R_GUNER, R_GBIF];
const REFS_ADV = [R_ANSIN, R_GUNER, R_GBIF];

type Row = [string, string, string, string, string, string, string[]];
const NE = 'Değerlendirilmemiş (kültür/yabancı tür)';
const rows: Row[] = [
  ['kafkas-goknari', 'LC (Asgari Endişe)', 'Yağışlı, serin dağ ormanları; ladin ve kayınla karışık kuşak.', '900 – 2.000 m', '30–50 m; gümüşi altlı yassı iğneler; dik, 12–18 cm kozalaklar.', 'Kafkasya ve Kuzeydoğu Anadolu; Türkiye’de Doğu Karadeniz dağlarında geniş meşcereler.', REFS_ORMAN],
  ['uludag-goknari', 'LC (Asgari Endişe)', 'Nemli ve sisli dağ ormanları; derin, serin topraklar.', '1.000 – 2.100 m', '25–40 m; iğneler yassı ve çentikli uçlu; kozalaklar dik.', 'Batı ve Orta Karadeniz ile Marmara dağlarına özgü; Uludağ saf ormanları.', REFS_ORMAN],
  ['kazdagi-goknari', 'Veri doğrulanmalı (IUCN kaydına bakınız)', 'Kazdağları’nın yüksek, sisli kuşağı; granit ve peridotit topraklar.', '800 – 1.700 m', '20–30 m; uçları sivri yassı iğneler; yüksek kozalak gövde.', 'Dar yayılışlı: Kazdağları ve çevresi; Türkiye endemiği.', REFS_ORMAN],
  ['sabin-ardici', 'LC (Asgari Endişe)', 'Yüksek dağ kuşağı; kayalık, kireçli yamaçlar.', '1.600 – 3.000 m', '1–4 m; pulsu yaprak; mavimsi-siyah meyve.', 'Avrupa dağları ve Batı Asya; Türkiye’de yüksek dağ kuşağı.', REFS_BOT],
  ['kokulu-ardic', 'LC (Asgari Endişe)', 'Kurak, taşlı yamaçlar; kireçli topraklar.', '800 – 2.200 m', '10–20 m; ezilince keskin kokan yapraklar; koyu mor meyve.', 'Doğu Akdeniz ve Batı Asya; Toros ve Güneydoğu Anadolu dağları.', REFS_BOT],
  ['anadolu-karacami', 'LC (Asgari Endişe)', 'Dağ ve iç kuşak ormanları; geniş toprak toleransı.', '300 – 1.800 m', '20–35 m; gri-siyah çatlaklı kabuk; uzun, koyu yeşil iğneler.', 'Anadolu’nun dağ ormanlarında en geniş yayılışlı iğne yapraklı.', REFS_ORMAN],
  ['macar-mesesi', 'LC (Asgari Endişe)', 'Nemli, derin topraklı alçak orman kuşağı.', '0 – 1.000 m', '20–30 m; büyük, derin loblu yaprak; iri palamut.', 'Balkanlar ve Güneydoğu Avrupa; Türkiye’de Trakya ve Marmara.', REFS_ORMAN],
  ['sapsiz-mese', 'LC (Asgari Endişe)', 'Nemli, derin ve hafif asidik topraklar.', '0 – 1.600 m', '20–35 m; yaprak sapı uzun, palamut sapsız.', 'Avrupa ve Batı Asya; Marmara ve Karadeniz ormanları.', REFS_ORMAN],
  ['sapli-mese', 'LC (Asgari Endişe)', 'Taşkın ovaları; nemli, besin zengini topraklar.', '0 – 1.200 m', '25–40 m; yaprak sapı kısa; palamut uzun saplı.', 'Avrupa ve Batı Asya; Trakya ve Kuzey Anadolu.', REFS_ORMAN],
  ['tuylu-mese', 'LC (Asgari Endişe)', 'Kurak, kireçli ve taşlı yamaçlar.', '200 – 1.600 m', '8–20 m; yaprak altı tüylü; kışın kuru yaprakları tutar.', 'Avrupa’dan Batı Asya’ya; İç Batı ve Orta Anadolu.', REFS_ORMAN],
  ['kafkas-mesesi', 'LC (Asgari Endişe)', 'Yüksek dağ kuşağı; soğuk iklim.', '1.000 – 2.300 m', '15–25 m; büyük, derin loblu yaprak.', 'Kafkasya, İran ve Kuzeydoğu Anadolu dağları.', REFS_ORMAN],
  ['salkim-sogut', NE, 'Göl ve nehir kıyıları; nemli, taşkın toprağı.', '0 – 1.200 m', '8–15 m; sarkık ince dallar; dar yapraklar.', 'Çin kökenli; dünya çapında süs ağacı olarak yayılmış.', REFS_BOT],
  ['dag-karaagaci', 'LC (Asgari Endişe)', 'Nemli, serin dağ vadileri.', '600 – 1.800 m', '25–35 m; iri ve pürüzlü yaprak; kanatlı meyve.', 'Avrupa ve Batı Asya dağlarında; Türkiye’de kuzey dağları.', REFS_BOT],
  ['cicekli-disbudak', 'LC (Asgari Endişe)', 'Kurak, taşlık yamaçlar; kireçli topraklar.', '0 – 1.400 m', '8–15 m; beyaz kokulu çiçek salkımları.', 'Güney Avrupa ve Batı Asya; Trakya ve Batı Anadolu.', REFS_BOT],
  ['gurgen', 'LC (Asgari Endişe)', 'Alçak ve dağ ormanları; nemli topraklar.', '0 – 1.500 m', '15–25 m; oluklu gövde; testere dişli yaprak.', 'Avrupa ve Batı Asya; Trakya, Marmara ve Karadeniz.', REFS_ORMAN],
  ['dogu-gurgeni', 'LC (Asgari Endişe)', 'Kurak ve taşlı yamaçlar; makiye geçiş kuşağı.', '0 – 1.400 m', '4–10 m; küçük yaprak; küçük meyve başakları.', 'Güneydoğu Avrupa ve Batı Asya; Marmara ve Ege.', REFS_ORMAN],
  ['kara-gurgen', 'LC (Asgari Endişe)', 'Kuru, kayalık ve kireçli yamaçlar.', '0 – 1.200 m', '10–20 m; hop başağına benzer meyve salkımı.', 'Güney Avrupa ve Batı Asya; Kuzey Anadolu.', REFS_ORMAN],
  ['alic', 'LC (Asgari Endişe)', 'Orman kenarları ve çalılıklar; çok çeşitli toprak.', '0 – 2.000 m', '4–10 m; dikenli dallar; beyaz çiçek; kırmızı meyve.', 'Avrupa, Batı Asya ve Kuzey Afrika; Türkiye’de yaygın.', REFS_BOT],
  ['uvez', 'LC (Asgari Endişe)', 'Dağ ormanları, yüksek yamaçlar.', '800 – 2.200 m', '5–15 m; bileşik yaprak; turuncu-kırmızı meyve salkımları.', 'Avrupa ve Batı Asya; Kuzey Anadolu dağları.', REFS_BOT],
  ['barut-agaci', 'LC (Asgari Endişe)', 'Meşe ormanlarının serin, nemli alt kuşağı.', '0 – 1.400 m', '10–25 m; loblu yaprak; küçük kahverengi meyve.', 'Avrupa ve Batı Asya; Marmara ve Karadeniz.', REFS_BOT],
  ['balkan-akcaagaci', 'LC (Asgari Endişe)', 'Yarı gölgeli orman tabanları; kireçli topraklar.', '0 – 1.500 m', '10–20 m; 5 loblu yaprak; sonbahar sarısı.', 'Güneydoğu Avrupa ve Batı Asya; Trakya ve Marmara.', REFS_BOT],
  ['norvec-akcaagaci', 'LC (Asgari Endişe)', 'Serin, nemli orman tabanları ve parklar.', '0 – 1.500 m', '15–25 m; 5 loblu sivri uçlu yaprak; sarı sonbahar.', 'Avrupa ve Batı Asya; kuzey Türkiye ve parklar.', REFS_BOT],
  ['negundo-akcaagaci', NE, 'Taşkın ovaları ve kent alanları.', '0 – 1.200 m', '10–20 m; bileşik yaprak; kanatlı çift meyve.', 'Kuzey Amerika kökenli; Avrupa ve Türkiye’de yayılmış.', REFS_BOT],
  ['at-kestanesi', 'Veri doğrulanmalı (IUCN kaydına bakınız)', 'Nemli, derin topraklı vadiler; parklar.', '0 – 1.500 m', '20–30 m; 5–7 yaprakçıklı bileşik yaprak; dik çiçek başağı.', 'Balkanlar kökenli; Avrupa ve Türkiye’de parklarda dikili.', REFS_BOT],
  ['sigla', 'EN (Tehlike Altında)', 'Taşkın ve bataklık ormanları; deniz seviyesine yakın alüvyonlu zemin.', '0 – 400 m', '15–35 m; 5 loblu yaprak; reçineli gövde.', 'Dar yayılışlı: Muğla, Aydın ve Antalya çevresi; Türkiye endemiği.', [R_IUCN, R_YALT, R_DAVIS]],
  ['turk-findigi', 'Veri doğrulanmalı (IUCN kaydına bakınız)', 'Serin, nemli dağ ormanları.', '200 – 1.500 m', '15–30 m; piramit taç; dikenli kabuklu meyve.', 'Balkanlar ve Batı Asya; Kuzey Anadolu.', REFS_BOT],
  ['sumak', 'LC (Asgari Endişe)', 'Kurak, taşlı ve fakir topraklar.', '0 – 1.500 m', '2–6 m; bileşik yaprak; kırmızı meyve salkımı.', 'Akdeniz havzası ve Batı Asya; Güneydoğu Anadolu.', REFS_BOT],
  ['katalpa', NE, 'Nemli, derin topraklı parklar.', '0 – 1.000 m', '10–15 m; büyük kalp yaprak; uzun çubuk meyve.', 'Kuzey Amerika kökenli; parklarda dikili.', REFS_BOT],
  ['ailanthus', NE, 'Kent çatlakları, boş alanlar; çok geniş tolerans.', '0 – 1.200 m', '15–25 m; çok yapraklı bileşik yaprak; kanatlı meyve.', 'Çin kökenli; dünya çapında istilacı.', REFS_BOT],
  ['gladicya', NE, 'Kent parkları; kuraklığa ve tuza dayanıklı.', '0 – 1.200 m', '15–25 m; dikenli gövde; uzun bükülmüş bakla.', 'Kuzey Amerika kökenli; Türkiye’de süs ve yol ağacı.', REFS_BOT],
  ['pagoda-agaci', NE, 'Kent parkları; kuraklığa dayanıklı.', '0 – 1.200 m', '15–25 m; bileşik yaprak; yaz ortası krem çiçek.', 'Çin ve Kore kökenli; süs ağacı olarak yaygın.', REFS_BOT],
  ['ipek-agaci', NE, 'Güneşli, kuru kentsel alanlar.', '0 – 1.000 m', '6–12 m; tüysü yaprak; pembe ipeksi çiçek.', 'Doğu Asya kökenli; süs ağacı.', REFS_BOT],
  ['paulownia', NE, 'Derin, iyi drene toprak; kentsel alanlar.', '0 – 1.000 m', '10–20 m; büyük yapraklı; mor çiçek.', 'Çin kökenli; süs ve hızlı büyüyen ağaç.', REFS_BOT],
  ['lale-agaci', NE, 'Derin, nemli topraklı parklar.', '0 – 1.000 m', '25–40 m; 4 loblu yaprak; lale biçimli çiçek.', 'Kuzey Amerika kökenli; parklarda dikili.', REFS_BOT],
  ['manolya', NE, 'Nemli iklim ve parklar; kıyı ve Karadeniz.', '0 – 500 m', '10–25 m; parlak deri yaprak; büyük beyaz çiçek.', 'Kuzey Amerika kökenli; kıyı kentlerinde dikili.', REFS_BOT],
  ['ginkgo', 'EN (Tehlike Altında; doğal popülasyonlar)', 'Kent parkları; kirliliğe dayanıklı.', '0 – 1.200 m', '20–35 m; yelpaze biçimli yaprak; sonbaharda sarı.', 'Çin kökenli; dünya çapında süs ağacı.', [R_IUCN, R_GUNER, R_GBIF]],
  ['datca-hurmasi', 'NT (Tehdite Yakın)', 'Kıyı kumulları ve dere ağızları.', '0 – 100 m', '4–10 m; çok gövdeli; yelpaze biçimli yaprak.', 'Datça, Bozburun ve Girit; Türkiye’de çok sınırlı.', [R_IUCN, R_GUNER, R_GBIF]],
  ['okaliptus', 'LC (doğal alanda); Türkiye’de yabancı', 'Ova, sulak alan kenarları; hızlı büyüme.', '0 – 500 m', '20–40 m; mavimsi yaşlı yaprak; soyulan kabuk.', 'Avustralya kökenli; Çukurova ve Akdeniz ovalarında dikili.', REFS_BOT],
  ['ilgin', 'LC (Asgari Endişe)', 'Tuzlu topraklar, deniz kıyısı, delta.', '0 – 1.000 m', '3–8 m; pul yaprak; pembe başak çiçekler.', 'Doğu Akdeniz ve Batı Asya; kıyı ve iç tuzlu alanlar.', REFS_BOT],
  ['tesbih-agaci', NE, 'Akdeniz kentleri; sıcak, kurak alanlar.', '0 – 600 m', '8–15 m; bileşik yaprak; sarı küresel meyve.', 'Asya kökenli; Akdeniz kıyılarında dikili.', REFS_BOT],
  ['funda', 'LC (Asgari Endişe)', 'Maki ve orman kenarı; asidik silisli topraklar.', '0 – 1.200 m', '2–5 m; ince iğne yaprak; beyaz çan çiçek.', 'Akdeniz havzası; Ege ve Akdeniz kıyı makileri.', REFS_BOT],
  ['kocayemis', 'LC (Asgari Endişe)', 'Akdeniz makisi ve kıyı ormanları.', '0 – 1.000 m', '3–8 m; kırmızı çilek benzeri meyve; kalıcı yaprak.', 'Akdeniz ve Atlantik Avrupa; Ege ve Akdeniz kıyıları.', REFS_BOT],
  ['ormangulu', 'LC (Asgari Endişe)', 'Nemli ormanaltı; asidik toprak.', '0 – 2.200 m', '2–6 m; deri yaprak; mor-pembe çiçek.', 'Güneybatı Avrupa ve Kafkasya; Doğu Karadeniz.', REFS_BOT],
  ['findik', NE, 'Nemli, serin kıyı yamaçları.', '0 – 1.200 m', '3–6 m; kuru kabuklu meyve; erkek çiçek püskülü.', 'Karadeniz kıyıları; dünya fındık üretiminin merkezi.', REFS_TARIM],
  ['antep-fistigi', NE, 'Kurak, taşlık ve kireçli toprak.', '300 – 1.200 m', '4–8 m; tüysü bileşik yaprak; periyodisite gösterir.', 'Güneydoğu Anadolu; Antep, Şanlıurfa ve Siirt.', REFS_TARIM],
  ['elma', NE, 'Serin, iyi drene vadiler; ılıman iklim.', '300 – 1.800 m', '4–8 m; beyaz-pembe çiçek; yuvarlak meyve.', 'Orta Asya kökenli; Anadolu’da yaygın üretim.', REFS_TARIM],
  ['armut', NE, 'Derin, nemli topraklı vadiler.', '0 – 1.600 m', '5–12 m; beyaz çiçek; armut biçimli meyve.', 'Avrupa ve Batı Asya; Anadolu’da kültüre alınmış.', REFS_TARIM],
  ['ayva', NE, 'Nemli, serin bahçeler.', '0 – 1.200 m', '3–6 m; tüysü meyve; pembe-beyaz çiçek.', 'Batı Asya kökenli; Anadolu’da yaygın.', REFS_TARIM],
  ['visne', NE, 'Serin iklim bahçeleri.', '300 – 1.500 m', '4–8 m; beyaz çiçek; ekşi meyve.', 'Avrupa ve Batı Asya; Anadolu’da yaygın.', REFS_TARIM],
  ['seftali', NE, 'Sıcak, güneşli bahçeler; ılıman iklim.', '0 – 800 m', '3–6 m; pembe çiçek; tüylü meyve.', 'Çin kökenli; Türkiye’de Marmara ve Akdeniz kıyıları.', REFS_TARIM],
  ['erik', NE, 'Serin bahçeler; nemli topraklar.', '300 – 1.400 m', '4–8 m; beyaz çiçek; mor-sarı meyve.', 'Avrasya kökenli; Anadolu’da yaygın.', REFS_TARIM],
  ['nar', NE, 'Kurak, sıcak yamaçlar.', '0 – 1.000 m', '3–6 m; parlak kırmızı çiçek; taneli meyve.', 'İran ve Orta Asya kökenli; Akdeniz kuşağı.', REFS_TARIM],
  ['hurma', NE, 'Nemli, ılıman kıyı bahçeleri.', '0 – 500 m', '6–12 m; turuncu meyve; kış boyunca dalda.', 'Çin kökenli; Karadeniz ve Akdeniz kıyıları.', REFS_TARIM],
  ['musmula', 'LC (Asgari Endişe)', 'Orman kenarları ve eski bahçeler.', '0 – 1.200 m', '3–6 m; büyük beyaz çiçek; kahverengi meyve.', 'Güneydoğu Avrupa ve Batı Asya; kuzey Anadolu.', REFS_BOT],
  ['ahlat', 'LC (Asgari Endişe)', 'Orta Anadolu bozkırı; kurak taşlı alanlar.', '600 – 1.800 m', '4–8 m; gümüşi yaprak; küçük armut meyvesi.', 'Güneybatı Asya; İç Anadolu bozkırı.', REFS_BOT],
  ['yenidunya', NE, 'Akdeniz kıyıları; sıcak, korunaklı bahçeler.', '0 – 400 m', '5–10 m; büyük deri yaprak; turuncu meyve.', 'Çin kökenli; Akdeniz kıyılarında dikili.', REFS_TARIM],
  ['portakal', NE, 'Akdeniz kıyı ovaları; ılık, kışları hafif iklim.', '0 – 400 m', '4–8 m; kokulu beyaz çiçek; turuncu meyve.', 'Asya kökenli; Akdeniz kıyıları.', REFS_TARIM],
  ['limon', NE, 'Akdeniz kıyı ovaları; kışları hafif iklim.', '0 – 400 m', '3–6 m; kokulu çiçek; sarı meyve.', 'Asya kökenli; Akdeniz kıyıları.', REFS_TARIM],
  ['turunc', NE, 'Akdeniz kıyı kentleri; ılık iklim.', '0 – 400 m', '4–8 m; çok kokulu çiçek; ekşi acı meyve.', 'Güneydoğu Asya kökenli; Akdeniz kıyıları.', REFS_TARIM],
  ['karayemis', 'LC (Asgari Endişe)', 'Nemli ormanaltı ve dere kıyıları.', '0 – 1.200 m', '4–8 m; parlak her dem yeşil yaprak; siyah meyve.', 'Güneydoğu Avrupa ve Batı Asya; Doğu Karadeniz.', REFS_BOT],
  ['hunnap', NE, 'Kurak, sıcak yamaçlar ve bahçeler.', '0 – 1.000 m', '4–8 m; dikenli dal; kırmızı-kahverengi meyve.', 'Asya kökenli; Güney ve Güneydoğu Anadolu.', REFS_TARIM],
  ['mahlep', 'LC (Asgari Endişe)', 'Kuru taşlı yamaçlar; kireçli toprak.', '300 – 1.600 m', '3–8 m; beyaz çiçek; küçük siyah meyve.', 'Avrupa ve Batı Asya; Orta Anadolu.', REFS_BOT],
  ['kafkas-zelkovasi', 'NT (Tehdite Yakın)', 'Nemli dere vadileri; alüvyal topraklar.', '0 – 1.200 m', '20–35 m; testere dişli yaprak; küçük meyve.', 'Kafkasya ve Kuzey İran; Doğu Karadeniz.', [R_IUCN, R_GUNER, R_GBIF]],
  ['akdeniz-servisi', 'LC (Asgari Endişe)', 'Kıyı ve dağ yamaçları; kurak kireçli toprak.', '0 – 1.200 m', '15–25 m; yatay dallı; küçük kozalaklar.', 'Doğu Akdeniz; Antalya ve Muğla.', REFS_ORMAN],
  ['memecik-zeytini', NE, 'Ege yamaçları; kurak, taşlık toprak.', '0 – 600 m', '6–12 m; küçük yağlı meyve; uzun ömür.', 'Ege bölgesinin yağlık çeşidi.', REFS_TARIM],
  ['gemlik-zeytini', NE, 'Marmara kıyıları; ılıman iklim.', '0 – 400 m', '5–10 m; iri sofralık meyve.', 'Bursa ve Yalova çevresi.', REFS_TARIM],
  ['edremit-zeytini', NE, 'Kazdağı eteği ve kıyı yamaçları.', '0 – 500 m', '6–12 m; yağlık meyve; ince yapraklı.', 'Balıkesir kıyıları; Edremit ve Ayvalık.', REFS_TARIM],
  ['mimoza', NE, 'Akdeniz kıyıları; hafif donlu iklim.', '0 – 500 m', '5–15 m; tüysü yaprak; sarı çiçek tüyleri.', 'Avustralya kökenli; kıyı kentlerinde dikili.', REFS_BOT],
  ['kirim-ihlamuru', NE, 'Cadde ve parklar; kirliliğe dayanıklı.', '0 – 1.000 m', '15–25 m; parlak yeşil yaprak; kokulu çiçek.', 'Melez; Avrupa ve Türkiye kentlerinde dikili.', REFS_BOT],
  ['igde', 'LC (Asgari Endişe)', 'Tuzlu, kurak topraklar; nehir kıyıları.', '0 – 2.000 m', '5–10 m; gümüşi yaprak; çok kokulu çiçek.', 'Batı ve Orta Asya; İç Anadolu ve Doğu Anadolu.', REFS_BOT],
  ['deniz-dikeni', 'LC (Asgari Endişe)', 'Dere yatakları; çakıllı, kumlu topraklar.', '800 – 2.500 m', '2–6 m; dikenli dal; turuncu meyve.', 'Avrasya’nın geniş kuşağı; Doğu Anadolu vadileri.', REFS_BOT],
  ['firat-kavagi', 'LC (Asgari Endişe)', 'Sıcak, tuzlu nehir kıyıları.', '300 – 1.000 m', '10–20 m; yaprak şekli yaşa göre değişir.', 'Orta Doğu ve Orta Asya; Fırat ve Dicle kıyıları.', REFS_BOT],
  ['hayit', 'LC (Asgari Endişe)', 'Dere yatakları ve kıyı kumulları.', '0 – 800 m', '2–5 m; parmaklı yaprak; mavi-mor başak.', 'Akdeniz havzası; Ege ve Akdeniz kıyıları.', REFS_BOT],
  ['zakkum', 'LC (Asgari Endişe)', 'Kurak dere yatakları ve kıyı.', '0 – 800 m', '2–6 m; dar deri yaprak; pembe çiçek; zehirli.', 'Akdeniz havzası ve Güney Asya.', REFS_BOT],
  ['simsir', 'LC (Asgari Endişe)', 'Nemli ormanaltı; kireçli yamaçlar.', '0 – 1.500 m', '2–8 m; küçük parlak yaprak; çok sert odun.', 'Avrupa ve Batı Asya; Karadeniz.', REFS_BOT],
  ['cobanpuskulu', 'LC (Asgari Endişe)', 'Nemli, gölgeli Kolhik ormanı alt tabakası.', '0 – 1.200 m', '3–8 m; dikensiz parlak yaprak; kırmızı meyve.', 'Kafkasya ve Doğu Karadeniz.', REFS_BOT],
  ['londra-cinari', NE, 'Cadde ve parklar; kentsel koşullar.', '0 – 1.000 m', '20–35 m; 5 loblu yaprak; soyulan kabuk.', 'Melez; Avrupa ve Türkiye kentlerinde yaygın.', REFS_BOT],
  ['buyuk-yapakli-ihlamur', 'LC (Asgari Endişe)', 'Nemli, serin orman vadileri.', '0 – 1.400 m', '25–35 m; büyük kalp yaprak; kokulu çiçek.', 'Avrupa ve Batı Asya; Trakya ve Kuzey Anadolu.', REFS_BOT],
  ['kafkas-kizilagaci', 'LC (Asgari Endişe)', 'Nemli yamaçlar ve dere boyları.', '0 – 1.500 m', '15–25 m; yuvarlak koyu yaprak; küçük kozalak.', 'Kafkasya ve Doğu Karadeniz.', REFS_BOT],
  ['kafkas-cevizi', 'LC (Asgari Endişe)', 'Nehir kıyısı ve taşkın ormanları.', '0 – 700 m', '15–30 m; bileşik yaprak; sarkık meyve başağı.', 'Kafkasya ve Kuzey İran; Doğu Karadeniz.', REFS_BOT],
  ['kara-hurma', NE, 'Kıyı ve orman kenarları; sıcak yamaçlar.', '0 – 1.000 m', '10–15 m; küçük koyu meyve.', 'Asya ve Güneydoğu Avrupa; Karadeniz.', REFS_BOT],
  ['adi-disbudak', 'LC (Asgari Endişe)', 'Nemli, besin zengini orman vadileri.', '0 – 1.500 m', '20–35 m; bileşik yaprak; siyah tomurcuk.', 'Avrupa ve Batı Asya; Trakya ve Kuzey Anadolu.', REFS_BOT],
  ['tatar-akcaagaci', 'LC (Asgari Endişe)', 'Bozkır-orman geçiş kuşağı.', '300 – 1.800 m', '3–8 m; kırmızı kanatlı meyve; sonbahar kızılı.', 'Doğu Avrupa ve Batı Asya; İç Anadolu.', REFS_BOT],
  ['akdeniz-akcaagaci', 'LC (Asgari Endişe)', 'Kurak, taşlı yamaçlar.', '0 – 1.500 m', '5–12 m; 3 loblu küçük yaprak.', 'Akdeniz havzası; Batı Toroslar.', REFS_BOT],
  ['kapadokya-akcaagaci', 'LC (Asgari Endişe)', 'Nemli, serin orman vadileri.', '600 – 2.000 m', '15–25 m; 5–7 loblu parlak yaprak; sonbahar sarısı.', 'Kafkasya ve Himalaya’ya kadar; Kuzeydoğu Anadolu.', REFS_BOT],
  ['yabani-elma', 'LC (Asgari Endişe)', 'Orman kenarı; köy çevresi.', '0 – 1.800 m', '5–10 m; küçük ekşi meyve; beyaz-pembe çiçek.', 'Avrupa ve Batı Asya; Kuzey Anadolu.', REFS_BOT],
  ['adi-ardic', 'LC (Asgari Endişe)', 'Yüksek dağ yamaçları; kayalık, açık alanlar.', '800 – 3.000 m', '1–8 m; iğne yaprak; mavi-siyah meyve.', 'Kuzey Yarımküre’de en geniş yayılışlı iğne yapraklı.', REFS_BOT],
  ['suriye-ardici', 'LC (Asgari Endişe)', 'Kuru, taşlı yamaçlar; Toros ve Amanoslar.', '500 – 1.800 m', '10–20 m; iri kahverengi yumuşak meyve; sivri iğne.', 'Doğu Akdeniz; Hatay, Antalya, Isparta.', REFS_BOT],
  ['arizona-servisi', NE, 'Kurak, sıcak alanlar; kent parkları.', '0 – 1.200 m', '10–20 m; mavimsi gri-yeşil pullar.', 'Kuzey Amerika kökenli; ağaçlandırmalarda dikili.', REFS_BOT],
  ['omur-agaci', NE, 'Kurak, taşlı alanlar; parklar ve mezarlıklar.', '0 – 1.000 m', '8–15 m; dikey düzlemsel pul dallar.', 'Çin kökenli; Türkiye’de parklarda ve mezarlıklarda.', REFS_BOT],
  ['atlas-sediri', 'EN (Tehlike Altında; doğal popülasyonlar)', 'Parklar ve dağ yamaçları; kireçli toprak.', '0 – 1.500 m', '25–35 m; mavimsi iğne demetleri.', 'Atlas Dağları kökenli; Türkiye’de dikili.', [R_IUCN, R_GUNER, R_GBIF]],
  ['bataklik-servisi', NE, 'Sulak alanlar ve göl kıyıları.', '0 – 600 m', '20–35 m; tüysü iğne yaprak; soluk kökler.', 'Kuzey Amerika kökenli; parklarda dikili.', REFS_BOT],
  ['trachycarpus', NE, 'Nemli, ılıman kıyı kentleri.', '0 – 500 m', '5–12 m; yelpaze biçimli yaprak; lifli gövde.', 'Çin kökenli; Karadeniz ve Marmara kıyıları.', REFS_BOT],
  ['kanarya-hurmasi', NE, 'Sıcak, kıyı kentleri.', '0 – 300 m', '10–20 m; tüy biçimli yaprak; kalın gövde.', 'Kanarya Adaları kökenli; Akdeniz kentlerinde dikili.', REFS_BOT],
  ['istranca-mesesi', 'LC (Asgari Endişe)', 'Nemli, sisli ormanlar; asidik toprak.', '0 – 1.000 m', '15–30 m; büyük, tırtıklı yaprak.', 'Kafkasya ve Istranca; Kırklareli ve Karadeniz kıyıları.', REFS_ORMAN],
  ['lubnan-mesesi', 'LC (Asgari Endişe)', 'Kurak yamaçlar; Doğu Akdeniz dağları.', '300 – 1.800 m', '5–12 m; uzun dar tırtıklı yaprak.', 'Doğu Akdeniz; Hatay ve Güneydoğu Toroslar.', REFS_ORMAN],
  ['kil-mese', 'LC (Asgari Endişe)', 'Kurak iç yamaçlar; Zagros uzantısı.', '500 – 2.000 m', '8–15 m; tüylü yaprak altı; iri palamut.', 'Güneybatı Asya; Güneydoğu Anadolu.', REFS_ORMAN],
  ['bittim', 'LC (Asgari Endişe)', 'Kurak yamaçlar; kireçli toprak.', '200 – 1.200 m', '5–12 m; bileşik yaprak; reçineli meyve.', 'Akdeniz ve Orta Doğu; Güneydoğu Anadolu.', REFS_BOT],
  ['keci-sogudu', 'LC (Asgari Endişe)', 'Orman kenarları ve açıklıklar.', '0 – 2.000 m', '5–12 m; pamuksu sarı çiçek.', 'Avrasya; Kuzey Anadolu.', REFS_BOT],
  ['can-erigi', NE, 'Parklar ve köy kenarları.', '0 – 1.500 m', '3–8 m; kırmızı-mor yaprak formları.', 'Balkanlar ve Batı Asya kökenli.', REFS_BOT],
  ['kucuk-yapakli-ihlamur', 'LC (Asgari Endişe)', 'Serin, nemli orman vadileri.', '0 – 1.400 m', '20–30 m; küçük kalp yaprak; kokulu çiçek.', 'Avrupa ve Batı Asya; Kuzey Anadolu.', REFS_BOT],
  ['cay', NE, 'Nemli, asidik, derin topraklı yamaçlar; yıllık yağış yüksek.', '0 – 800 m', '1–3 m (budanmış); parlak deri yaprak; beyaz çiçek.', 'Güneydoğu Asya kökenli; Türkiye’de Doğu Karadeniz.', REFS_TARIM],
  ['greyfurt', NE, 'Akdeniz kıyı ovaları; ılık iklim.', '0 – 300 m', '4–8 m; iri meyve; kokulu çiçek.', 'Melez kökenli; Akdeniz kıyıları.', REFS_TARIM],
  ['himalaya-sediri', 'LC (doğal alanda)', 'Parklar ve bahçeler; derin drene toprak.', '0 – 1.200 m', '30–50 m; sarkık dallar; mavimsi uzun iğneler.', 'Himalaya kökenli; süs ağacı.', REFS_BOT],
  ['duglas', NE, 'Serin, nemli ve derin topraklı sahalar.', '0 – 1.600 m', '30–60 m; yumuşak iğne yapraklar; sarkık kozalak.', 'Kuzey Amerika kökenli; ağaçlandırma denemeleri.', REFS_ORMAN],
  ['fenike-ardici', 'LC (Asgari Endişe)', 'Kıyı kayalıkları ve kumullar.', '0 – 800 m', '3–8 m; pul yaprak; kırmızı-sarı meyve.', 'Akdeniz havzası; Türkiye’de kıyı kuşağı.', REFS_BOT],
  ['dogu-kizilagaci', 'LC (Asgari Endişe)', 'Dere kıyıları ve taşkın ormanları.', '0 – 800 m', '10–20 m; yuvarlak yaprak; küçük kozalak.', 'Doğu Akdeniz; Hatay, Antalya, Muğla.', REFS_BOT],
  ['dogu-citlenbigi', 'LC (Asgari Endişe)', 'Kurak, taşlı yamaçlar.', '400 – 1.800 m', '4–10 m; testere dişli yaprak; turuncu-kırmızı meyve.', 'Doğu Akdeniz ve Batı Asya; İç Anadolu.', REFS_BOT],
  ['duman-agaci', 'LC (Asgari Endişe)', 'Kurak, kireçli yamaçlar.', '0 – 1.500 m', '3–6 m; yuvarlak yaprak; tüylü çiçek sapı.', 'Güney Avrupa’dan Çin’e; Anadolu.', REFS_BOT],
  ['gilaburu', 'LC (Asgari Endişe)', 'Nemli vadiler ve dere kenarları.', '500 – 1.800 m', '3–5 m; 3 loblu yaprak; kırmızı salkım meyve.', 'Avrasya; Orta Anadolu.', REFS_BOT],
  ['murver', 'LC (Asgari Endişe)', 'Nemli çalılık, orman kenarı.', '0 – 1.500 m', '3–8 m; bileşik yaprak; krem çiçek; mor meyve.', 'Avrupa ve Batı Asya.', REFS_BOT],
  ['kusburnu', 'LC (Asgari Endişe)', 'Çalılık ve orman kenarları.', '0 – 2.200 m', '1–3 m; dikenli dal; kırmızı meyve.', 'Avrupa, Batı Asya ve Kuzey Afrika; Türkiye’de yaygın.', REFS_BOT],
  ['karacali', 'LC (Asgari Endişe)', 'Kurak yamaçlar ve tarla kenarları.', '0 – 1.200 m', '2–5 m; çift diken; disk biçimli meyve.', 'Güneydoğu Avrupa ve Batı Asya.', REFS_BOT],
  ['katirtirnagi', 'LC (Asgari Endişe)', 'Kıyı makisi ve yol kenarları.', '0 – 800 m', '2–4 m; yeşil çubuk dallar; sarı kokulu çiçek.', 'Akdeniz havzası.', REFS_BOT],
  ['sari-ormangulu', 'LC (Asgari Endişe)', 'Nemli yamaçlar; orman altı.', '300 – 2.000 m', '1–3 m; sarı kokulu çiçek.', 'Kafkasya ve Karadeniz; Kuzey Anadolu.', REFS_BOT],
];

export const MORE_ACADEMIC: Record<string, Academic> = Object.fromEntries(
  rows.map(([id, iucn, habitat, altitude, morphology, distribution, references]) => [
    id,
    { iucn, habitat, altitude, morphology, distribution, references },
  ]),
);
