export type Category = 'ibreli' | 'yaprakli' | 'maki' | 'meyve';

export interface Region {
  district: string;
  note: string;
  coords: [number, number]; // [lat, lng]
}

export interface Species {
  id: string;
  name: string;
  latin: string;
  family: string;
  category: Category;
  height: string;
  bloom: string;
  desc: string;
  benefits: string[];
  regions: Region[];
  tag?: string; // örn. "Relikt", "Coğrafi İşaretli", "Anıt Ağaç"
}

export const CATEGORY_META: Record<
  Category,
  { label: string; color: string; soft: string }
> = {
  ibreli: { label: 'İbreli', color: '#2F5233', soft: '#e3ecdf' },
  yaprakli: { label: 'Yaprak Döken', color: '#57772e', soft: '#edf3dd' },
  maki: { label: 'Maki', color: '#96742a', soft: '#f5eedd' },
  meyve: { label: 'Meyve & Ekonomik', color: '#b0762a', soft: '#f8efdd' },
};

export const IZMIR_CENTER: [number, number] = [38.53, 27.35];

export const SPECIES: Species[] = [
  {
    id: 'kizilcam',
    name: 'Kızılçam',
    latin: 'Pinus brutia',
    family: 'Çamgiller (Pinaceae)',
    category: 'ibreli',
    height: '20–35 m',
    bloom: 'Şubat – Nisan (tozlaşma)',
    tag: 'İzmir’in en yaygın ağacı',
    desc: 'İzmir’in kıyı bandının karakteristik ağacıdır. Kırmızımsı-kahverengi kabuğu ve güneşe eğimli tepesiyle tanınır. Ege kıyılarında deniz seviyesinden 1.200 metreye kadar yayılış gösterir ve Akdeniz ikliminin kurak yazlarına son derece dayanıklıdır.',
    benefits: [
      'Eğimli arazilerde erozyonu önleyen güçlü kök sistemi',
      'Reçinesi endüstride (kolofoni, terebentin) kullanılır',
      'Hızlı büyümesiyle yüksek karbon tutma kapasitesi',
      'Yangın sonrası kozalakları ısıyla açılıp tohum saçarak ormanı yeniler',
      'Odunu inşaat, mobilya ve kağıt sanayisinde değerlidir',
      'Kurak alanların ağaçlandırılmasında birincil tür',
    ],
    regions: [
      { district: 'Karaburun', note: 'Yarımadanın tamamında saf kızılçam ormanları', coords: [38.64, 26.51] },
      { district: 'Çeşme', note: 'Ildır ve Reisdere çevresi kızılçam örtüsü', coords: [38.32, 26.3] },
      { district: 'Urla', note: 'İç kesimlerdeki tepelerde yoğun yayılış', coords: [38.32, 26.76] },
      { district: 'Bornova / Yamanlar', note: 'Yamanlar Dağı kızılçam sahası', coords: [38.52, 27.23] },
      { district: 'Menderes / Gümüldür', note: 'Kıyı bandı boyunca kesintisiz örtü', coords: [38.08, 27.03] },
      { district: 'Seferihisar', note: 'Sığacık çevresi ve iç tepeler', coords: [38.2, 26.84] },
      { district: 'Kemalpaşa', note: 'Nif Dağı etekleri', coords: [38.43, 27.42] },
    ],
  },
  {
    id: 'fistikcami',
    name: 'Fıstıkçamı',
    latin: 'Pinus pinea',
    family: 'Çamgiller (Pinaceae)',
    category: 'ibreli',
    height: '12–25 m',
    bloom: 'Nisan – Mayıs',
    tag: 'Kozak Yaylası',
    desc: 'Şemsiye biçimli görkemli tepesiyle tanınan fıstıkçamı, İzmir’de özellikle Bergama’nın Kozak Yaylası’nda yoğunlaşır. Kozak, Türkiye’nin en büyük fıstıkçamı üretim havzasıdır; bölge ekonomisinin bel kemiğidir.',
    benefits: [
      'Kozalaklarından elde edilen çam fıstığı yüksek katma değerli gıdadır',
      'Köy ekonomisine doğrudan gelir sağlar, kırdan kente göçü azaltır',
      'Granitik, fakir topraklarda bile yetişerek araziyi değerlendirir',
      'Geniş tepesi mikro iklim ve gölge oluşturur',
      'Türün gen kaynağı açısından Kozak ulusal önemdedir',
    ],
    regions: [
      { district: 'Bergama / Kozak', note: 'Yaklaşık 16 köyü kapsayan dev üretim havzası', coords: [39.22, 27.1] },
      { district: 'Dikili', note: 'Kıyı gerisi tepelerde dağınık gruplar', coords: [39.07, 26.89] },
      { district: 'Kınık', note: 'Bakırçay havzasının kuzeyinde yayılış', coords: [39.09, 27.38] },
    ],
  },
  {
    id: 'karacam',
    name: 'Karaçam',
    latin: 'Pinus nigra subsp. pallasiana',
    family: 'Çamgiller (Pinaceae)',
    category: 'ibreli',
    height: '25–40 m',
    bloom: 'Mart – Nisan',
    desc: 'Yüksek dağların ağacı olan karaçam, İzmir’de 900 metrenin üzerindeki serin ve nemli yükseltilerde görülür. Koyu yeşil iğne yaprakları ve derin çatlaklı kabuğuyla kızılçamdan ayrılır.',
    benefits: [
      'Yüksek kesimlerde su rejimini düzenler, kaynakları besler',
      'Düzgün gövdeli odunu yapı kerestesi olarak değerlidir',
      'Kar yüküne dayanıklı formuyla dağ ormanlarını kurar',
      'Yaban hayatı için barınak ve besin sağlar',
    ],
    regions: [
      { district: 'Ödemiş / Bozdağ', note: 'Bozdağ kütleşinin üst kesimleri', coords: [38.34, 28.09] },
      { district: 'Kemalpaşa / Nif Dağı', note: 'Zirveye yakın karaçam toplulukları', coords: [38.37, 27.37] },
      { district: 'Bornova / Yamanlar üst kesim', note: 'Karagöl çevresi', coords: [38.55, 27.22] },
    ],
  },
  {
    id: 'bozdag-goknari',
    name: 'Bozdağ Göknarı',
    latin: 'Abies nordmanniana subsp. bornmuelleriana',
    family: 'Çamgiller (Pinaceae)',
    category: 'ibreli',
    height: '30–45 m',
    bloom: 'Nisan – Mayıs',
    tag: 'Relikt tür',
    desc: 'Buzul dönemlerinden kalma bir kalıntı (relikt) olan Bozdağ göknarı, İzmir’de yalnızca Bozdağ’ın 1.500 metre üzerindeki serin ve sisli yamaçlarında yaşar. Anadolu’nun en batıya ulaşan göknar topluluklarından biridir.',
    benefits: [
      'Biyolojik çeşitlilik ve evrimsel miras açısından eşsiz gen kaynağı',
      'Sis suyunu toplayarak kaynak sularını besler',
      'Kütlevi orman yapısıyla karbon depolama gücü yüksektir',
      'Bilimsel araştırmalar ve doğa eğitimi için canlı laboratuvar',
    ],
    regions: [
      { district: 'Ödemiş / Bozdağ zirve', note: '1.500–2.159 m arası gölge yamaçlar', coords: [38.37, 28.11] },
    ],
  },
  {
    id: 'kermes-mesesi',
    name: 'Kermes Meşesi',
    latin: 'Quercus coccifera',
    family: 'Kayıngiller (Fagaceae)',
    category: 'maki',
    height: '1–4 m (çalı formunda)',
    bloom: 'Mart – Nisan',
    desc: 'Maki topluluğunun temel taşı olan kermes meşesi, kızılçam ormanlarının tahrip olduğu her yerde doğal olarak devreye girer. Dikenli derimsi yaprakları kuraklığa karşı kusursuz bir adaptasyondur.',
    benefits: [
      'Kurak ve taşlık yamaçlarda toprağı tutan süpürge kökleri',
      'Palamutları yaban hayvanları için kış besini',
      'Tahrip olmuş orman alanlarında toprak oluşumunu başlatır',
      'Kökünden elde edilen mazı geleneksel tabaklamada kullanılır',
    ],
    regions: [
      { district: 'Karaburun', note: 'Rüzgarlı sırtlarda yoğun maki', coords: [38.65, 26.55] },
      { district: 'Çeşme', note: 'Yarımada genelinde kızılçam altlığı', coords: [38.3, 26.28] },
      { district: 'Urla', note: 'İç kesimlerdeki tahrip alanları', coords: [38.34, 26.8] },
      { district: 'Karşıyaka / Yamanlar etek', note: 'Kuzey yamaçlarda maki kuşağı', coords: [38.5, 27.18] },
    ],
  },
  {
    id: 'piramit-mese',
    name: 'Pırnal Meşe',
    latin: 'Quercus ilex',
    family: 'Kayıngiller (Fagaceae)',
    category: 'maki',
    height: '5–20 m',
    bloom: 'Nisan – Mayıs',
    desc: 'Her dem yeşil bir meşe olan pırnal, derimsi koyu yeşil yapraklarıyla makinin ağaç boyuna ulaşabilen üyesidir. İzmir’in kırsalında anıtsal boyutlara erişen bireyleri görülür.',
    benefits: [
      'Yaprak dökmediği için yıl boyu karbon tutar',
      'Sert ve ağır odunu kaliteli yakacak ve kömür hammaddesidir',
      'Palamutları geleneksel olarak hayvan yemi olur',
      'Kuraklığa en dayanıklı ağaç formundaki meşedir',
    ],
    regions: [
      { district: 'Karaburun iç kesimleri', note: 'Yamaçlarda ağaç formunda topluluklar', coords: [38.62, 26.55] },
      { district: 'Seferihisar', note: 'Teos antik kenti çevresi', coords: [38.18, 26.82] },
      { district: 'Bergama kırsalı', note: 'Kozak çevresi geçiş kuşağı', coords: [39.1, 27.15] },
    ],
  },
  {
    id: 'mazi-mesesi',
    name: 'Mazı Meşesi',
    latin: 'Quercus infectoria',
    family: 'Kayıngiller (Fagaceae)',
    category: 'yaprakli',
    height: '8–15 m',
    bloom: 'Nisan – Mayıs',
    desc: 'Yaprak döken meşelerin en yaygınıdır. Dal uçlarındaki mazılar (arı kovanımsı oluşumlar) yüzyıllardır mürekkep, boya ve deri tabaklamada kullanılmıştır; Osmanlı’da en önemli ihracat kalemlerinden biriydi.',
    benefits: [
      'Mazısından elde edilen tanen: deri tabaklama ve mürekkep',
      'Palamudu hayvan yemi ve geleneksel gıda',
      'Geniş taç altı gölgesi mera ekosistemini destekler',
      'Tarım arazileri arasında biyolojik çeşitlilik adacıkları oluşturur',
    ],
    regions: [
      { district: 'Bergama', note: 'Bakırçay havzası yamaçları', coords: [39.12, 27.18] },
      { district: 'Ödemiş', note: 'Ova kenarı tepelikler', coords: [38.23, 27.97] },
      { district: 'Kiraz', note: 'Dağ eteği köyler çevresi', coords: [38.23, 28.2] },
      { district: 'Tire', note: 'Küçük Menderes havzası yükseltileri', coords: [38.09, 27.74] },
    ],
  },
  {
    id: 'palamut-mesesi',
    name: 'Palamut Meşesi',
    latin: 'Quercus ithaburensis subsp. macrolepis',
    family: 'Kayıngiller (Fagaceae)',
    category: 'yaprakli',
    height: '10–20 m',
    bloom: 'Nisan',
    tag: 'Tarihi tabaklama hammaddesi',
    desc: 'Halk arasında “kupariya” olarak bilinir. İri palamutlarının kupulası (dış kabuğu) tanence zengindir; tarih boyunca Bergama ve çevresinden gemilerle Avrupa’ya tabaklama hammaddesi olarak ihraç edilmiştir.',
    benefits: [
      'Kupula ihracatı tarihî bir bölge geliridir',
      'Görkemli gövdeleriyle kültürel peyzajın parçası, anıt ağaç statüsünde bireyler',
      'Palamutları koyun-keçi besiciliğinde önemli',
      'Geniş taçlı yapısıyla tarla sınırlarında gölgelik',
    ],
    regions: [
      { district: 'Bergama / Kozak çevresi', note: 'Kültürel peyzaj içinde dağınık anıtsal bireyler', coords: [39.15, 27.12] },
      { district: 'Dikili', note: 'Çandarlı yolu boyunca mera içi ağaçlar', coords: [39.05, 26.95] },
      { district: 'Kınık', note: 'Bakırçay kuzeyi yamaçlar', coords: [39.08, 27.35] },
    ],
  },
  {
    id: 'sakiz',
    name: 'Sakız Ağacı',
    latin: 'Pistacia lentiscus',
    family: 'Sakızgiller (Anacardiaceae)',
    category: 'maki',
    height: '2–6 m',
    bloom: 'Mart – Nisan',
    tag: 'Coğrafi işaret: Çeşme sakızı',
    desc: 'Gövdesinden sızan damlaların kuruyarak sakız olduğu, Akdeniz’in efsanevi ağacıdır. İzmir’de en verimli yetiştiği yer Çeşme Yarımadası’dır; “Çeşme sakızı” coğrafi işaretle tescillidir. Dünyada damla sakızının en bilinen iki merkezinden biri Çeşme’dir (diğeri Sakız Adası).',
    benefits: [
      'Damla sakızı: çiklet, şekerleme, ilaç ve kozmetik hammaddesi',
      'Antiseptik ve sindirim destekleyici özellikleriyle geleneksel tıpta kullanım',
      'Tescilli ürün olarak kırsal kalkınmaya doğrudan katkı',
      'Kurak ve kireçli topraklarda erozyona karşı örtü oluşturur',
    ],
    regions: [
      { district: 'Çeşme', note: 'Sakız bahçeleri ve doğal makilikler', coords: [38.32, 26.3] },
      { district: 'Alaçatı', note: 'Rüzgar almayan korunaklı vadiler', coords: [38.28, 26.37] },
      { district: 'Karaburun', note: 'Yarımadanın korunaklı güney yamaçları', coords: [38.63, 26.5] },
    ],
  },
  {
    id: 'menengic',
    name: 'Menengiç',
    latin: 'Pistacia terebinthus',
    family: 'Sakızgiller (Anacardiaceae)',
    category: 'maki',
    height: '3–8 m',
    bloom: 'Mart – Nisan',
    desc: 'Antep fıstığının yaban atasıdır; kültür fıstığı çeşitleri menengiç anacına aşılanır. Sonbaharda kızaran yaprakları makiye renk katar.',
    benefits: [
      'Meyvelerinden menengiç kahvesi ve “çitlembik” yağı elde edilir',
      'Antep fıstığı için doğal aşı anacı',
      'Reçinesi geleneksel olarak tıp ve boyacılıkta kullanılır',
      'Kuşlar için önemli bir sonbahar besini',
    ],
    regions: [
      { district: 'Urla', note: 'Maki kuşağında yaygın', coords: [38.33, 26.77] },
      { district: 'Seferihisar', note: 'Teos ve Sığacık çevresi', coords: [38.19, 26.83] },
      { district: 'Karaburun', note: 'Kıyı gerisi tepeler', coords: [38.64, 26.53] },
      { district: 'Foça', note: 'Taş ocakları çevresi makilikler', coords: [38.67, 26.76] },
    ],
  },
  {
    id: 'zeytin',
    name: 'Zeytin',
    latin: 'Olea europaea',
    family: 'Zeytingiller (Oleaceae)',
    category: 'meyve',
    height: '5–15 m',
    bloom: 'Nisan – Mayıs',
    tag: 'İzmir’in ölümsüz ağacı',
    desc: 'İzmir kırsalının ekonomik ve kültürel temelidir. Urla’daki Klazomenai’de bulunan MÖ 6. yüzyıla ait zeytinyağı işliği, Anadolu’nun bilinen en eski zeytinyağı üretim tesisidir. Binde yılı aşkın yaşa ulaşan anıt zeytinler bölgede hâlâ meyve verir.',
    benefits: [
      'Zeytinyağı: kalp sağlığı ve Akdeniz diyetinin merkezi',
      'Asırlık gövdeleriyle yaşayan kültür mirası',
      'Kuraklığa dayanıklı; sulamasız tarımla kırsal gelir sağlar',
      'Kırpıntısı ve karasuyu yeni yöntemlerle enerji ve gübreye dönüşür',
      'Yamaç arazilerde kalıcı örtü ile erozyon kontrolü',
    ],
    regions: [
      { district: 'Urla', note: 'Klazomenai antik işliği ve yoğun bahçeler', coords: [38.32, 26.77] },
      { district: 'Seferihisar', note: 'Teos çevresi zeytinlikler', coords: [38.2, 26.83] },
      { district: 'Menemen', note: 'Gediz ovası kenarı geniş bahçeler', coords: [38.6, 27.07] },
      { district: 'Aliağa', note: 'Kyme ve Myrina çevresi tarihî zeytinlikler', coords: [38.8, 27.0] },
      { district: 'Bergama', note: 'Bakırçay havzası zeytin kuşağı', coords: [39.12, 27.16] },
      { district: 'Selçuk', note: 'Efes çevresi ve Şirince yolu', coords: [37.95, 27.37] },
    ],
  },
  {
    id: 'defne',
    name: 'Defne (Akdeniz Defnesi)',
    latin: 'Laurus nobilis',
    family: 'Defnegiller (Lauraceae)',
    category: 'maki',
    height: '3–10 m',
    bloom: 'Mart – Nisan',
    desc: 'Antik çağda zafer ve kehanetin simgesi; yaprakları bugün mutfağın vazgeçilmez baharatıdır. Nemli dere kenarlarını ve korunaklı vadileri sever.',
    benefits: [
      'Yaprakları baharat ve uçucu yağ kaynağı',
      'Sinek ve böcek kaçırıcı doğal etki',
      'Dere kenarlarında kıyı ağaçlandırması ve bank stabilitesi',
      'Her dem yeşil yapısıyla peyzaj değeri',
    ],
    regions: [
      { district: 'Karşıyaka', note: 'Yamanlar dereleri boyunca doğal gruplar', coords: [38.48, 27.19] },
      { district: 'Selçuk', note: 'Meryem Ana vadisi çevresi', coords: [37.92, 27.35] },
      { district: 'Güzelbahçe', note: 'Korunaklı vadi içleri', coords: [38.36, 26.89] },
      { district: 'Bergama', note: 'Bakırçay boyu nemli kesimler', coords: [39.13, 27.2] },
    ],
  },
  {
    id: 'mersin',
    name: 'Mersin',
    latin: 'Myrtus communis',
    family: 'Mersingiller (Myrtaceae)',
    category: 'maki',
    height: '1–4 m',
    bloom: 'Mayıs – Haziran',
    desc: 'Beyaz çiçekleri ve mis kokulu yapraklarıyla makinin en zarif üyesidir. Mitolojide aşk ve güzellik tanrıçası Afrodit’e adanmıştır.',
    benefits: [
      'Yaprak ve meyvelerinden uçucu yağ (mersin suyu, kolonya)',
      'Meyveleri geleneksel likör ve reçel yapımında kullanılır',
      'Yaprakları antiseptik özellik taşır',
      'Arılar için değerli geç bahar nektarı kaynağı',
    ],
    regions: [
      { district: 'Karaburun', note: 'Kıyı makiliğinde bol', coords: [38.63, 26.52] },
      { district: 'Çeşme', note: 'Korunaklı koy gerileri', coords: [38.31, 26.29] },
      { district: 'Foça', note: 'Eski Foça çevresi', coords: [38.67, 26.75] },
      { district: 'Seferihisar', note: 'Sığacık koyları', coords: [38.19, 26.78] },
    ],
  },
  {
    id: 'keciboynuzu',
    name: 'Keçiboynuzu (Harnup)',
    latin: 'Ceratonia siliqua',
    family: 'Baklagiller (Fabaceae)',
    category: 'maki',
    height: '5–12 m',
    bloom: 'Eylül – Kasım',
    desc: 'Koyu yeşil, her dem yeşil yaprakları ve bakla benzeri meyveleriyle tanınır. “Harnup” adı Arapça’dan gelir; İzmir’in batı yarımadalarında doğal ve kültür popülasyonları bulunur.',
    benefits: [
      'Meyvesi keçiboynuzu unu ve pekmezi: yüksek lif ve mineral',
      'Kakao yerine sağlıklı alternatif olarak gıda sanayisinde',
      'Azot bağlayan kökleriyle fakir toprakları zenginleştirir',
      'Derin kök sistemiyle kuraklığa ve rüzgara dayanıklı',
    ],
    regions: [
      { district: 'Seferihisar', note: 'Teos antik kentinde anıtsal harnuplar', coords: [38.18, 26.81] },
      { district: 'Urla', note: 'Kıyı bandı ve iç köyler', coords: [38.32, 26.78] },
      { district: 'Karaburun', note: 'Mordoğan çevresi', coords: [38.52, 26.55] },
      { district: 'Güzelbahçe', note: 'Yelki ve Kahramandere', coords: [38.36, 26.88] },
    ],
  },
  {
    id: 'sandal',
    name: 'Sandal Ağacı & Kocayemiş',
    latin: 'Arbutus andrachne / Arbutus unedo',
    family: 'Fundagiller (Ericaceae)',
    category: 'maki',
    height: '3–8 m',
    bloom: 'Şubat – Mart',
    tag: 'Karaburun’a özgü görünüm',
    desc: 'Sandal ağacının turuncu-kızıl, kağıt gibi soyulan kabuğu İzmir florasının en dikkat çekici görüntülerinden biridir. Kocayemiş ise kırmızı, çilek benzeri meyveleriyle tanınır. İki tür Karaburun Yarımadası’nda yan yana görülür.',
    benefits: [
      'Kocayemiş meyvesi C vitamini yönünden zengin, yenebilir',
      'Arıcılık için önemli bir erken bahar kaynağı',
      'Kızıl kabuklu görünümüyle doğa turizmi değeri',
      'Türkiye’de yayılışının batı sınırını oluşturan özel popülasyonlar',
    ],
    regions: [
      { district: 'Karaburun', note: 'Yarımadanın en özgün ağaç toplulukları', coords: [38.66, 26.53] },
      { district: 'Çeşme', note: 'Korunaklı iç vadiler', coords: [38.3, 26.32] },
    ],
  },
  {
    id: 'cinar',
    name: 'Doğu Çınarı',
    latin: 'Platanus orientalis',
    family: 'Çınargiller (Platanaceae)',
    category: 'yaprakli',
    height: '20–35 m',
    bloom: 'Nisan – Mayıs',
    tag: 'Anıt ağaçlar',
    desc: 'Dere boylarının ve köy meydanlarının sultanı. Bergama’daki asırlık çınarlar gibi, İzmir’de çok sayıda çınar “anıt ağaç” olarak tescillidir. Dallanan dev gövdesiyle bir köyün ortak hafızasıdır.',
    benefits: [
      'Dev taçlı gölgesi: köy meydanlarının doğal toplanma alanı',
      'Dere kenarlarında taşkın ve yatak stabilitesi sağlar',
      'Kent içinde toz tutma ve serinletme kapasitesi yüksektir',
      'Kültürel miras: düğün, pazar ve kahve geleneklerinin mekânı',
    ],
    regions: [
      { district: 'Bergama', note: 'Bakırçay boyu ve anıt çınarlar', coords: [39.12, 27.19] },
      { district: 'Kemalpaşa', note: 'Nif Çayı boyunca sıralı çınarlar', coords: [38.43, 27.43] },
      { district: 'Tire', note: 'Kahrat dere çevresi', coords: [38.1, 27.75] },
      { district: 'Ödemiş', note: 'Küçük Menderes boyunca', coords: [38.24, 27.98] },
      { district: 'Bornova', note: 'Köy içi ve dere kenarları', coords: [38.47, 27.22] },
    ],
  },
  {
    id: 'servi',
    name: 'Mezarlık Servisi',
    latin: 'Cupressus sempervirens',
    family: 'Servigiller (Cupressaceae)',
    category: 'ibreli',
    height: '15–30 m',
    bloom: 'Şubat – Mart',
    desc: 'Dikey, kalem biçimli silüetiyle Ege peyzajının imzasıdır. İzmir’de hem doğal Akdeniz servisi toplulukları hem de rüzgâr perdesi ve peyzaj dikimleri olarak her yerdedir.',
    benefits: [
      'Tarla kenarlarında etkili rüzgar perdesi',
      'Az suyla yetişir; kurakçıl peyzajın temel ağacı',
      'Esansiyel yağı geleneksel tıpta kullanılır',
      'Uzun ömürlü odunu suya dayanıklıdır',
    ],
    regions: [
      { district: 'Karşıyaka', note: 'Doğal yayılış ve tarihi mezarlıklar', coords: [38.47, 27.15] },
      { district: 'Bornova', note: 'Yamaç dikimleri', coords: [38.46, 27.24] },
      { district: 'Selçuk', note: 'Ayasuluk çevresi', coords: [37.96, 27.38] },
      { district: 'Urla', note: 'Bağ yolları boyunca rüzgar perdeleri', coords: [38.31, 26.79] },
    ],
  },
  {
    id: 'kestane',
    name: 'Anadolu Kestanesi',
    latin: 'Castanea sativa',
    family: 'Kayıngiller (Fagaceae)',
    category: 'yaprakli',
    height: '20–30 m',
    bloom: 'Haziran – Temmuz',
    desc: 'Bozdağ ve Aydın Dağı eteklerinin nemli, serin yamaçlarında yetişir. Bal üretimi için de kritik önemdedir; kestane balı bölgenin aranan ürünüdür.',
    benefits: [
      'Meyvesi besleyici ve ekonomik değeri yüksek',
      'Uzun çiçeklenme dönemiyle kestane balının ana kaynağı',
      'Dağ köylerinde ahşap ve yakacak temini',
      'Nemli yamaçlarda toprak ve su dengesini korur',
    ],
    regions: [
      { district: 'Ödemiş / Bozdağ', note: '1.000 m üzeri nemli yamaçlar', coords: [38.33, 28.06] },
      { district: 'Ödemiş / Aydın Dağı etek', note: 'Gölcük çevresi', coords: [38.15, 28.02] },
      { district: 'Kiraz', note: 'Suludere ve dokuzlar çevresi', coords: [38.24, 28.22] },
    ],
  },
  {
    id: 'ceviz',
    name: 'Ceviz',
    latin: 'Juglans regia',
    family: 'Cevizgiller (Juglandaceae)',
    category: 'meyve',
    height: '15–25 m',
    bloom: 'Nisan – Mayıs',
    desc: 'Küçük Menderes havzasının yayla köylerinde sulu ve derin topraklarda yetişir. Kiraz ve Beydağ çevresindeki bahçeler bölgeye önemli gelir sağlar.',
    benefits: [
      'Omega-3 açısından zengin, yüksek değerli ürün',
      'Odunu en kıymetli mobilya kerestelerindendir',
      'Yaprak ve yeşil kabuğu geleneksel boyacılıkta kullanılır',
      'Geniş gölgesi hayvancılık yapılan köylerde önemli',
    ],
    regions: [
      { district: 'Kiraz', note: 'Yayla köylerinde ceviz bahçeleri', coords: [38.23, 28.21] },
      { district: 'Beydağ', note: 'Dağ eteği sulu araziler', coords: [38.09, 28.21] },
      { district: 'Ödemiş', note: 'Bozdağ etek köyleri', coords: [38.27, 28.02] },
    ],
  },
  {
    id: 'ihlamur',
    name: 'Gümüşi Ihlamur',
    latin: 'Tilia tomentosa',
    family: 'Ihlamurgiller (Tiliaceae)',
    category: 'yaprakli',
    height: '20–30 m',
    bloom: 'Haziran – Temmuz',
    desc: 'Yaz ortasında açan sarımsı çiçeklerinin kokusu bir mahalleyi sarabilir. İzmir’de dağ etekleri ve nemli vadilerde doğal, kent parklarında dikili olarak bulunur.',
    benefits: [
      'Çiçeği ıhlamur çayı: geleneksel kış içeceği',
      'Arıların en sevdiği nektar kaynaklarından',
      'Kentsel ısı adasına karşı güçlü gölge',
      'Lifleri geleneksel ip ve sepet yapımında',
    ],
    regions: [
      { district: 'Ödemiş / Bozdağ', note: 'Serin vadi içleri', coords: [38.35, 28.08] },
      { district: 'Buca / Kaynaklar', note: 'Nemli yamaç köyleri', coords: [38.34, 27.24] },
      { district: 'Bornova', note: 'Park ve kampüs ağaçlandırmaları', coords: [38.47, 27.23] },
    ],
  },
  {
    id: 'karaagac',
    name: 'Karaağaç',
    latin: 'Ulmus minor',
    family: 'Karaağaçgiller (Ulmaceae)',
    category: 'yaprakli',
    height: '15–25 m',
    bloom: 'Şubat – Mart',
    desc: 'Ova köylerinin ve tarla sınırlarının klasik ağacıdır. Ilımlı suyu seven karaağaç, Küçük Menderes ovasında doğal topluluklar oluşturur.',
    benefits: [
      'Elastik ve dayanıklı odunu: el arabası, sandık yapımı',
      'Ova peyzajında kuş türleri için yuva alanı',
      'Geniş gölgesiyle kırsal yaşamın parçası',
      'Dere içi setlerde toprak tutucu',
    ],
    regions: [
      { district: 'Torbalı', note: 'Küçük Menderes ovası tarla kenarları', coords: [38.18, 27.36] },
      { district: 'Bayındır', note: 'Ova ve dere boyları', coords: [38.22, 27.65] },
      { district: 'Tire', note: 'Ova içi köyler', coords: [38.1, 27.73] },
    ],
  },
  {
    id: 'kavak',
    name: 'Ak Kavak & Kara Kavak',
    latin: 'Populus alba / Populus nigra',
    family: 'Söğütgiller (Salicaceae)',
    category: 'yaprakli',
    height: '20–30 m',
    bloom: 'Mart – Nisan',
    desc: 'Hızlı büyümesiyle Anadolu’nun “ekonomi ağacı”dır. Bakırçay ve Gediz havzalarında dere boylarında ve koruluklarda yoğun yetiştirilir.',
    benefits: [
      'En hızlı büyüyen yerli ağaçlardan: lif ve sunta sanayisi',
      'Dere boylarında kıyı erozyonunu önler',
      'Rüzgar perdesi olarak tarımsal verimi korur',
      'Yüksek buharlaşmayla bataklık alanları kurutur',
    ],
    regions: [
      { district: 'Bergama', note: 'Bakırçay boyu koruluklar', coords: [39.14, 27.22] },
      { district: 'Menemen', note: 'Gediz havzası ova koruları', coords: [38.62, 27.09] },
      { district: 'Dikili', note: 'Bakırçay deltası çevresi', coords: [39.08, 26.92] },
    ],
  },
  {
    id: 'sogut',
    name: 'Söğüt',
    latin: 'Salix alba',
    family: 'Söğütgiller (Salicaceae)',
    category: 'yaprakli',
    height: '10–25 m',
    bloom: 'Mart – Nisan',
    desc: 'Su kenarlarının kaçınılmaz ağacı. Gediz deltası ve tüm dere boylarında, kökleri suya değen gruplar oluşturur. Esnek sürgünleri geleneksel sepetçiliğin hammaddesidir.',
    benefits: [
      'Taşkın dönemlerinde kıyı çizgisini tutan canlı set',
      'Salgından aspirin hammaddesi salisilin keşfi',
      'Sepetçilik ve örgü sanayisi için sürgün',
      'Sulak alan kuşları için barınak',
    ],
    regions: [
      { district: 'Menemen / Gediz Deltası', note: 'Sulak alan kenarları', coords: [38.6, 26.9] },
      { district: 'Bergama', note: 'Bakırçay yatağı boyunca', coords: [39.13, 27.21] },
      { district: 'Torbalı', note: 'Fetrek Çayı boyları', coords: [38.17, 27.34] },
    ],
  },
  {
    id: 'disbudak',
    name: 'Sivri Meyveli Dişbudak',
    latin: 'Fraxinus angustifolia',
    family: 'Zeytingiller (Oleaceae)',
    category: 'yaprakli',
    height: '15–25 m',
    bloom: 'Şubat – Mart',
    desc: 'Nemli ova ve taban arazilerinin ağacıdır. Gediz deltası gerisindeki ıslak çayırlıklarda doğal topluluklar kurar.',
    benefits: [
      'Esnek ve sağlam odunu: alet sapı ve spor malzemesi',
      'Taban suyu yüksek arazilerde yetişebilen nadir ağaçlardan',
      'Gölge toleranslı alt katmanla zengin orman yapısı kurar',
    ],
    regions: [
      { district: 'Menemen / Gediz ovası', note: 'Islak taban araziler', coords: [38.61, 27.02] },
      { district: 'Torbalı', note: 'Ova içi nemli kesimler', coords: [38.19, 27.38] },
    ],
  },
  {
    id: 'ardic',
    name: 'Bodur & Boylu Ardıç',
    latin: 'Juniperus oxycedrus / Juniperus excelsa',
    family: 'Servigiller (Cupressaceae)',
    category: 'ibreli',
    height: '2–12 m',
    bloom: 'Şubat – Mart',
    desc: 'Kurak dağ yamaçlarının dayanıklı bekçisi. İğne yapraklı türleri (bodur ardıç) maki içinde, boylu ardıç ise Bozdağ ve Nif’in yükseklerinde ağaç formunda görülür.',
    benefits: [
      'Kozalağından ardıç katranı: geleneksel tıp ve kozmetik',
      'En fakir, kayalık yamaçlarda bile toprak tutar',
      'Meyveleri yaban hayvanlarının kışlık besini',
      'Yüzlerce yıl yaşayabilen karbon arşivi',
    ],
    regions: [
      { district: 'Ödemiş / Bozdağ', note: 'Yüksek kayalık yamaçlar', coords: [38.36, 28.1] },
      { district: 'Kemalpaşa / Nif', note: 'Kızılçam üstü kuşak', coords: [38.38, 27.38] },
      { district: 'Karaburun', note: 'Bodur ardıç maki içinde', coords: [38.65, 26.54] },
    ],
  },
  {
    id: 'incir',
    name: 'İncir',
    latin: 'Ficus carica',
    family: 'Dutgiller (Moraceae)',
    category: 'meyve',
    height: '5–10 m',
    bloom: 'Çiçek içte; meyve Haziran – Eylül',
    tag: 'Karşıyaka’nın simgesi',
    desc: 'Karşıyaka’ya adını veren efsaneye konu olan incir, İzmir kıyı bahçelerinin vazgeçilmezidir. Kayalık yamaçlardan yarımadalara kadar kendiliğinden de yetişir.',
    benefits: [
      'Taze ve kuru meyve: lif, kalsiyum ve doğal şeker kaynağı',
      'İncir arısıyla karşılıklı evrimin ders kitabı örneği',
      'Kurak bahçe tarımında sulamasız yetişir',
      'Yamaç bahçelerinde teras stabilitesi',
    ],
    regions: [
      { district: 'Karşıyaka', note: 'Tarihi incir bahçelerinin yurdu', coords: [38.46, 27.11] },
      { district: 'Menemen', note: 'Gediz ovası kenarı bahçeler', coords: [38.59, 27.06] },
      { district: 'Menderes', note: 'Ovacık ve Görece çevresi', coords: [38.25, 27.13] },
      { district: 'Torbalı', note: 'Ova bahçeleri', coords: [38.17, 27.35] },
    ],
  },
  {
    id: 'dut',
    name: 'Beyaz & Kara Dut',
    latin: 'Morus alba / Morus nigra',
    family: 'Dutgiller (Moraceae)',
    category: 'meyve',
    height: '8–15 m',
    bloom: 'Nisan – Mayıs',
    desc: 'Kemalpaşa ve köylerinin meydan ağacıdır. İpek böcekçiliğinin tarihî hammaddesi olan beyaz dut, İzmir’in dokuma geçmişiyle de bağlantılıdır.',
    benefits: [
      'Meyvesi taze, kurutulmuş ve pekmez olarak tüketilir',
      'Beyaz dut yaprağı ipek böceğinin tek besini',
      'Hızlı büyüyen gölge ağacı',
      'Kuşlar için yaz başı besin şöleni',
    ],
    regions: [
      { district: 'Kemalpaşa', note: 'Köy meydanları ve bağ bahçeler', coords: [38.42, 27.41] },
      { district: 'Bergama', note: 'Köy içi bahçeler', coords: [39.11, 27.17] },
      { district: 'Ödemiş', note: 'Ova kenarı köyler', coords: [38.22, 27.96] },
    ],
  },
  {
    id: 'erguvan',
    name: 'Erguvan',
    latin: 'Cercis siliquastrum',
    family: 'Baklagiller (Fabaceae)',
    category: 'yaprakli',
    height: '4–8 m',
    bloom: 'Nisan – Mayıs (yapraktan önce)',
    desc: 'Yapraklanmadan önce gövdesini bile mor-çiçek çiçeklere bulayan erguvan, baharın İzmir’deki en görkemli habercisidir. Doğal olarak maki içinde bulunur.',
    benefits: [
      'Erken baharda arılar için hayati nektar kaynağı',
      'Köklerinde azot bağlama: toprağı besler',
      'Çiçekleri yenilebilir; geleneksel mutfaklarda süsleme',
      'Yüksek peyzaj değeri: kent parklarının yıldızı',
    ],
    regions: [
      { district: 'Karaburun', note: 'Maki içi doğal bireyler', coords: [38.63, 26.51] },
      { district: 'Urla', note: 'Bağ yolu çevreleri', coords: [38.33, 26.78] },
      { district: 'Konak / kent içi', note: 'Park ve bahçe dikimleri', coords: [38.42, 27.13] },
    ],
  },
  {
    id: 'citlenbik',
    name: 'Çitlenbik',
    latin: 'Celtis australis',
    family: 'Karaağaçgiller (Cannabaceae/Ulmaceae)',
    category: 'yaprakli',
    height: '10–20 m',
    bloom: 'Nisan',
    desc: 'Sıcak ve kurak yamaçların gösterişsiz ama dirençli ağacı. Gri, pürüzsüz kabuğu ve küçük kara meyveleriyle tanınır.',
    benefits: [
      'Aşırı kurak ve kireçli yamaçlarda ağaç örtüsü kurabilir',
      'Meyveleri kuş besini; geleneksel olarak yenir',
      'Sert ve esnek odunu alet yapımında',
      'Kentsel kurakçıl peyzaj için ideal',
    ],
    regions: [
      { district: 'Karşıyaka yamaçları', note: 'Güney bakan sıcak yamaçlar', coords: [38.47, 27.17] },
      { district: 'Karaburun', note: 'Kayalık kıyı gerileri', coords: [38.62, 26.52] },
      { district: 'Selçuk', note: 'Efes antik kenti çevresi', coords: [37.94, 27.36] },
    ],
  },
  {
    id: 'mandalina',
    name: 'Satsuma Mandalinası',
    latin: 'Citrus unshiu',
    family: 'Turunçgiller (Rutaceae)',
    category: 'meyve',
    height: '3–5 m',
    bloom: 'Nisan – Mayıs (beyaz, kokulu)',
    tag: 'Seferihisar’ın kimliği',
    desc: 'Seferihisar ve Gümüldür havzasının kimlik ürünüdür. İlkbaharda beyaz çiçeklerinin kokusu tüm körfezi sarar; sonbaharda kasalara dolarak ihracata gider.',
    benefits: [
      'İlçe ekonomisinin ana ihracat ürünü',
      'Çiçek döneminde yoğun arıcılık faaliyeti',
      'Yerel festival ve kırsal turizmin merkezi',
      'Küçük aile işletmeleri için istikrarlı gelir',
    ],
    regions: [
      { district: 'Seferihisar', note: 'Satsuma bahçelerinin merkezi', coords: [38.21, 26.85] },
      { district: 'Menderes / Gümüldür', note: 'Körfez havzası bahçeleri', coords: [38.09, 27.02] },
    ],
  },
];

export interface District {
  name: string;
  coords: [number, number];
}

export const HOTSPOTS: District[] = [
  { name: 'Bozdağ', coords: [38.36, 28.09] },
  { name: 'Kozak Yaylası', coords: [39.2, 27.1] },
  { name: 'Karaburun Yarımadası', coords: [38.64, 26.52] },
  { name: 'Çeşme Yarımadası', coords: [38.31, 26.3] },
  { name: 'Gediz Deltası', coords: [38.6, 26.9] },
  { name: 'Nif Dağı', coords: [38.38, 27.37] },
  { name: 'Yamanlar Dağı', coords: [38.53, 27.22] },
  { name: 'Bakırçay Havzası', coords: [39.13, 27.2] },
  { name: 'Küçük Menderes Havzası', coords: [38.15, 27.7] },
];


/* ------------------------------------------------------------------ */
/* Akademik veri katmanı: her tür için habitat, IUCN, morfoloji vb.   */
/* ------------------------------------------------------------------ */

export interface Academic {
  iucn: string;
  habitat: string;
  altitude: string;
  morphology: string;
  distribution: string;
  references: string[];
}

const REF_DAVIS = 'Davis, P.H. (ed.) (1965–1988). Flora of Turkey and the East Aegean Islands, Vol. 1–10. Edinburgh University Press.';
const REF_GUNER = 'Güner, A. et al. (2012). Türkiye Bitkileri Listesi (Damarlı Bitkiler). Nezahat Gökyiğit Botanik Bahçesi Yayınları, İstanbul.';
const REF_YALTIRIK = 'Yaltırık, F. & Efe, A. (1989). Türkiye’nin Önemli Orman Ağaçları ve Yüzeyleri. İ.Ü. Orman Fakültesi Yayınları.';
const REF_TUBIVES = 'TÜBİVES — Türkiye Bitkileri Veri Servisi, tür yayılış ve örnek kayıtları.';
const REF_GBIF = 'GBIF — Global Biodiversity Information Facility, tür dağılım kayıtları (gbif.org).';
const REF_ANSIN = 'Ansin, R. & Özkan, Z.C. (2006). Tohumlu Bitkiler (Spermatophyta); Odunsu Taksonlar. KTÜ Orman Fakültesi.';
const REF_EFE = 'Efe, A. (1987). Bergama–Kozak Yöresinin Florası ve Vejetasyonu. E.Ü. Fen Fakültesi, İzmir.';
const REF_KULTUR = 'Kültür, Ş. (2008). Gediz Deltası florası ve koruma değerleri. Ege Üniversitesi.';
const REF_KAYNACIK = 'Kaynacık, H. (1970). Kızılçamın (Pinus brutia Ten.) silvikültürel özellikleri. İ.Ü. Orman Fakültesi Dergisi.';

export const ACADEMIC: Record<string, Academic> = {
  kizilcam: {
    iucn: 'LC (Asgari Endişe)',
    habitat: 'Akdeniz kıyı kuşağı; kurak, kireçtaşı ve marn yamaçlar, maki vejetasyonu üstü orman kuşağı.',
    altitude: '0 – 1.200 m (İzmir’de optimal 100–800 m)',
    morphology: 'Kırmızımsı-kahverengi, plakalar halinde soyulan kabuk; 10–16 cm’lik çiftli iğne yapraklar; serotinous (ısıyla açılan) kozalaklar yangın ekolojisine adapte.',
    distribution: 'Doğu Akdeniz elementi: Türkiye, Kıbrıs, Girit, Suriye, Lübnan. Türkiye’de kıyı kuşağının en geniş yayılışlı çamı; İzmir’de hakim orman kurucu.',
    references: [REF_KAYNACIK, REF_DAVIS, REF_GUNER, REF_TUBIVES],
  },
  fistikcami: {
    iucn: 'LC (Asgari Endişe)',
    habitat: 'Kurak, güneşli yamaçlar; granitik ve kireçtaşı ana kaya üzeri fakir topraklar; kıyı Akdeniz kuşağı.',
    altitude: '0 – 600 m',
    morphology: 'Şemsiye (parasol) biçimli yayvan taç; 8–15 cm iğneler; iri, 3 yılda olgunlaşan kozalaklar; yenilebilir tohum (çam fıstığı).',
    distribution: 'Akdeniz havzası boyunca (İberya’dan Anadolu’ya). Türkiye’de en büyük doğal-yarı doğal havza İzmir–Bergama Kozak Yaylası (yaklaşık 17.000 ha).',
    references: [REF_EFE, REF_DAVIS, REF_GUNER, REF_GBIF],
  },
  karacam: {
    iucn: 'LC (Asgari Endişe)',
    habitat: 'Serin ve nemli dağ kuşağı; kuzey yamaçlarda saf veya göknar-kayın karışık meşcereler.',
    altitude: '900 – 2.100 m',
    morphology: 'Koyu yeşil, sert 8–15 cm iğneler; kalın, derin çatlaklı koyu kabuk; konik-geniş taç; düzgün uzun gövde.',
    distribution: 'Anadolu’nun dağ kuşağında geniş yayılış; İzmir’de yalnızca Bozdağ, Nif ve Yamanlar’ın üst kesimlerinde relikt topluluklar.',
    references: [REF_YALTIRIK, REF_DAVIS, REF_ANSIN],
  },
  'bozdag-goknari': {
    iucn: 'NT (Tehdide Yakın) — dar yayılışlı alt tür',
    habitat: '1.500 m üzeri serin, sisli kuzey yamaçlar; derin, nemli dağ toprakları.',
    altitude: '1.500 – 2.159 m (Bozdağ zirve kuşağı)',
    morphology: 'Konik form; düz sıralı, altı iki beyaz stoma bantlı yapraklar; dik duran 12–20 cm’lik kozalaklar; 45 m’ye ulaşan gövde.',
    distribution: 'Bornmüller göknarı: Anadolu’nun kuzey-orta dağları; İzmir Bozdağ popülasyonu türün en batı uç topluluklarından (buzul dönemi relikti).',
    references: [REF_DAVIS, REF_GUNER, REF_YALTIRIK, REF_TUBIVES],
  },
  'kermes-mesesi': {
    iucn: 'LC',
    habitat: 'Maki; tahrip olmuş kızılçam sahaları, taşlık ve kireçli yamaçlar, garig geçişleri.',
    altitude: '0 – 1.000 m',
    morphology: '1–4 m çalı (nadiren küçük ağaç); dikenli, derimsi, altı tozlu yapraklar; sert palamutlar; kermes böceği (Kermes vermilio) ile tarihsel ilişki.',
    distribution: 'Akdeniz havzası genel; Batı Anadolu maki kuşağının kurucu türü. İzmir yarımadalarında dominant.',
    references: [REF_DAVIS, REF_GUNER, REF_TUBIVES],
  },
  'piramit-mese': {
    iucn: 'LC',
    habitat: 'Derin topraklı maki kuşağı ve orman açıklıkları; korunaklı vadiler.',
    altitude: '0 – 900 m',
    morphology: 'Her dem yeşil, 5–20 m ağaç; koyu yeşil derimsi yapraklar; uzun sivri palamutlar; gri-siyah çatlaklı kabuk.',
    distribution: 'Batı ve Orta Akdeniz; Türkiye’de Ege ve Akdeniz kıyı kuşağında ağaç boyuna ulaşabilen tek her dem yeşil meşe.',
    references: [REF_DAVIS, REF_ANSIN, REF_GBIF],
  },
  'mazi-mesesi': {
    iucn: 'LC',
    habitat: 'Yaprak döken meşe toplulukları; tepe ve yamaçlarda, tarım arazisi sınırlarında mera-ağaç karışımı değer sistemleri.',
    altitude: '300 – 1.400 m',
    morphology: '8–15 m; derin loplu yapraklar; dal uçlarında tanence zengin mazılar (gal oluşumu); gri-kahve çatlaklı kabuk.',
    distribution: 'Güneydoğu Avrupa, Anadolu, İran. Türkiye’de en yaygın yaprak döken meşe; Osmanlı dönemi mazı ihracatının ana kaynağı.',
    references: [REF_DAVIS, REF_GUNER, REF_YALTIRIK],
  },
  'palamut-mesesi': {
    iucn: 'LC',
    habitat: 'Sıcak, kurak ova ve tepe kuşağı; mera içi dağınık anıtsal bireyler (kültürel peyzaj).',
    altitude: '0 – 800 m',
    morphology: '10–20 m, geniş yuvarlak taç; iri palamutların kupulası kalın ve pul dizilimli (macrolepis); sonbaharda sararan derimsi yapraklar.',
    distribution: 'Doğu Akdeniz (Balkanlar, Anadolu, Suriye). Bakırçay havzası kupula (valonya) ihracatının tarihî merkezi.',
    references: [REF_DAVIS, REF_EFE, REF_TUBIVES],
  },
  sakiz: {
    iucn: 'LC',
    habitat: 'Kıyı makiliği; kireçli, taşlık ve rüzgârdan korunaklı güney yamaçlar; geleneksel sakız bahçeleri.',
    altitude: '0 – 500 m',
    morphology: '2–6 m her dem yeşil çalı-küçük ağaç; karşılıklı parçalı (kanatlı rachisli) yapraklar; gövdeden damla halinde sızan reçine (mastic).',
    distribution: 'Akdeniz havzası genel. Ticari damla sakızı üretimi Çeşme Yarımadası ve Sakız Adası ile sınırlı; coğrafi işaretli ürün.',
    references: [REF_DAVIS, REF_GUNER, REF_GBIF],
  },
  menengic: {
    iucn: 'LC',
    habitat: 'Maki ve orman kenarları; kurak, kireçli yamaçlar; tarla sınırları.',
    altitude: '0 – 1.200 m',
    morphology: '3–8 m yaprak döken çalı-ağaç; tüysü bileşik yapraklar sonbaharda kızarır; kırmızıdan maviye dönen küçük meyveler; kesif reçine.',
    distribution: 'Güney Avrupa’dan Orta Asya’ya. Pistacia cinsinin Anadolu’daki ana yaban türü; Antep fıstığı (P. vera) için doğal aşı anacı.',
    references: [REF_DAVIS, REF_GUNER, REF_ANSIN],
  },
  zeytin: {
    iucn: 'LC',
    habitat: 'Kurakçıl kıyı kuşağı; teraslı yamaç bahçeleri; doğal forma (delice) maki içinde rastlanır.',
    altitude: '0 – 600 m',
    morphology: '5–15 m her dem yeşil; gümüşi-alt yapraklar; yıllar içinde burgulu, oyuk gövde; anıtsal bireyler 1.000+ yaş.',
    distribution: 'Akdeniz havzasında kültür; yaban formu Doğu Akdeniz kökenli. İzmir–Urla Klazomenai işliği (MÖ 6. yy) Anadolu’nun en eski zeytinyağı tesisi.',
    references: [REF_DAVIS, REF_GUNER, REF_TUBIVES, REF_GBIF],
  },
  defne: {
    iucn: 'LC',
    habitat: 'Nemli dere kenarları, korunaklı vadi içleri; maki içinde gölge mikro-habitatlar.',
    altitude: '0 – 700 m',
    morphology: '3–10 m her dem yeşil; aromatik, dalgalı kenarlı derimsi yapraklar; siyah parlak meyve; uçucu yağ bakımından zengin.',
    distribution: 'Akdeniz ve Makaronezya. Anadolu’da kıyı kuşağı boyunca doğal; mitolojide (Daphne) ve antik çağ ritüellerinde merkezî.',
    references: [REF_DAVIS, REF_GUNER],
  },
  mersin: {
    iucn: 'LC',
    habitat: 'Kıyı makiliği, koy gerileri ve korunaklı yamaçlar; kızılçam altlığı.',
    altitude: '0 – 500 m',
    morphology: '1–4 m her dem yeşil çalı; karşılıklı, yağ bezecikli aromatik yapraklar; beyaz fırça çiçekler; mavi-siyah meyve.',
    distribution: 'Akdeniz havzası genel; mitolojide Afrodit’e adanmış tür. Ege kıyı makisinin karakteristik elemanı.',
    references: [REF_DAVIS, REF_TUBIVES],
  },
  keciboynuzu: {
    iucn: 'LC',
    habitat: 'Kıyı kuşağı kurak yamaçlar, maki ve antik kent çevreleri; kireçtaşı ana kaya.',
    altitude: '0 – 500 m',
    morphology: '5–12 m her dem yeşil; parlak parçalı yapraklar; 10–30 cm’lik bakla meyveler (yüksek şeker ve lif); derin kazık kök.',
    distribution: 'Akdeniz havzası (muhtemel Doğu Akdeniz kökenli, eski kültür yayılışı). Teos ve Karaburun’da anıtsal bireyler.',
    references: [REF_DAVIS, REF_GUNER, REF_GBIF],
  },
  sandal: {
    iucn: 'LC',
    habitat: 'Maki içi korunaklı yamaç ve vadiler; kireçtaşı ve volkanik ana kaya.',
    altitude: '0 – 800 m',
    morphology: 'A. andrachne: turuncu-kızıl soyulan kabuk, kışın yaprak döken-geçici; A. unedo: her dem yeşil, çilek benzeri kırmızı meyve.',
    distribution: 'A. andrachne: Doğu Akdeniz; Türkiye’de en yoğun ve batı uç popülasyonları Karaburun Yarımadası’nda. A. unedo: Akdeniz genel.',
    references: [REF_DAVIS, REF_GUNER, REF_TUBIVES],
  },
  cinar: {
    iucn: 'DD/LC',
    habitat: 'Dere yatakları, alüvyal tabanlar, köy meydanları; yüksek taban suyu.',
    altitude: '0 – 1.100 m',
    morphology: '20–35 m; pul pul soyulan açık renk kabuk; derin loplu geniş yapraklar; sarkan küre çiçek-meyve toplulukları.',
    distribution: 'Balkanlar’dan İran’a. Anadolu’da kültürel peyzajın parçası; İzmir’de çok sayıda tescilli anıt çınar.',
    references: [REF_DAVIS, REF_ANSIN, REF_YALTIRIK],
  },
  servi: {
    iucn: 'LC',
    habitat: 'Doğal topluluklar kireçtaşı yamaçlarda; yaygın kültür: rüzgâr perdesi, mezarlık ve yol ağaçlandırması.',
    altitude: '0 – 1.000 m',
    morphology: '15–30 m; kalem biçimli (var. horizontalis yayvan) form; pul yapraklı koyu yeşil sürgünler; küremsi kozalak.',
    distribution: 'Doğu Akdeniz kökenli; antik çağdan beri tüm havzada kültür. İzmir kent peyzajının karakteristik silüeti.',
    references: [REF_DAVIS, REF_ANSIN, REF_TUBIVES],
  },
  kestane: {
    iucn: 'LC',
    habitat: 'Nemli, serin dağ yamaçları; kireçsiz, derin topraklar; sis kuşağı.',
    altitude: '600 – 1.400 m',
    morphology: '20–30 m; uzun dişli yapraklar; erkek çiçekler uzun kediciklerde; dikenli kupula içinde 2–3 yenilebilir meyve.',
    distribution: 'Güney Avrupa ve Anadolu; Ege’de Bozdağ ve Aydın Dağı eteklerinde yayla kuşağında; kestane balı üretim kuşağı.',
    references: [REF_DAVIS, REF_YALTIRIK, REF_TUBIVES],
  },
  ceviz: {
    iucn: 'LC',
    habitat: 'Derin, serinletilmiş ve sulu vadi tabanları; yayla köyü bahçeleri.',
    altitude: '400 – 1.600 m',
    morphology: '15–25 m; büyük tüysü bileşik yapraklar; yeşil dış kabuklu meyve; koyu renkli değerli odun.',
    distribution: 'Balkanlar’dan Himalaya’ya; Anadolu’da eski kültür. Küçük Menderes havzasının yayla kuşağında yoğun.',
    references: [REF_DAVIS, REF_ANSIN],
  },
  ihlamur: {
    iucn: 'LC',
    habitat: 'Serin vadi içleri, nemli dağ etekleri; kent parklarında dikili.',
    altitude: '300 – 1.500 m',
    morphology: '20–30 m; kalp biçimli, altı gümüşi tüylü yapraklar; sarımsı, güçlü kokulu çiçek demetleri; brakte ile sarkan meyve.',
    distribution: 'Orta-Güney Avrupa ve Batı Anadolu. Tıbbi çiçek (tiliae flos) ve önemli nektar kaynağı.',
    references: [REF_DAVIS, REF_GUNER],
  },
  karaagac: {
    iucn: 'DD (Dutch elm hastalığı baskısı altında)',
    habitat: 'Ova ve dere boyları, taban araziler; tarla sınır ağaçları.',
    altitude: '0 – 900 m',
    morphology: '15–25 m; asimetrik tabanlı dişli yapraklar; kanatlı yassı tohumlar (samara); gri çatlaklı kabuk.',
    distribution: 'Avrupa ve Batı Asya; Küçük Menderes ovasında doğal taban ormanı kalıntıları.',
    references: [REF_DAVIS, REF_TUBIVES],
  },
  kavak: {
    iucn: 'LC',
    habitat: 'Dere boyları, alüvyal tabanlar, koruluklar ve plantasyonlar.',
    altitude: '0 – 1.200 m',
    morphology: '20–30 m hızlı büyüme; P. alba: altı beyaz keçeli yaprak; P. nigra: üçgen-elmas yaprak; kedicik çiçekler.',
    distribution: 'Avrasya genel; Bakırçay ve Gediz havzalarında hem doğal koruluklar hem ekonomik plantasyon.',
    references: [REF_DAVIS, REF_ANSIN],
  },
  sogut: {
    iucn: 'LC',
    habitat: 'Akarsu kıyıları, sulak alan kenarları, sazlık-söğütlük geçişleri.',
    altitude: '0 – 1.000 m',
    morphology: '10–25 m; dar, ipeksi tüylü mızrak yapraklar; esnek sürgünler; su köklenen canlı çelikler.',
    distribution: 'Avrupa, Batı ve Orta Asya; Gediz Deltası sulak alanlarında kıyı koridorunun kurucusu.',
    references: [REF_KULTUR, REF_DAVIS, REF_GUNER],
  },
  disbudak: {
    iucn: 'LC',
    habitat: 'Taban suyu yüksek ıslak çayırlar, ova içi nemli korular.',
    altitude: '0 – 700 m',
    morphology: '15–25 m; karşılıklı dar parçalı yapraklar; kanatlı tohum (samara); yapraktan önce açan çiçekler.',
    distribution: 'Güney Avrupa’dan İran’a; Gediz ovası ve Küçük Menderes’te taban ormanı elemanı.',
    references: [REF_DAVIS, REF_TUBIVES],
  },
  ardic: {
    iucn: 'LC',
    habitat: 'Kurak-kayalık dağ yamaçları (boylu ardıç); maki içi güneşli sırtlar (bodur ardıç).',
    altitude: '0 – 1.800 m',
    morphology: 'J. oxycedrus: sivri iğne yapraklı çalı; J. excelsa: 12 m’ye ulaşan pul yapraklı ağaç; etli küçük kozalaklar.',
    distribution: 'Akdeniz ve Anadolu genel; ardıç katranı (kozalak destilasyonu) geleneksel eczacılık hammaddesi.',
    references: [REF_DAVIS, REF_ANSIN, REF_GUNER],
  },
  incir: {
    iucn: 'LC',
    habitat: 'Kıyı bahçeleri, kayalık yamaçlar, duvar dipleri; yabanlaşmış popülasyonlar.',
    altitude: '0 – 800 m',
    morphology: '5–10 m; büyük el ayası loplu yapraklar; süt özlü; içe dönük çiçeklenme (syconium) ve incir arısı (Blastophaga psenes) ile zorunlu mutualizm.',
    distribution: 'Güneybatı Asya kökenli, Akdeniz’de antik kültür; Ege kıyı kuşağında doğallaşmış.',
    references: [REF_DAVIS, REF_GUNER, REF_GBIF],
  },
  dut: {
    iucn: 'LC',
    habitat: 'Köy meydanları, bahçeler, dere kenarları; sulu ova kuşağı.',
    altitude: '0 – 1.200 m',
    morphology: '8–15 m; kalp biçimli loplu yapraklar (ipek böceği besini); bileşik görünümlü sulu meyve.',
    distribution: 'M. alba Asya kökenli (ipekçilikle yayıldı), M. nigra Batı Asya; İzmir ova ve köy peyzajında yaygın.',
    references: [REF_DAVIS, REF_TUBIVES],
  },
  erguvan: {
    iucn: 'LC',
    habitat: 'Maki içi korunaklı yamaçlar, orman kenarları; kireçli topraklar.',
    altitude: '0 – 800 m',
    morphology: '4–8 m; kalp biçimli yapraklar; yapraktan önce gövde ve dallarda (kauliflori) mor-pembe kelebek çiçekler; yassı bakla meyve.',
    distribution: 'Güney Avrupa ve Batı Asya; Anadolu’da bahar fenolojisinin simge türü.',
    references: [REF_DAVIS, REF_GUNER],
  },
  citlenbik: {
    iucn: 'LC',
    habitat: 'Aşırı kurak, güney bakan kireçli yamaçlar; taşlık kıyı gerileri.',
    altitude: '0 – 800 m',
    morphology: '10–20 m; pürüzsüz gri-sorguçlu kabuk; asimetrik küçük yapraklar; tek çekirdekli kara meyveler.',
    distribution: 'Güney Avrupa, Kuzey Afrika, Batı Asya; Ege’de kurakçıl yamaçların dirençli ağacı.',
    references: [REF_DAVIS, REF_TUBIVES],
  },
  mandalina: {
    iucn: 'Kültür türü (değerlendirme dışı)',
    habitat: 'Don riski düşük körfez havzaları; korunaklı ova bahçeleri.',
    altitude: '0 – 300 m',
    morphology: '3–5 m her dem yeşil; kanatlı yaprak sapı; beyaz, yoğun kokulu çiçekler; kabuğu kolay soyulan satsuma meyvesi.',
    distribution: 'Japonya kökenli; Türkiye’de Ege kıyı kuşağında, özellikle Seferihisar–Gümüldür havzasında yoğunlaşan ticari üretim.',
    references: [REF_GUNER, 'TÜİK bitkisel üretim istatistikleri, İzmir turunçgil raporları.'],
  },
  kizilagac: {
    iucn: 'LC',
    habitat: 'Akarsu kıyıları, sazlık-sulak alan geçişleri; doymuş taban toprakları.',
    altitude: '0 – 1.000 m',
    morphology: '15–25 m; yapışkan sürgünler; yuvarlak dişli yapraklar; kozalak benzeri odunlaşmış meyve kümeleri; azot bağlayıcı kök nodülleri (Frankia).',
    distribution: 'Avrupa ve Batı Asya; Gediz Deltası ve Bakırçay kıyı koridorlarında doğal.',
    references: [REF_KULTUR, REF_DAVIS, REF_ANSIN],
  },
  'sacli-mese': {
    iucn: 'LC',
    habitat: 'Güneşli, kurak-ılıman yamaçlar; maki üstü geçiş kuşağı ve orman açıklıkları.',
    altitude: '200 – 1.300 m',
    morphology: '5–15 m yaprak döken; altı tüylü (pubescens) yapraklar; uzun saplı palamutlar; derin çatlaklı kabuk.',
    distribution: 'Orta-Güney Avrupa ve Anadolu; İzmir iç kesimlerinde yaprak döken meşe topluluklarının elemanı.',
    references: [REF_DAVIS, REF_GUNER],
  },
  'ova-akcaagaci': {
    iucn: 'LC',
    habitat: 'Işık ormanları, çit ve dere kenarları; ılıman ova-tepe kuşağı.',
    altitude: '0 – 1.200 m',
    morphology: '8–15 m; 5 loplu küçük yapraklar sonbaharda altın sarısı; kanatlı ikiz meyveler (samara).',
    distribution: 'Avrupa ve Batı Anadolu; Gediz ve Bakırçay havzalarında dağınık.',
    references: [REF_DAVIS, REF_TUBIVES],
  },
  kizilcik: {
    iucn: 'LC',
    habitat: 'Orman kenarları, çalılıklar ve vadi içleri; serin yamaçlar.',
    altitude: '300 – 1.400 m',
    morphology: '3–8 m çalı-ağaç; kış sonunda yapraktan önce sarı çiçek şemsiyeleri; parlak kırmızı, ekşi zeytin biçimli meyve.',
    distribution: 'Orta-Güney Avrupa ve Batı Asya; İzmir’in dağ eteği köylerinde doğal ve bahçe bireyleri.',
    references: [REF_DAVIS, REF_GUNER],
  },
  'yabani-kiraz': {
    iucn: 'LC',
    habitat: 'Serin, nemli dağ ormanları ve vadi içleri; göknar-karaçam karışık kuşak.',
    altitude: '600 – 1.800 m',
    morphology: '15–25 m; kırmızımsı, enine soyulan parlak kabuk; beyaz salkım çiçekler; küçük tatlı-meşimsi meyveler (kuş kirazı).',
    distribution: 'Avrupa ve Batı Asya; Bozdağ ve Nif’in nemli kuşağında doğal.',
    references: [REF_DAVIS, REF_ANSIN],
  },
  'halep-cami': {
    iucn: 'LC',
    habitat: 'Kıyı kuşağı ağaçlandırmaları ve kent çevresi dikim sahaları; kurak kireçli yamaçlar.',
    altitude: '0 – 600 m',
    morphology: '10–20 m; açık gri-kahve kabuk; ince, açık yeşil iğneler (kızılçamdan daha kısa ve ince); uzun saplı kozalaklar.',
    distribution: 'Batı-Orta Akdeniz ana yayılış; İzmir’de eski ağaçlandırma ve kent parkı dikimleriyle temsil edilir.',
    references: [REF_KAYNACIK, REF_DAVIS, REF_GBIF],
  },
  saricam: {
    iucn: 'LC (Asgari Endişe)',
    habitat: 'Yüksek dağ kuşağı; soğuk ve karlı yamaçlar, 1.200 m üzeri yükseltiler.',
    altitude: '1.200 – 2.600 m',
    morphology: 'Sarımsı-turuncu ince pullu kabuk; 4–7 cm çiftli mavi-yeşil iğneler; küçük, sapsız kozalaklar.',
    distribution: 'Avrupa’dan Sibirya’ya geniş kuşak; Türkiye’de Kuzeydoğu Anadolu ve Karadeniz yüksekleri, Sarıkamış saf ormanları.',
    references: [REF_YALTIRIK, REF_ANSIN, REF_GUNER],
  },
  'dogu-kayini': {
    iucn: 'LC (Asgari Endişe)',
    habitat: 'Nemli-sisli dağ kuşağı; derin, kireçsiz topraklar; kuzey yamaçlar.',
    altitude: '400 – 1.900 m',
    morphology: 'Pürüzsüz gri gövde; basit, dişli kenarlı eliptik yapraklar; üçgen palamut (kayın kozası).',
    distribution: 'Kafkasya ve Kuzey Anadolu; Karadeniz dağlarının kurucu türü, Yenice’de anıt bireyler.',
    references: [REF_DAVIS, REF_YALTIRIK, REF_GBIF],
  },
  'dogu-ladini': {
    iucn: 'LC (Asgari Endişe)',
    habitat: 'Doğu Karadeniz’in yağışlı dağ yamaçları; serin, nemli mikroklimalar.',
    altitude: '600 – 2.300 m',
    morphology: 'Konik form, sarkık ince dallar; dört köşeli kısa iğneler; 6–10 cm sarkık silindirik kozalaklar.',
    distribution: 'Doğu Karadeniz dağları ve Batı Kafkasya; dar ama yoğun yayılış kuşağı.',
    references: [REF_YALTIRIK, REF_DAVIS, REF_TUBIVES],
  },
  'toros-sediri': {
    iucn: 'LC (toplum düzeyinde hassas popülasyonlar)',
    habitat: 'Torosların yüksek kuşağı; kireçtaşı yamaçlar, güneşli ve kurak sırtlar.',
    altitude: '800 – 2.200 m',
    morphology: 'Katlı-tablo taç; koyu yeşil kümeler halinde iğneler; dik duran, fıçı biçimli kozalaklar; bin yılı aşan anıt bireyler.',
    distribution: 'Doğu Akdeniz: Toroslar ana yayılış; Lübnan ve Suriye’de küçük kalıntılar.',
    references: [REF_DAVIS, REF_YALTIRIK, REF_GUNER],
  },
  'toros-goknari': {
    iucn: 'NT (Tehdide Yakın) — endemik',
    habitat: 'Torosların yüksek, kayalık yamaçları; karaçam ve sedirle karışık meşcereler.',
    altitude: '1.000 – 2.000 m',
    morphology: 'Konik taç; sert, ucu çentikli koyu yeşil yapraklar; 15–20 cm dik silindirik kozalaklar.',
    distribution: 'Türkiye endemikleri arasında: Toroslar (Antalya’dan Kahramanmaraş’a) ve Kuzey Suriye’de kalıntılar.',
    references: [REF_DAVIS, REF_GUNER, REF_YALTIRIK],
  },
  porsuk: {
    iucn: 'LC (popülasyonları seyrek)',
    habitat: 'Nemli, gölgeli orman içleri ve vadi tabanları; kireçli topraklar.',
    altitude: '100 – 1.600 m',
    morphology: 'Koyu yeşil, iki sıralı yassı iğne benzeri yapraklar; tohum kırmızı etli aril ile çevrili (zehirli).',
    distribution: 'Avrupa ve Batı Asya; Türkiye’de Karadeniz kuşağının nemli ormanları.',
    references: [REF_DAVIS, REF_ANSIN, REF_GBIF],
  },
  'kasnak-mesesi': {
    iucn: 'NT (Tehdide Yakın) — endemik',
    habitat: 'İç Anadolu step-orman geçiş kuşağı; 1.200–1.900 m kireçtaşı yamaçlar.',
    altitude: '1.200 – 1.900 m',
    morphology: 'Geniş, derin ve sivri loplu 15–25 cm yapraklar; iri palamut; kalın çatlaklı kabuk.',
    distribution: 'Türkiye endemiği: Kütahya–Konya–Eskişehir hattında dar yayılışlı topluluklar.',
    references: [REF_GUNER, REF_TUBIVES, REF_DAVIS],
  },
  'dag-akcaagaci': {
    iucn: 'LC (Asgari Endişe)',
    habitat: 'Serin ve nemli dağ ormanları; kayın-göknar meşcerelerinde karışık.',
    altitude: '400 – 2.000 m',
    morphology: 'Beş loplu, ters yüzü grimsi geniş yapraklar; ikili kanatlı (samara) meyveler; soyulan kabuk.',
    distribution: 'Orta ve Güney Avrupa’dan Kafkasya’ya; Türkiye’de Karadeniz dağ kuşağı.',
    references: [REF_DAVIS, REF_GBIF, REF_ANSIN],
  },
  'titrek-kavak': {
    iucn: 'LC (Asgari Endişe)',
    habitat: 'Yüksek platoların nemli yamaçları ve bozuk orman açıklıkları; öncü tür.',
    altitude: '1.200 – 2.400 m',
    morphology: 'Uzun yassı yaprak sapı (yaprağın “titremesinin” nedeni); yuvarlak, ince dişli yapraklar; klonal sürgünler.',
    distribution: 'Avrasya’nın serin kuşağı; Türkiye’de Doğu Anadolu yüksekleri.',
    references: [REF_DAVIS, REF_GUNER, REF_GBIF],
  },
  hus: {
    iucn: 'LC (Asgari Endişe)',
    habitat: 'Soğuk ve nemli yüksek vadiler; ışık seven öncü tür.',
    altitude: '1.400 – 2.600 m',
    morphology: 'Beyaz, kâğıt gibi soyulan kabuk; sarkık ince dallar; üçgen-elmas biçimli dişli yapraklar.',
    distribution: 'Avrupa ve Batı Sibirya; Türkiye’de Doğu Anadolu’nun en soğuk vadileri.',
    references: [REF_DAVIS, REF_GUNER, REF_TUBIVES],
  },
  kayisi: {
    iucn: 'DD (kültür formu yaygın)',
    habitat: 'Sıcak-kurak iç havza bahçeleri; kireçli, derin topraklar.',
    altitude: '600 – 1.600 m',
    morphology: 'Yuvarlak taç; kalp biçimli parlak yapraklar; erken açan beyaz-pembe çiçekler; etli çekirdekli meyve.',
    distribution: 'Orta Asya kökenli; Türkiye’de Malatya merkezli kültür havzası dünya üretiminin merkezi.',
    references: [REF_GUNER, REF_GBIF],
  },
  badem: {
    iucn: 'DD (kültür formu yaygın)',
    habitat: 'Kurak, kireçli ve taşlık yamaçlar; kıyı Akdeniz-Ege kuşağı.',
    altitude: '0 – 1.200 m',
    morphology: 'Mızraksı ince yapraklar; şubatta açan pembe-beyaz çiçekler; tüylü yeşil dış kabuklu meyve.',
    distribution: 'Güneybatı Asya kökenli; Türkiye’de Ege-Akdeniz ve Güneydoğu kültür kuşağı.',
    references: [REF_GUNER, REF_GBIF],
  },
  'yalanci-akasya': {
    iucn: 'LC (yerleşik kültür türü)',
    habitat: 'Kent parkları, yol kenarları ve bozuk sahalar; son derece uyumlu.',
    altitude: '0 – 1.600 m',
    morphology: 'Tüysü bileşik yapraklar; dikenli genç sürgünler; kokulu beyaz salkım çiçekler; bakla tipi meyve.',
    distribution: 'Kuzey Amerika kökenli; dünya genelinde doğallaşmış, Türkiye’de kent kuşağında yaygın.',
    references: [REF_GBIF, REF_GUNER],
  },
};

/* ------------------------------------------------------------------ */
/* Ek türler (doğal yayılış + kültür kuşağı tamamlayıcıları)          */
/* ------------------------------------------------------------------ */

export const EXTRA_SPECIES: Species[] = [
  {
    id: 'kizilagac',
    name: 'Kızılağaç',
    latin: 'Alnus glutinosa',
    family: 'Huşgiller (Betulaceae)',
    category: 'yaprakli',
    height: '15–25 m',
    bloom: 'Şubat – Mart (yapraktan önce)',
    desc: 'Suyu seven ağaçların başında gelir; köklerindeki simbiyotik bakterilerle havadaki azotu toprağa bağlar. Sulak alan restorasyonunda kilit türdür.',
    benefits: [
      'Azot bağlama: fakir ve bataklık toprakları doğal olarak gübreler',
      'Akarsu kıyılarında yatak ve istinat stabilitesi',
      'Sulak alan kuşları ve su samuru için habitat koridoru',
      'Suya dayanıklı odunu tarihî kazık ve köprü yapımında',
    ],
    regions: [
      { district: 'Menemen / Gediz Deltası', note: 'Deltanın tatlı su kanalları boyunca', coords: [38.59, 26.88] },
      { district: 'Bergama', note: 'Bakırçay kıyı koridoru', coords: [39.13, 27.2] },
      { district: 'Tire', note: 'Küçük Menderes boyunca gruplar', coords: [38.09, 27.73] },
    ],
  },
  {
    id: 'sacli-mese',
    name: 'Saçlı Meşe',
    latin: 'Quercus pubescens',
    family: 'Kayıngiller (Fagaceae)',
    category: 'yaprakli',
    height: '5–15 m',
    bloom: 'Nisan – Mayıs',
    desc: 'Kurak-ılıman yamaçların yaprak döken meşesi. Makiden ormana geçiş kuşağında öncü rol oynar; altı tüylü yaprakları buharlaşmayı azaltır.',
    benefits: [
      'Kurak yamaçlarda ormanlaşmanın öncü türü',
      'Palamutları domuz, karaca ve kuşlar için besin',
      'Maki-orman geçiş kuşağında tür zenginliğini artırır',
      'Kaliteli yakacak ve mangal kömürü',
    ],
    regions: [
      { district: 'Kemalpaşa / Nif', note: 'Kuzey yamaçlarda topluluklar', coords: [38.4, 27.4] },
      { district: 'Ödemiş', note: 'Bozdağ etek kuşağı', coords: [38.28, 28.0] },
      { district: 'Bergama', note: 'Madra Dağı etekleri', coords: [39.16, 27.25] },
    ],
  },
  {
    id: 'ova-akcaagaci',
    name: 'Ova Akçaağacı',
    latin: 'Acer campestre',
    family: 'Akçaağaçgiller (Sapindaceae)',
    category: 'yaprakli',
    height: '8–15 m',
    bloom: 'Mart – Nisan',
    desc: 'Anadolu’nun en yaygın yerli akçaağacıdır. Sonbaharda altın sarısına dönen loplu yapraklarıyla ova peyzajına renk katar.',
    benefits: [
      'Yoğun taç yapısıyla küçük kuşlar için yuva alanı',
      'Sert ve düzgün dokulu odun: torna ve alet sapı',
      'Erken bahar polen kaynağı',
      'Çit ve rüzgar perdesi dizilişlerinde dayanıklı',
    ],
    regions: [
      { district: 'Torbalı', note: 'Ova içi dere ve çit hatları', coords: [38.18, 27.37] },
      { district: 'Menemen', note: 'Gediz ovası nemli kesimler', coords: [38.61, 27.08] },
    ],
  },
  {
    id: 'kizilcik',
    name: 'Kızılcık',
    latin: 'Cornus mas',
    family: 'Kızılcıkgiller (Cornaceae)',
    category: 'meyve',
    height: '3–8 m',
    bloom: 'Şubat – Mart (yapraktan önce)',
    desc: 'Yılın en erken çiçek açan odunsu türlerinden; karlar erimeden sarı çiçeklerini açar. Ekşi meyveleri geleneksel şerbet ve marmelat yapımında kullanılır.',
    benefits: [
      'Kış sonu açan çiçekleriyle arılar için kritik ilk nektar',
      'C vitamini yönünden zengin yenilebilir meyve',
      'Yoğun çalı formu kuşlar için korunaklı barınak',
      'Son derece sert odunu geleneksel baston ve alet yapımında',
    ],
    regions: [
      { district: 'Kiraz', note: 'Dağ eteği köy bahçeleri', coords: [38.24, 28.19] },
      { district: 'Ödemiş / Bozdağ etek', note: 'Vadi içi çalılıklar', coords: [38.3, 28.05] },
      { district: 'Bayındır', note: 'Yamaç köyleri çevresi', coords: [38.23, 27.67] },
    ],
  },
  {
    id: 'yabani-kiraz',
    name: 'Yabani Kiraz (Kuş Kirazı)',
    latin: 'Prunus avium',
    family: 'Gülgiller (Rosaceae)',
    category: 'yaprakli',
    height: '15–25 m',
    bloom: 'Nisan',
    desc: 'Kültür kirazlarının yaban atasıdır. Bozdağ’ın nemli vadilerinde beyaz çiçek örtüsüyle baharı karşılar; meyveleri kuşların paylaşım şölenidir.',
    benefits: [
      'Kültür kirazı çeşitleri için gen kaynağı ve aşı anacı',
      'Kuş tohum dağılımıyla orman yenilenmesine katkı',
      'Değerli mobilya ve kaplama kerestesi',
      'Bahar çiçeklenmesiyle polinatör desteği',
    ],
    regions: [
      { district: 'Ödemiş / Bozdağ', note: 'Nemli vadi içleri, göknar kuşağı altı', coords: [38.35, 28.07] },
      { district: 'Kemalpaşa / Nif', note: 'Kuzey yamaç vadileri', coords: [38.39, 27.39] },
    ],
  },
  {
    id: 'halep-cami',
    name: 'Halep Çamı',
    latin: 'Pinus halepensis',
    family: 'Çamgiller (Pinaceae)',
    category: 'ibreli',
    height: '10–20 m',
    bloom: 'Mart – Nisan',
    tag: 'Ağaçlandırma türü',
    desc: 'Batı Akdeniz’in kuraklık şampiyonu; İzmir’de kent çevresi ağaçlandırma sahalarında ve parklarda karşımıza çıkar. İnce, açık yeşil iğneleriyle kızılçamdan ayırt edilir.',
    benefits: [
      'Aşırı kurak ve fakir sahalarda başarılı ağaçlandırma',
      'Kentsel yeşil kuşakta hızlı örtü oluşturma',
      'Toz ve rüzgar tutucu bariyer',
      'Reçine ve odun değeri',
    ],
    regions: [
      { district: 'Bornova', note: 'Kent çevresi ağaçlandırma sahaları', coords: [38.48, 27.25] },
      { district: 'Buca', note: 'Kaynaklar yolu boyunca dikimler', coords: [38.35, 27.23] },
      { district: 'Gaziemir', note: 'Sarnıç çevresi ağaçlandırma', coords: [38.32, 27.16] },
    ],
  },
];

/* ------------------------------------------------------------------ */
/* Türkiye geneli türler (ülke çapında yayılış kuşağı)                */
/* ------------------------------------------------------------------ */

export const TURKIYE_SPECIES: Species[] = [
  {
    id: 'saricam',
    name: 'Sarıçam',
    latin: 'Pinus sylvestris var. hamata',
    family: 'Çamgiller (Pinaceae)',
    category: 'ibreli',
    height: '25–40 m',
    bloom: 'Nisan – Mayıs',
    tag: 'Sarıkamış ormanları',
    desc: 'Soğuğun ağacı sarıçam, Türkiye’de yüksek dağ kuşağının hakim türüdür. Sarımsı-turuncu kabuğuyla kolayca tanınır; Kars Sarıkamış’taki saf ormanları ülkenin en etkileyici iğne yapraklı örtülerindendir.',
    benefits: [
      'Yüksek rakımlı havzalarda kar birikimini düzenler, su rejimini korur',
      'Düzgün ve reçinesi az odunu yapı sektörünün gözdesidir',
      'Aşırı soğuk iklimlerde ağaçlandırmanın birincil türü',
      'Kar altında kışlayan yaban hayvanlarına sığınak sağlar',
    ],
    regions: [
      { district: 'Kars / Sarıkamış', note: 'Türkiye’nin en görkemli saf sarıçam ormanı', coords: [40.33, 42.58] },
      { district: 'Bolu / Aladağ', note: 'Yüksek kesim meşcereleri', coords: [40.6, 31.9] },
      { district: 'Kastamonu / Küre Dağları', note: 'Karışık dağ ormanları', coords: [41.8, 33.7] },
      { district: 'Artvin', note: 'Doğu Karadeniz yüksekleri', coords: [41.18, 41.82] },
    ],
  },
  {
    id: 'dogu-kayini',
    name: 'Doğu Kayını',
    latin: 'Fagus orientalis',
    family: 'Kayıngiller (Fagaceae)',
    category: 'yaprakli',
    height: '30–40 m',
    bloom: 'Nisan – Mayıs',
    tag: 'Karadeniz’in anıt ağacı',
    desc: 'Karadeniz dağlarının sisli yamaçlarını kaplayan doğu kayını, pürüzsüz gri gövdesi ve sonbaharda altın sarısına dönen yapraklarıyla tanınır. Yenice Ormanları’ndaki dev bireyleri anıt ağaç statüsündedir.',
    benefits: [
      'Sisli dağ ormanlarında su toplama ve toprak koruma',
      'Palamutları sincaptan ayıya zengin yaban hayatı besini',
      'Değerli mobilya ve kaplama kerestesi',
      'Yüksek karbon depolayan uzun ömürlü meşcereler',
    ],
    regions: [
      { district: 'Zonguldak / Yenice', note: 'Anıt kayınlarıyla ünlü orman dokusu', coords: [41.2, 32.3] },
      { district: 'Bolu / Yedigöller', note: 'Kayın-göknar karışık meşcereler', coords: [40.95, 31.75] },
      { district: 'Rize / Fırtına Vadisi', note: 'Sis kuşağındaki yoğun yayılış', coords: [41.05, 41.05] },
    ],
  },
  {
    id: 'dogu-ladini',
    name: 'Doğu Ladini',
    latin: 'Picea orientalis',
    family: 'Çamgiller (Pinaceae)',
    category: 'ibreli',
    height: '30–45 m',
    bloom: 'Nisan – Mayıs',
    desc: 'Doğu Karadeniz’in nemli dağlarında 45 metreye ulaşan doğu ladini, sarkık dalları ve küçük kozalaklarıyla bilinir. Çamburnu’daki koruma ormanı, toprak kaymasını durduran canlı bir mühendislik örneğidir.',
    benefits: [
      'Dik ve nemli yamaçlarda erozyonu durduran sık kök ağı',
      'Kaliteli rezonans ağacı: müzik enstrümanı yapımı',
      'Yoğun tacıyla sis suyunu toplar, kaynak besler',
      'Doğu Karadeniz endemik kuşlarına yaşam alanı',
    ],
    regions: [
      { district: 'Trabzon / Maçka', note: 'Altındere vadisi yamaçları', coords: [40.8, 39.6] },
      { district: 'Rize', note: 'Kaçkar eteklerindeki kuşak', coords: [41.0, 40.9] },
      { district: 'Artvin / Şavşat', note: 'Saf ve karışık meşcereler', coords: [41.25, 42.35] },
    ],
  },
  {
    id: 'toros-sediri',
    name: 'Toros Sediri',
    latin: 'Cedrus libani',
    family: 'Çamgiller (Pinaceae)',
    category: 'ibreli',
    height: '25–40 m',
    bloom: 'Ekim – Kasım',
    tag: 'Bin yıllık anıtlar',
    desc: 'Antik çağ gemilerinin ve sarayların efsanevi kerestesi; Toroslar’da 1.000 yaşını aşan bireyleri hâlâ ayaktadır. Katlı, tablo gibi yayılan tacıyla başka hiçbir iğne yapraklıyla karışmaz.',
    benefits: [
      'Dayanıklı ve kokulu odunu yüzyıllarca çürümez',
      'Torosların kurak yüksek kuşağında örtü kuran az bulunur tür',
      'Anıt bireyleri kültürel miras ve turizm değeri',
      'Uzun ömürlü karbon deposu',
    ],
    regions: [
      { district: 'Isparta / Kovada Gölü', note: 'Göl çevresindeki sedir meşcereleri', coords: [37.65, 30.9] },
      { district: 'Antalya / Elmalı', note: 'Çığlıkara sedir ormanı', coords: [36.75, 29.95] },
      { district: 'Mersin / Anamur', note: 'Batı Toros yayılışı', coords: [36.25, 32.8] },
    ],
  },
  {
    id: 'toros-goknari',
    name: 'Toros Göknarı',
    latin: 'Abies cilicica',
    family: 'Çamgiller (Pinaceae)',
    category: 'ibreli',
    height: '25–35 m',
    bloom: 'Nisan – Mayıs',
    tag: 'Endemik',
    desc: 'Yalnızca Toroslar ve yakın çevresinde yaşayan endemik göknar; koyu yeşil sert yaprakları ve dik kozalaklarıyla kayalık yüksek yamaçların türüdür. Dünyada başka doğal yayılışı yoktur.',
    benefits: [
      'Türkiye’ye özgü endemik gen kaynağı',
      'Kayalık yamaçlarda toprak oluşumunu başlatır',
      'Sedir ve karaçamla karışık meşcereler kurar',
      'Dar yayılışı nedeniyle koruma önceliği yüksek',
    ],
    regions: [
      { district: 'Isparta / Eğirdir', note: 'Dedegöl Dağı yamaçları', coords: [37.9, 30.8] },
      { district: 'Antalya / Akseki', note: 'Gidengelmez Dağları', coords: [37.05, 31.8] },
      { district: 'Kahramanmaraş', note: 'Doğu Toros kesimi', coords: [37.6, 36.9] },
    ],
  },
  {
    id: 'porsuk',
    name: 'Porsuk',
    latin: 'Taxus baccata',
    family: 'Porsukgiller (Taxaceae)',
    category: 'ibreli',
    height: '10–20 m',
    bloom: 'Mart – Nisan',
    tag: 'Zehirlidir',
    desc: 'Avrupa’nın en uzun ömürlü ağaçlarından; Karadeniz’in nemli gölgelik vadilerinde yüzyıllarca yaşar. Kırmızı etli “meyve” görünümlü yapısı çekici olsa da yaprak ve tohumları zehirlidir.',
    benefits: [
      'Binlerce yıl yaşayabilen istisnai uzun ömür',
      'Kabuğundan elde edilen taksol kanser ilacı hammaddesi',
      'Gölgeli orman altı ekosisteminin kurucusu',
      'Yoğun, esnek odunu tarihte yay yapımında kullanıldı',
    ],
    regions: [
      { district: 'Zonguldak', note: 'Nemli kayın ormanı alt kuşağı', coords: [41.3, 31.9] },
      { district: 'Trabzon', note: 'Gölgeli vadi tabanları', coords: [41.0, 39.7] },
      { district: 'Rize / Çamlıhemşin', note: 'Yağmur ormanı relict dokular', coords: [41.05, 41.0] },
    ],
  },
  {
    id: 'kasnak-mesesi',
    name: 'Kasnak Meşesi',
    latin: 'Quercus vulcanica',
    family: 'Kayıngiller (Fagaceae)',
    category: 'yaprakli',
    height: '20–30 m',
    bloom: 'Nisan – Mayıs',
    tag: 'Endemik',
    desc: 'İç Anadolu’ya özgü endemik meşe; geniş, derin loplu yapraklarıyla diğer meşelerden hemen ayrılır. Kütahya-Konya hattındaki toplulukları dünyadaki tek doğal yayılışıdır.',
    benefits: [
      'Türkiye’ye özgü endemik tür; bilimsel önemi yüksek',
      'Step-orman geçiş kuşağında biyoçeşitlilik adası',
      'Palamutları kuşlar ve kemirgenler için besin',
      'Kuraklığa dayanıklı meşe genotipi',
    ],
    regions: [
      { district: 'Kütahya', note: 'Murat Dağı çevresi saf topluluklar', coords: [39.4, 29.9] },
      { district: 'Konya / Akşehir', note: 'Sultan Dağları yayılışı', coords: [38.35, 31.4] },
      { district: 'Eskişehir', note: 'Türkmen Dağı meşcereleri', coords: [39.75, 30.5] },
    ],
  },
  {
    id: 'dag-akcaagaci',
    name: 'Dağ Akçaağacı',
    latin: 'Acer pseudoplatanus',
    family: 'Akçaağaçgiller (Sapindaceae)',
    category: 'yaprakli',
    height: '25–35 m',
    bloom: 'Nisan – Mayıs',
    desc: 'Çınar yapraklı akçaağaç da denir; beş loplu geniş yaprakları ve çiftli kanatçıklı meyveleriyle tanınır. Karadeniz’in serin dağ ormanlarında kayın ve göknarla karışır.',
    benefits: [
      'Rüzgarla yayılan kanatlı tohumlarıyla hızlı doğal gençleşme',
      'Gölgeye dayanıklı: orman alt katmanını zenginleştirir',
      'Açık renkli odunu mobilya ve torna işlerinde değerli',
      'Kent parklarında güçlü gölge ağacı',
    ],
    regions: [
      { district: 'Rize', note: 'Karışık yapraklı kuşak', coords: [41.0, 40.9] },
      { district: 'Giresun', note: 'Dağ kuşağı meşcereleri', coords: [40.65, 38.5] },
      { district: 'Bolu', note: 'Yedigöller çevresi karışık orman', coords: [40.7, 31.6] },
    ],
  },
  {
    id: 'titrek-kavak',
    name: 'Titrek Kavak',
    latin: 'Populus tremula',
    family: 'Söğütgiller (Salicaceae)',
    category: 'yaprakli',
    height: '15–25 m',
    bloom: 'Mart – Nisan',
    desc: 'En hafif esintiyle bile titreyen uzun saplı yapraklarıyla bilinir. Doğu Anadolu’nun yüksek platolarında sonbaharda altın sarısı koloniler oluşturur; kök sürgünleriyle klonal yayılır.',
    benefits: [
      'Bozkır-orman geçişinde hızlı öncü tür',
      'Kök sürgünleriyle tahrip olmuş araziyi tutar',
      'Kuzukulağı renginde sonbahar dokusu; peyzaj değeri',
      'Kelebek tırtılları için önemli besin bitkisi',
    ],
    regions: [
      { district: 'Kars', note: 'Sarıkamış çevresi klonal gruplar', coords: [40.3, 42.7] },
      { district: 'Erzurum', note: 'Vadi içi ve nemli yamaçlar', coords: [39.9, 41.3] },
      { district: 'Sivas', note: 'Yüksek plato orman açıklıkları', coords: [39.75, 37.0] },
    ],
  },
  {
    id: 'hus',
    name: 'Huş',
    latin: 'Betula pendula',
    family: 'Huşgiller (Betulaceae)',
    category: 'yaprakli',
    height: '15–25 m',
    bloom: 'Nisan – Mayıs',
    desc: 'Kâğıt gibi soyulan beyaz kabuğuyla tanınan huş, Doğu Anadolu’nun soğuk ve yüksek vadilerinde ince, zarif gruplar kurar. Işık seven bir öncü türdür.',
    benefits: [
      'Yanmış ve tahrip olmuş sahalarda ilk yerleşen türlerden',
      'Soğuk iklim peyzajında estetik değer',
      'Öz suyu ve yaprakları geleneksel kullanıma sahip',
      'Hafif ve işlenebilir odun',
    ],
    regions: [
      { district: 'Ağrı', note: 'Yüksek rakımlı vadi dokuları', coords: [39.75, 43.05] },
      { district: 'Kars', note: 'Çoruh-Sarıkamış geçiş kuşağı', coords: [40.3, 42.9] },
      { district: 'Ardahan', note: 'Soğuk plato orman kenarları', coords: [41.1, 42.7] },
    ],
  },
  {
    id: 'kayisi',
    name: 'Kayısı',
    latin: 'Prunus armeniaca',
    family: 'Gülgiller (Rosaceae)',
    category: 'meyve',
    height: '5–9 m',
    bloom: 'Mart (erken çiçek)',
    tag: 'Malatya',
    desc: 'Malatya, dünya kayısı üretiminin kalbidir; baharın ilk açan çiçekleriyle vadileri beyaza boyar. Yabani formları Orta Asya kökenlidir, Anadolu’da yüzyıllardır kültüre alınmıştır.',
    benefits: [
      'Malatya havzasında on binlerce ailenin geçim kaynağı',
      'Erken çiçekleriyle arılar için ilk nektar kaynağı',
      'Kuru ve taze meyve ihracatında dünya liderliği',
      'Tohumu (kayısı çekirdeği) ek katma değer',
    ],
    regions: [
      { district: 'Malatya', note: 'Dünya kayısı başkenti; ova boyunca bahçeler', coords: [38.35, 38.3] },
      { district: 'Elazığ', note: 'Fırat havzası bahçeleri', coords: [38.65, 39.2] },
      { district: 'Erzincan', note: 'Üzümlü çevresi kayısı bahçeleri', coords: [39.75, 39.5] },
    ],
  },
  {
    id: 'badem',
    name: 'Badem',
    latin: 'Prunus amygdalus',
    family: 'Gülgiller (Rosaceae)',
    category: 'meyve',
    height: '4–8 m',
    bloom: 'Şubat – Mart',
    tag: 'Datça',
    desc: 'Şubatta pembe-beyaz çiçeklerle uyanan badem, Datça yarımadasının simgesidir. Kuraklığa dayanıklı, kireçli ve taşlık toprakların türüdür.',
    benefits: [
      'Kurak tarımın kilit meyvesi; sulama istemez',
      'Datça ekonomisine turizm ve gıda değeri',
      'Kış sonu çiçekleriyle arıcılığı besler',
      'Eğimli, taşlık arazileri değerlendirir',
    ],
    regions: [
      { district: 'Muğla / Datça', note: 'Yarımadanın simgesi; şubat badem çiçeği', coords: [36.75, 27.65] },
      { district: 'Aydın', note: 'Büyük Menderes havzası bahçeleri', coords: [37.85, 27.85] },
      { district: 'Mardin', note: 'Mezopotamya badem kuşağı', coords: [37.3, 40.7] },
    ],
  },
  {
    id: 'yalanci-akasya',
    name: 'Yalancı Akasya',
    latin: 'Robinia pseudoacacia',
    family: 'Baklagiller (Fabaceae)',
    category: 'yaprakli',
    height: '15–25 m',
    bloom: 'Mayıs – Haziran',
    tag: 'Yerleşik kültür türü',
    desc: 'Kuzey Amerika kökenli; kokulu salkım çiçekleriyle kentlerin en çok dikilen ağacı oldu. Azot bağlayan kökleriyle fakir topraklarda bile hızla büyür, bu yüzden kontrolsüz yayılmasına dikkat edilir.',
    benefits: [
      'Azot bağlama: bozuk kentsel toprakları iyileştirir',
      'Nektar zengini çiçekleriyle değerli akasya balı',
      'Çürümeye çok dayanıklı kazık ve direk odunu',
      'Hızlı büyüyerek kentte erken gölge sağlar',
    ],
    regions: [
      { district: 'İstanbul', note: 'Kent parkları ve yol ağaçlandırması', coords: [41.0, 28.97] },
      { district: 'Ankara', note: 'Kent çevresi erozyon sahaları', coords: [39.93, 32.86] },
      { district: 'Bornova', note: 'İzmir’de kampüs ve park dikimleri', coords: [38.47, 27.21] },
    ],
  },
];

export const ALL_SPECIES: Species[] = [...SPECIES, ...EXTRA_SPECIES, ...TURKIYE_SPECIES];

export function getSpeciesById(id: string): Species | undefined {
  return ALL_SPECIES.find((s) => s.id === id);
}

export function getAcademic(id: string): Academic | undefined {
  return ACADEMIC[id];
}

/* İlçe listesi (filtreleme için) */
export const DISTRICTS: string[] = Array.from(
  new Set(
    ALL_SPECIES.flatMap((s) =>
      s.regions.map((r) => r.district.split(' / ')[0].trim()),
    ),
  ),
).sort((a, b) => a.localeCompare(b, 'tr'));

/* Harita araması için gezilebilir yer dizini (ilçe/il merkezleri + sıcak noktalar) */
export interface Place {
  name: string;
  coords: [number, number];
  kind: 'district' | 'hotspot';
}

export const PLACES: Place[] = (() => {
  const seen = new Map<string, [number, number]>();
  for (const s of ALL_SPECIES)
    for (const r of s.regions) {
      const key = r.district.split(' / ')[0].trim();
      if (!seen.has(key)) seen.set(key, r.coords);
    }
  const places: Place[] = Array.from(seen, ([name, coords]) => ({
    name,
    coords,
    kind: 'district' as const,
  }));
  for (const h of HOTSPOTS)
    places.push({ name: h.name, coords: h.coords, kind: 'hotspot' });
  return places;
})();
