/* Türkiye geneli ek türler. Konumlar il/bölge merkezlerine göre işaretlidir. */
import type { Species, Category } from './species';

const P: Record<string, [number, number]> = {
  Adana: [37.0, 35.32], Adıyaman: [37.76, 38.28], Afyon: [38.76, 30.54], Ağrı: [39.72, 43.05],
  Aksaray: [38.37, 34.03], Amasya: [40.65, 35.83], Ankara: [39.93, 32.86], Antalya: [36.89, 30.71],
  Ardahan: [41.11, 42.7], Artvin: [41.18, 41.82], Aydın: [37.85, 27.85], Balıkesir: [39.65, 27.89],
  Bartın: [41.63, 32.34], Batman: [37.88, 41.13], Bayburt: [40.26, 40.23], Bilecik: [40.14, 29.98],
  Bingöl: [38.88, 40.5], Bitlis: [38.4, 42.11], Bolu: [40.73, 31.61], Burdur: [37.72, 30.29],
  Bursa: [40.19, 29.06], Çanakkale: [40.15, 26.41], Çankırı: [40.6, 33.62], Çorum: [40.55, 34.95],
  Denizli: [37.78, 29.09], Diyarbakır: [37.91, 40.24], Düzce: [40.84, 31.16], Edirne: [41.68, 26.56],
  Elazığ: [38.67, 39.22], Erzincan: [39.75, 39.5], Erzurum: [39.9, 41.27], Eskişehir: [39.78, 30.52],
  Gaziantep: [37.07, 37.38], Giresun: [40.91, 38.39], Gümüşhane: [40.46, 39.48], Hakkari: [37.58, 43.74],
  Hatay: [36.4, 36.35], Iğdır: [39.92, 44.04], Isparta: [37.76, 30.55], İstanbul: [41.01, 28.97],
  İzmir: [38.42, 27.13], Kahramanmaraş: [37.58, 36.94], Karabük: [41.2, 32.62], Karaman: [37.18, 33.22],
  Kars: [40.6, 43.1], Kastamonu: [41.38, 33.78], Kayseri: [38.72, 35.49], Kırıkkale: [39.85, 33.51],
  Kırklareli: [41.74, 27.22], Kırşehir: [39.15, 34.17], Kilis: [36.72, 37.12], Kocaeli: [40.77, 29.94],
  Konya: [37.87, 32.48], Kütahya: [39.42, 29.98], Malatya: [38.35, 38.31], Manisa: [38.61, 27.43],
  Mardin: [37.31, 40.74], Mersin: [36.8, 34.64], Muğla: [37.22, 28.36], Muş: [38.74, 41.49],
  Nevşehir: [38.62, 34.71], Niğde: [37.97, 34.68], Ordu: [40.98, 37.88], Osmaniye: [37.07, 36.25],
  Rize: [41.02, 40.52], Sakarya: [40.69, 30.4], Samsun: [41.29, 36.33], Siirt: [37.93, 41.94],
  Sinop: [42.03, 35.15], Sivas: [39.75, 37.02], Şanlıurfa: [37.16, 38.79], Şırnak: [37.52, 42.46],
  Tekirdağ: [40.98, 27.51], Tokat: [40.31, 36.55], Trabzon: [41.0, 39.72], Tunceli: [39.11, 39.55],
  Uşak: [38.68, 29.41], Van: [38.5, 43.38], Yalova: [40.65, 29.27], Yozgat: [39.82, 34.8],
  Zonguldak: [41.46, 31.8], Datça: [36.75, 27.68], Marmaris: [36.85, 28.27], Köyceğiz: [36.97, 28.68],
  Fethiye: [36.62, 29.12], Kazdağları: [39.7, 26.85], Uludağ: [40.07, 29.13], 'Ilgaz Dağı': [41.07, 33.78],
  'Köprülü Kanyon': [37.2, 31.2], 'Kaçkar Dağları': [40.84, 41.15], 'Belgrad Ormanı': [41.18, 28.98],
  Yedigöller: [40.9, 31.75], Abant: [40.6, 31.28], Sarıkamış: [40.33, 42.58], Kızılcahamam: [40.47, 32.65],
  Alanya: [36.54, 32.0], Anamur: [36.08, 32.84], Silifke: [36.38, 33.93], Fatsa: [41.03, 37.5],
  Hopa: [41.4, 41.42], Bodrum: [37.04, 27.43], Samandağ: [36.08, 35.97], Ayvalık: [39.31, 26.69],
  Edremit: [39.6, 27.02], Sürmene: [40.91, 40.12], Çarşamba: [41.2, 36.72], Akçakoca: [41.09, 31.12],
  Ödemiş: [38.23, 27.97], Bozdağ: [38.36, 28.09], Nizip: [37.01, 37.79], 'Toros Dağları': [37.1, 34.2],
  Bergama: [39.12, 27.18], Çeşme: [38.32, 26.3], Urla: [38.32, 26.76], Gökova: [37.03, 28.3],
  Kemer: [36.6, 30.56], Göksu: [36.4, 33.7], Tarsus: [36.92, 34.89], Erdemli: [36.6, 34.31],
  Kozan: [37.45, 35.82], Kumluca: [36.37, 30.29], Finike: [36.3, 30.15], Iğneada: [41.88, 28.0],
  Sapanca: [40.69, 30.27], Tosya: [41.01, 34.04], Taşköprü: [41.51, 34.21], Bafra: [41.57, 35.91],
};

function s(
  id: string, name: string, latin: string, family: string, category: Category,
  height: string, bloom: string, desc: string, benefits: string[],
  regions: [string, string][], tag?: string,
): Species {
  return {
    id, name, latin, family, category, height, bloom, desc, benefits, tag,
    regions: regions.map(([district, note]) => {
      const coords = P[district];
      if (!coords) throw new Error(`Bilinmeyen konum: ${district}`);
      return { district, note, coords };
    }),
  };
}

const PIN = 'Çamgiller (Pinaceae)', FAG = 'Kayıngiller (Fagaceae)', ROS = 'Gülgiller (Rosaceae)',
  CUP = 'Servigiller (Cupressaceae)', SAL = 'Söğütgiller (Salicaceae)', BET = 'Hüşgiller (Betulaceae)',
  ACE = 'Akçaağaçgiller (Sapindaceae)', RUT = 'Sedefotugiller (Rutaceae)', OLE = 'Zeytingiller (Oleaceae)',
  FAB = 'Baklagiller (Fabaceae)', ANA = 'Sumakgiller (Anacardiaceae)', MYR = 'Mersingiller (Myrtaceae)';

export const MORE_SPECIES: Species[] = [
  /* ---- İbreliler ---- */
  s('kafkas-goknari', 'Kafkas Göknarı', 'Abies nordmanniana', PIN, 'ibreli', '30–50 m', 'Mayıs',
    'Doğu Karadeniz’in nemli dağ ormanlarında ladin ve kayınla karışık yaşayan, Noel ağacı olarak da ünlü görkemli göknardır. Gümüşi alt yüzlü yaprakları ve dik kozalaklarıyla tanınır.',
    ['Kaliteli kereste ve selüloz ham maddesi', 'Dikili Noel ağacı üretimiyle ekonomik değer', 'Yağışlı yamaçlarda toprak ve su koruması'],
    [['Artvin', 'Karagöl–Sahara çevresi göknar-ladin ormanları'], ['Rize', 'Kaçkar etekleri yüksek kesimleri'], ['Giresun', 'Eğribel ve Karagöl çevresi']]),
  s('uludag-goknari', 'Uludağ Göknarı', 'Abies bornmuelleriana', PIN, 'ibreli', '25–40 m', 'Mayıs',
    'Batı Karadeniz ve Marmara dağlarının endemik göknarıdır. Uludağ’ın 1.000–2.000 m arasındaki kuşağında geniş ormanlar kurar.',
    ['Uludağ’ın su havzasını koruyan ana orman örtüsü', 'Yapı ve mobilya kerestesi', 'Kış turizmi peyzajının parçası'],
    [['Uludağ', 'Ulu orman kuşağı; saf göknar meşcereleri'], ['Bolu', 'Köroğlu ve Abant çevresi'], ['Kastamonu', 'Ilgaz ve Küre dağları']], 'Endemik'),
  s('kazdagi-goknari', 'Kazdağı Göknarı', 'Abies equi-trojani', PIN, 'ibreli', '20–30 m', 'Mayıs',
    'Yalnızca Kazdağları ve çevresinde doğal olarak yetişen, Anadolu’nun nadir endemik göknarıdır. Troya atının mitolojik ağacı olarak da anılır.',
    ['Kazdağları su havzası ve oksijen deposu', 'Genetik çeşitlilik açısından koruma önceliği', 'Ekoturizmin simge türü'],
    [['Kazdağları', 'Sarıkız zirvesi çevresi saf göknar ormanları'], ['Edremit', 'Zeytinli ve Güre yamaçları'], ['Balıkesir', 'Kazdağı Milli Parkı']], 'Endemik'),
  s('sabin-ardici', 'Sabin Ardıcı', 'Juniperus sabina', CUP, 'ibreli', '1–4 m', 'Nisan – Mayıs',
    'Yer örtücü ya da küçük ağaç formundaki bu ardıç, yüksek dağ kuşağında yamaçlara yayılarak yaşar. Mavi-siyah meyveleri ve pul yaprakları vardır.',
    ['Yüksek yamaçlarda erozyon koruması', 'Kış beslenmesinde yaban hayatına sığınak', 'Peyzajda yer örtücü olarak kullanılır'],
    [['Sarıkamış', 'Kuzeydoğu Anadolu yüksek dağları'], ['Erzurum', 'Palandöken yamaçları'], ['Ağrı', 'Yüksek dağ otlakları']]),
  s('kokulu-ardic', 'Kokulu Ardıç', 'Juniperus foetidissima', CUP, 'ibreli', '10–20 m', 'Mart – Nisan',
    'Ezildiğinde keskin kokan yaprakları nedeniyle bu adı alan Doğu Akdeniz ardıcıdır. Toros ve Güneydoğu Anadolu dağlarında doğal ormanlar kurar.',
    ['Çürümeye çok dayanıklı odun', 'Kurak yamaçlarda toprak bağlama', 'Kültürel yapılarda geleneksel direk malzemesi'],
    [['Antalya', 'Kuzey Toros yamaçlarında ardıç ormanları'], ['Konya', 'Güney yamaçlarda seyrek ardıçlık'], ['Burdur', 'Kuyucak çevresi']]),
  s('anadolu-karacami', 'Anadolu Karaçamı', 'Pinus nigra subsp. pallasiana', PIN, 'ibreli', '20–35 m', 'Mayıs',
    'Orta Anadolu dağlarının ve Marmara-Ege iç kesimlerinin en yaygın çamı. Soğuğa ve kuraklığa dayanıklı, gri-siyah kabuklu ve uzun iğneli bir dağ ağacıdır.',
    ['Türkiye’nin önemli kereste kaynaklarından', 'Dağ ağaçlandırmalarında en başarılı tür', 'Reçine ve odun kömürü üretimi'],
    [['Bolu', 'Köroğlu ve Gölcük çevresi karaçam ormanları'], ['Kütahya', 'Domaniç Dağları'], ['Karabük', 'Safranbolu Yenice ormanları']]),
  s('macar-mesesi', 'Macar Meşesi', 'Quercus frainetto', FAG, 'yaprakli', '20–30 m', 'Nisan – Mayıs',
    'Trakya ve Marmara’nın büyük yapraklı, derin loblu görkemli meşesidir. Balkan meşe ormanlarının Anadolu’daki batı uzantısını oluşturur.',
    ['Yüksek kaliteli meşe kerestesi', 'Kuşlar ve böcekler için zengin yaşam alanı', 'Trakya’nın orman örtüsünün omurgası'],
    [['Kırklareli', 'Istranca ormanları'], ['Tekirdağ', 'Ganos Dağı yamaçları'], ['Edirne', 'Kıyıköy’e kadar uzanan sahalar']]),
  s('sapsiz-mese', 'Sapsız Meşe', 'Quercus petraea', FAG, 'yaprakli', '20–35 m', 'Nisan – Mayıs',
    'Sapsız palamutlarıyla tanınan, yüksek kaliteli odun veren orman meşesidir. Karadeniz ve Marmara’nın nemli ormanlarında yaygındır.',
    ['Parke, fıçı ve mobilya sanayisi için üstün odun', 'Yaban hayatı için palamut kaynağı', 'Orman karbon depolama kapasitesi yüksek'],
    [['Kırklareli', 'Istranca ormanları'], ['Sinop', 'Kuzey Anadolu orman kuşağı'], ['Bolu', 'Yenice ve Abant çevresi']]),
  s('sapli-mese', 'Saplı Meşe', 'Quercus robur', FAG, 'yaprakli', '25–40 m', 'Nisan – Mayıs',
    'Uzun saplı palamutları olan, asırlarca yaşayan meşedir. Taşkın ovaları ve nemli vadi tabanlarında doğal olarak yetişir.',
    ['Mobilya ve ahşap sanayisi', 'Kuş ve memeli türleri için barınak', 'Tarihî anıt ağaç örnekleri'],
    [['Kırklareli', 'Trakya nemli ormanları'], ['Samsun', 'Kuzey Anadolu kıyı ormanları'], ['Sakarya', 'Karasu çevresi']]),
  s('tuylu-mese', 'Tüylü Meşe', 'Quercus pubescens', FAG, 'yaprakli', '8–20 m', 'Nisan – Mayıs',
    'Kış boyunca kuru yapraklarını tutabilen, kurak ve kireçli yamaçların meşesidir. Yaprak altları tüylüdür.',
    ['Kurak kireçli toprakların ağaçlandırılması', 'Balık ve karaca gibi yaban hayatına besin', 'Yakacak ve odun kömürü'],
    [['Kütahya', 'İç Batı Anadolu kurak ormanları'], ['Çankırı', 'Ilgaz’ın güney yamaçları'], ['Tokat', 'Yeşilırmak vadisi']]),
  s('kafkas-mesesi', 'Kafkas Meşesi', 'Quercus macranthera', FAG, 'yaprakli', '15–25 m', 'Mayıs',
    'Doğu Anadolu ve Kafkaslar’ın yüksek dağ meşesidir. Büyük, derin loblu yapraklarıyla soğuk bölge ormanlarının karakterini belirler.',
    ['Soğuk iklimlerde orman örtüsünün yapı taşı', 'Kaliteli yakacak ve yapı kerestesi', 'Dağ ekosistemi için palamut kaynağı'],
    [['Erzurum', 'Palandöken ve Aşkale çevresi'], ['Kars', 'Sarıkamış kenarları'], ['Artvin', 'Yusufeli vadileri']]),
  s('salkim-sogut', 'Salkım Söğüt', 'Salix babylonica', SAL, 'yaprakli', '8–15 m', 'Nisan',
    'Aşağı sarkan ince dallarıyla göl kıyılarının şiirsel ağacı. Köken olarak Çin’e ait olsa da Anadolu’da yüzyıllardır dikilir.',
    ['Su kenarı peyzajında gölge ve estetik', 'Kıyı erozyonuna karşı koruma', 'Halk hekiminde söğüt kabuğu kullanımı'],
    [['İstanbul', 'Boğaz ve park kıyıları'], ['Bursa', 'Nilüfer çayı çevresi'], ['Bolu', 'Gölcük ve Abant']]),
  s('dag-karaagaci', 'Dağ Karaağacı', 'Ulmus glabra', 'Karaağaçgiller (Ulmaceae)', 'yaprakli', '25–35 m', 'Mart',
    'Dağ ormanlarının nemli vadilerinde yaşar. Hollanda karaağaç hastalığı nedeniyle birçok bölgede azalmıştır.',
    ['Kaliteli parke ve mobilya odunu', 'Dere vadilerinde gölge ve nem tutucu', 'Hastalığa dirençli bireyler genetik değer taşır'],
    [['Bolu', 'Yedigöller çevresi'], ['Kastamonu', 'Küre Dağları'], ['Giresun', 'Karadeniz iç yamaçları']]),
  s('cicekli-disbudak', 'Çiçekli Dışbudak', 'Fraxinus ornus', OLE, 'yaprakli', '8–15 m', 'Nisan – Mayıs',
    'Yapraklarla birlikte beyaz, kokulu salkım çiçekler açan dışbudaktır. Kurak taşlık yamaçlarda doğal olarak yetişir.',
    ['Arılar için erken bahar nektarı', 'Kurak ve kireçli arazilerin ağaçlandırması', 'Süs ağacı olarak kentlere uyum'],
    [['Edirne', 'Trakya kalıntı ormanları'], ['Çanakkale', 'Gelibolu yarımadası'], ['Bursa', 'Uludağ etekleri']]),
  s('gurgen', 'Adi Gürgen', 'Carpinus betulus', BET, 'yaprakli', '15–25 m', 'Nisan – Mayıs',
    'Kaslı, oluklu gövdesiyle tanınan, çok sert odunlu gürgen; kayın ve meşe ormanlarında yaygındır. Odunu çok yoğundur.',
    ['Alet sapı ve parke yapımında kullanılan sert odun', 'Orman altı mikro iklimini serinletir', 'Parklarda çit ve gölge ağacı'],
    [['Kırklareli', 'Istranca ormanları'], ['Düzce', 'Akçakoca yamaçları'], ['Zonguldak', 'Batı Karadeniz']]),
  s('dogu-gurgeni', 'Doğu Gürgeni', 'Carpinus orientalis', BET, 'yaprakli', '4–10 m', 'Nisan – Mayıs',
    'Kurak yamaçlarda çalımsı-küçük ağaç olarak yaşayan, meşelerle birlikte tipik maki geçiş kuşağı bitkisidir.',
    ['Erozyona karşı kurak yamaçlarda koruma', 'Yakacak odun ve çit bitkisi', 'Kuşlar için orman kenarı yaşam alanı'],
    [['Çanakkale', 'Biga yarımadası'], ['Manisa', 'Spil ve Yamanlar çevresi'], ['Bursa', 'Orhaneli çevresi']]),
  s('kara-gurgen', 'Kara Gürgen', 'Ostrya carpinifolia', BET, 'yaprakli', '10–20 m', 'Nisan – Mayıs',
    'Kuru yamaçlarda yaşayan, sert odunlu ve soğuğa dayanıklı bir ağaçtır. Kozalak benzeri meyve salkımlarıyla tanınır.',
    ['Çok sert ve sağlam odun', 'Kuru kayalık yamaçlarda toprak koruma', 'Kış beslenmesinde kuşlara tohum'],
    [['Zonguldak', 'Batı Karadeniz yamaçları'], ['Bartın', 'Ulus çevresi'], ['Artvin', 'Çoruh vadisi']]),
  s('alic', 'Alıç', 'Crataegus monogyna', ROS, 'yaprakli', '4–10 m', 'Nisan – Mayıs',
    'Beyaz çiçek salkımları ve kırmızı meyveleriyle bahar ve sonbaharın güzel ağacıdır. Meyveleri halk hekiminde kalp sağlığı için kullanılır.',
    ['Meyvesi geleneksel şifalı bitki olarak değerlendirilir', 'Çit ve rüzgâr perdesi olarak kullanılır', 'Kuşlar ve arılar için besin'],
    [['Ankara', 'Kızılcahamam çevresi'], ['Erzurum', 'Yüksek yayla vadileri'], ['Konya', 'Meram bahçeleri']]),
  s('uvez', 'Üvez', 'Sorbus aucuparia', ROS, 'yaprakli', '5–15 m', 'Mayıs – Haziran',
    'Parlak turuncu-kırmızı meyve salkımlarıyla sonbaharın simgesi olan dağ ağacıdır. Soğuğa dayanıklıdır.',
    ['Meyveleri kuşlar için kış besini', 'Reçel ve geleneksel içeceklerde kullanım', 'Dağ peyzajında süs ağacı'],
    [['Bolu', 'Köroğlu Dağları'], ['Trabzon', 'Uzungöl çevresi yaylaları'], ['Kastamonu', 'Ilgaz Dağı']]),
  s('barut-agaci', 'Barut Ağacı', 'Sorbus torminalis', ROS, 'yaprakli', '10–25 m', 'Mayıs',
    'Ağaç türleri içinde yavaş büyüyen, yüksek değerli odunuyla tanınır. Meşe ormanlarının serin gölgelerinde bulunur.',
    ['Mobilya ve el sanatlarında değerli odun', 'Meyveleri doğada kuşlar için besin', 'Sonbaharda parlak kızıl yaprak rengi'],
    [['Kırklareli', 'Istranca ormanları'], ['Bursa', 'Uludağ etekleri'], ['Zonguldak', 'Kuzey Anadolu ormanları']]),
  s('balkan-akcaagaci', 'Balkan Akçaağacı', 'Acer hyrcanum', ACE, 'yaprakli', '10–20 m', 'Nisan – Mayıs',
    'Yarı gölgeyi seven, dağ ormanlarının serin tabanlarının akçaağacıdır. Sonbaharda parlak sarı yaprakları vardır.',
    ['Sonbahar rengiyle peyzaj değeri', 'Odunu mobilya ve enstrüman yapımında kullanılır', 'Nektarıyla arıcılığa katkı'],
    [['Kırklareli', 'Istranca ormanları'], ['Çanakkale', 'Kazdağı çevresi'], ['Bolu', 'Yedigöller']]),
  s('norvec-akcaagaci', 'Norveç Akçaağacı', 'Acer platanoides', ACE, 'yaprakli', '15–25 m', 'Nisan',
    'Parlak sarı sonbahar rengi ve geniş taçla tanınan akçaağaçtır. Kuzey Anadolu’nun yüksek serin vadilerinde ve parklarda görülür.',
    ['Kent parklarında güçlü gölge ve renk', 'Kuvvetli, hafif odun', 'Erken polenle arılara katkı'],
    [['Bolu', 'Abant Gölü çevresi'], ['Kastamonu', 'Küre Dağları Milli Parkı'], ['Düzce', 'Kaynaşlı çevresi']]),
  s('negundo-akcaagaci', 'Dişbudak Yapraklı Akçaağaç', 'Acer negundo', ACE, 'yaprakli', '10–20 m', 'Mart – Nisan',
    'Kuzey Amerika kökenli, hızlı büyüyen ve kentlerde yol ağacı olarak dikilen akçaağaçtır. Sulak alanlarda kolayca yayılır.',
    ['Kentte hızlı gölge ve yeşil örtü', 'Kuraklığa ve kirliliğe toleranslı', 'Yayılma riski nedeniyle dikimi izlenmelidir'],
    [['Ankara', 'Parklarda yaygın dikim'], ['Eskişehir', 'Porsuk çayı kıyıları'], ['Konya', 'Kent ağaçlandırmaları']], 'Yabancı tür'),
  s('at-kestanesi', 'At Kestanesi', 'Aesculus hippocastanum', 'Atkestanesigiller (Sapindaceae)', 'yaprakli', '20–30 m', 'Nisan – Mayıs',
    'Mumları andıran dik, beyaz çiçek salkımları ve parlak, zehirli kestaneleriyle bilinir. Balkanlar kökenlidir, Anadolu parklarının sevilen ağacıdır.',
    ['Kentlerde geniş, serin gölge', 'Çiçekleriyle polinatörlere besin', 'Kabuk ve tohumundan ilaç sanayisinde yararlanılır'],
    [['İstanbul', 'Gülhane ve Emirgan korusu'], ['Bursa', 'Uludağ yolu'], ['Bolu', 'Şehir parkları']]),
  s('sigla', 'Sığla Ağacı', 'Liquidambar orientalis', 'Sığlagiller (Altingiaceae)', 'yaprakli', '15–35 m', 'Nisan – Mayıs',
    'Yalnızca Güneybatı Anadolu’da yetişen, çok eski bir relikt türdür. Gövdesinden elde edilen reçine geçmişten bugüne parfüm ve ilaç yapımında değerlidir.',
    ['Reçinesi (sığla yağı) tıp ve parfümeride kullanılır', 'Koruma altındaki Köyceğiz sulak ormanını oluşturur', 'Türkiye endemiği olarak ulusal doğa mirası'],
    [['Köyceğiz', 'Sülüngür gölü çevresi sığla ormanı'], ['Fethiye', 'Dalaman ovası kenarları'], ['Marmaris', 'Gökova körfezi kıyıları']], 'Endemik · Relikt'),
  s('turk-findigi', 'Türk Fındığı', 'Corylus colurna', BET, 'yaprakli', '15–30 m', 'Şubat – Mart',
    'Ağaç formunda büyüyen, kabuklu meyveleri yeşil püsküllü yapılara sarılı, yerli fındık türüdür. Peyzajda piramit tepesiyle görünür.',
    ['Kentlerde dayanıklı sokak ağacı', 'Meyvesi yaban hayatına besin', 'Odunu parlak ve değerlidir'],
    [['Artvin', 'Çoruh vadisi dağ ormanları'], ['Kastamonu', 'Daday ormanları'], ['Giresun', 'İç Karadeniz yamaçları']]),
  s('sumak', 'Sumak', 'Rhus coriaria', ANA, 'yaprakli', '2–6 m', 'Mayıs – Haziran',
    'Koyu kırmızı meyve salkımlarının kurutulup öğütülmesiyle baharat elde edilen çalımsı küçük ağaçtır. Güneydoğu mutfağının vazgeçilmezidir.',
    ['Mutfakta baharat olarak yaygın kullanım', 'Deri tabaklamada tanen kaynağı', 'Kurak, fakir topraklarda yetişir'],
    [['Gaziantep', 'Nizip ve Araban çevresi'], ['Kahramanmaraş', 'Yukarı Maraş kırsalı'], ['Hatay', 'Amanos yamaçları']]),
  s('katalpa', 'Katalpa', 'Catalpa bignonioides', 'Bignoniagiller (Bignoniaceae)', 'yaprakli', '10–15 m', 'Haziran – Temmuz',
    'Büyük kalp biçimli yaprakları ve uzun, çubuk gibi meyveleriyle bilinen park ağacıdır. Yaz başında beyaz çiçekleri vardır.',
    ['Kentlerde geniş gölge', 'Süs ağacı olarak çarpıcı çiçekler', 'Arılar için geç nektar kaynağı'],
    [['İstanbul', 'Parklarda dikili'], ['Ankara', 'Kent parkları'], ['İzmir', 'Alsancak çevresi']], 'Yabancı tür'),
  s('ailanthus', 'Kokulu Ağaç (Ailanthus)', 'Ailanthus altissima', 'Acıağaçgiller (Simaroubaceae)', 'yaprakli', '15–25 m', 'Mayıs – Haziran',
    'Çin kökenli, hızla yayılan ve kentin her çatlağında filizlenen ağaçtır. İstilacı türler arasında izlenir.',
    ['Çok zor koşullarda hızla büyür', 'Kentsel alanlarda hava kirliliğine toleranslı', 'Yayılımı kontrol edilmesi gereken yabancı tür'],
    [['İstanbul', 'Kentsel boş alanlarda yaygın'], ['Ankara', 'Şehir çevresi'], ['Bursa', 'Nilüfer çayı çevresi']], 'İstilacı'),
  s('gladicya', 'Gladiçya', 'Gleditsia triacanthos', FAB, 'yaprakli', '15–25 m', 'Mayıs – Haziran',
    'Uzun, çatallı dikenleri ve bükülmüş baklalarıyla tanınan Kuzey Amerika ağacıdır. Hafif gölgesiyle kent sokaklarının tercih edilen türüdür.',
    ['İnce yapraklarıyla hafif gölge ve su tasarrufu', 'Kuraklığa ve tuzlu toprağa toleranslı', 'Baklaları kuşlara ve arılara besin'],
    [['İstanbul', 'Yol ağaçlandırması'], ['Ankara', 'Bulvar ve parklarda'], ['Konya', 'Kent içi parklar']], 'Yabancı tür'),
  s('pagoda-agaci', 'Pagoda Ağacı', 'Styphnolobium japonicum', FAB, 'yaprakli', '15–25 m', 'Temmuz – Ağustos',
    'Yaz ortasında krem rengi çiçek salkımlarıyla dolan, Çin kökenli süs ve yol ağacıdır. Kent koşullarına çok dayanıklıdır.',
    ['Yaz aylarında nadir nektar kaynağı', 'Kirliliğe ve kuraklığa dayanıklı', 'Geniş taçla serin gölge'],
    [['İstanbul', 'Yıldız Parkı'], ['Ankara', 'Kent parkları'], ['Bursa', 'Botanik Park']], 'Yabancı tür'),
  s('ipek-agaci', 'İpek Ağacı', 'Albizia julibrissin', FAB, 'yaprakli', '6–12 m', 'Haziran – Ağustos',
    'Pembe ipeksi çiçek püskülleri ve tüysü yapraklarıyla yaz süsüdür. Güneşi seven, kuraklığa dayanıklı bir park ağacıdır.',
    ['Yaz çiçekleriyle peyzaj değeri', 'Azot bağlayıcı kökleri', 'Kentte kuraklığa dayanıklı süs ağacı'],
    [['İstanbul', 'Sahil parkları'], ['İzmir', 'Karşıyaka sahili'], ['Antalya', 'Kent içi caddeler']], 'Yabancı tür'),
  s('paulownia', 'Paulownia', 'Paulownia tomentosa', 'Paulowniagiller (Paulowniaceae)', 'yaprakli', '10–20 m', 'Nisan – Mayıs',
    'Çok hızlı büyüyen, mavi-mor çiçek salkımlarına sahip Çin kökenli ağaçtır. Çiçekleri yapraklardan önce açar.',
    ['Hızlı büyüme ve yüksek karbon tutma', 'Hafif ve dayanıklı odun', 'Polinatörler için erken bahar çiçeği'],
    [['İstanbul', 'Parklarda dikili'], ['Sakarya', 'Sapanca çevresi'], ['Bursa', 'Süs bitkisi olarak']], 'Yabancı tür'),
  s('lale-agaci', 'Lale Ağacı', 'Liriodendron tulipifera', 'Manolyagiller (Magnoliaceae)', 'yaprakli', '25–40 m', 'Mayıs – Haziran',
    'Lale biçimli turuncu-sarı çiçekleri ve dört loblu garip yapraklarıyla Kuzey Amerika’dan gelen yüksek bir ağaçtır.',
    ['Geniş taçla güçlü gölge', 'Çiçekleri arılar için nektar kaynağı', 'Sonbaharda altın sarısı yaprak'],
    [['İstanbul', 'Emirgan Korusu'], ['Bursa', 'Botanik Park'], ['Sakarya', 'Kent parkları']], 'Yabancı tür'),
  s('manolya', 'Manolya', 'Magnolia grandiflora', 'Manolyagiller (Magnoliaceae)', 'yaprakli', '10–25 m', 'Mayıs – Ağustos',
    'Büyük, parlak yaprakları ve limon kokulu dev beyaz çiçekleriyle bilinen her dem yeşil ağaçtır. Karadeniz ve Marmara parklarında yaygındır.',
    ['Kokulu çiçekleriyle peyzaj değeri', 'Her dem yeşil gölge ve rüzgâr perdesi', 'Çiçekleri hem ilkel yapısıyla böcekler tarafından tozlaştırılır'],
    [['Rize', 'Parklar ve evlerin bahçeleri'], ['İstanbul', 'Yıldız Parkı'], ['Samsun', 'Kıyı şeridi parkları']], 'Yabancı tür'),
  s('ginkgo', 'Ginkgo', 'Ginkgo biloba', 'Ginkgogiller (Ginkgoaceae)', 'yaprakli', '20–35 m', 'Nisan',
    'Dinozorlar çağından beri değişmeden gelen “yaşayan fosil”. Yelpaze biçimli yapraklarıyla sonbaharda altın sarısına döner.',
    ['Kirli kent havasına çok dayanıklı', 'Yaşayan fosil olarak bilimsel değeri yüksek', 'Sonbahar renkleriyle parklarda değerli'],
    [['İstanbul', 'Gülhane Parkı'], ['Ankara', 'Botanik bahçeleri'], ['Bursa', 'Botanik Park']], 'Yaşayan fosil'),
  s('datca-hurmasi', 'Datça Hurması', 'Phoenix theophrasti', 'Palmiyegiller (Arecaceae)', 'maki', '4–10 m', 'Nisan – Mayıs',
    'Yalnızca Datça ve Girit’te doğal olarak bulunan, Türkiye’nin tek yerli palmiyesidir. Kumul ve dere ağızlarında küçük koloniler oluşturur.',
    ['Koruma altındaki nadir endemik palmiye', 'Kumul ekosistemlerinin dengeleyicisi', 'Ekoturizm değeri yüksek simge tür'],
    [['Datça', 'Hurma Burnu ve Palamutbükü'], ['Marmaris', 'Bozburun çevresi']], 'Endemik'),
  s('okaliptus', 'Okaliptüs', 'Eucalyptus camaldulensis', MYR, 'yaprakli', '20–40 m', 'Haziran – Eylül',
    'Avustralya kökenli, Türkiye’de bataklıkları kurutmak için dikilen ve yol kenarlarında uzun sıralar oluşturan hızlı büyüyen bir ağaçtır.',
    ['Hızlı büyüme ve kereste', 'Çiçekleri arıcılık için nektar kaynağı', 'Yaprak yağı ilaç ve kozmetikte kullanılır'],
    [['Adana', 'Seyhan ve Ceyhan ovası'], ['Mersin', 'Tarsus çevresi'], ['Antalya', 'Aksu ve Manavgat ovaları']], 'Yabancı tür'),
  s('ilgin', 'Ilgın', 'Tamarix smyrnensis', 'Ilgıngiller (Tamaricaceae)', 'maki', '3–8 m', 'Mayıs – Eylül',
    'Tuzlu toprakların ve deniz kıyısının dayanıklı bitkisi; ince pembe çiçek başaklarıyla yaz boyunca açar.',
    ['Tuzlu ve kumlu toprakları bağlar', 'Kıyı ve sulak alanlarda kuş yuvalama alanı', 'Rüzgâr perdesi olarak değerli'],
    [['İzmir', 'Gediz Deltası'], ['Edirne', 'Meriç deltası'], ['Aksaray', 'Tuz Gölü çevresi']]),
  s('tesbih-agaci', 'Tesbih Ağacı', 'Melia azedarach', 'Maun Ailesi (Meliaceae)', 'yaprakli', '8–15 m', 'Nisan – Mayıs',
    'Küçük leylak renkli çiçekleri ve boncuk gibi meyveleriyle Akdeniz kentlerinin süs ağacıdır. Meyveleri geleneksel olarak tesbih yapımında kullanılır.',
    ['Kuraklığa ve sıcağa dayanıklı kent ağacı', 'Çiçekleri hoş kokulu', 'Meyve çekirdekleri el sanatlarında kullanılır'],
    [['Mersin', 'Kıyı şeridi parkları'], ['Adana', 'Kent içi sokaklar'], ['Antalya', 'Konyaaltı sahili']], 'Yabancı tür'),
  s('funda', 'Ağaç Funda', 'Erica arborea', 'Fundagiller (Ericaceae)', 'maki', '2–5 m', 'Mart – Nisan',
    'Yoğun beyaz çiçeklerle baharın başında makileri kar yağmış gibi gösteren fundalık bitkisi. Kökü pipo ve bıçak sapı yapımında değerlidir.',
    ['Kökünden pipo üretimi (kök kütüğü)', 'Maki ekosistemlerinde nektar kaynağı', 'Erozyon sahalarını kapatır'],
    [['Muğla', 'Marmaris ve Datça çevresi'], ['Aydın', 'Çine ormanları'], ['İzmir', 'Karaburun makileri']]),
  s('kocayemis', 'Kocayemiş', 'Arbutus unedo', 'Fundagiller (Ericaceae)', 'maki', '3–8 m', 'Ekim – Aralık',
    'Hem çiçek hem olgun meyvesi aynı anda bulunabilen, çilek benzeri kırmızı meyveli makilik ağacıdır. Sonbaharda açar, ertesi yıl olgunlaşır.',
    ['Meyveleri reçel ve likör için kullanılır', 'Makide yaban hayatına kış besini', 'Sonbahar çiçekleriyle nektar kaynağı'],
    [['Muğla', 'Köyceğiz ve Marmaris makileri'], ['Antalya', 'Kemer yamaçları'], ['İzmir', 'Karaburun']]),
  s('ormangulu', 'Mor Ormangülü', 'Rhododendron ponticum', 'Fundagiller (Ericaceae)', 'maki', '2–6 m', 'Mayıs – Haziran',
    'Karadeniz yaylalarını mor ve pembe çiçeklerle donatan, her dem yeşil çalımsı ağaçtır. Çiçeklerinden elde edilen bal “deli bal” olarak bilinir.',
    ['Karadeniz yaylalarının simgesi ve turistik değer', 'Sulak yamaçlarda toprak koruması', 'Nadir bal üretimi'],
    [['Rize', 'Ayder ve Pokut yaylaları'], ['Trabzon', 'Uzungöl çevresi'], ['Giresun', 'Kümbet ve Bektaş yaylaları']]),
  s('findik', 'Fındık', 'Corylus avellana', BET, 'meyve', '3–6 m', 'Ocak – Şubat',
    'Dünya fındık üretiminin büyük bölümü Karadeniz yamaçlarından gelir. Türkiye fındığı, kış ortasında erkek çiçek püskülleriyle erken uyanır.',
    ['Türkiye’nin en önemli ihraç tarım ürünlerinden', 'Eğimli Karadeniz yamaçlarında toprak koruma', 'Yüksek besin değerli kuruyemiş'],
    [['Giresun', 'Piraziz ve Bulancak bahçeleri'], ['Ordu', 'Fındık üretiminin merkezi'], ['Samsun', 'Terme ve Çarşamba'], ['Sakarya', 'Akyazı ve Hendek']], 'Coğrafi işaret'),
  s('antep-fistigi', 'Antep Fıstığı', 'Pistacia vera', ANA, 'meyve', '4–8 m', 'Nisan',
    'Güneydoğu Anadolu’nun kurak taşlık araziyi altına çeviren ağacıdır. Yılda bir ürün veren (periyodisite gösteren) bu ağaç baklavanın simgesidir.',
    ['Yüksek katma değerli kuru meyve', 'Kurak ve taşlık arazide sulamasız yetişebilir', 'Bölgenin tatlı sanayisi temeli'],
    [['Gaziantep', 'Nizip, Şehitkamil ve Araban'], ['Şanlıurfa', 'Siverek ve Birecik'], ['Siirt', 'Siirt fıstığı']], 'Coğrafi işaret'),
  s('elma', 'Elma', 'Malus domestica', ROS, 'meyve', '4–8 m', 'Nisan – Mayıs',
    'Anadolu’nun en yaygın meyvelerinden biri; Amasya, Karaman ve Isparta dağ vadilerinde büyük bahçeler kurar. Çiçekleri baharın müjdesidir.',
    ['Türkiye’nin önde gelen meyve üretimi', 'Kuşlar ve arılar için çiçek kaynağı', 'Taze, kurutulmuş ve suyu olarak değerlendirilir'],
    [['Amasya', 'Amasya elması — Coğrafi İşaretli'], ['Isparta', 'Eğirdir çevresi büyük bahçeler'], ['Karaman', 'Ermenek ve Taşkent']], 'Coğrafi işaret'),
  s('armut', 'Armut', 'Pyrus communis', ROS, 'meyve', '5–12 m', 'Nisan',
    'Anadolu’da binlerce yıldır yetiştirilen, bol çiçekli meyve ağacıdır. Yabani formu ahlat olarak köy kenarlarında bulunur.',
    ['Meyve ve kurutma ürünü', 'Yabani formu dayanıklı anaç olarak kullanılır', 'Arılar için bahar nektarı'],
    [['Bursa', 'İnegöl çevresi'], ['Bilecik', 'Söğüt çevresi'], ['Eskişehir', 'Sakarya havzası']]),
  s('ayva', 'Ayva', 'Cydonia oblonga', ROS, 'meyve', '3–6 m', 'Nisan – Mayıs',
    'Kış ortasına kadar dalında kalabilen, sarı tüylü meyveleriyle tanınan ve reçeli, tatlısı ile ünlü bir meyve ağacıdır.',
    ['Reçel, tatlı ve geleneksel sağlık içeceği', 'Anaç olarak armut ve alıç için kullanılır', 'Soğuk kış için dayanıklı'],
    [['Bursa', 'Ayva bahçeleri'], ['Bilecik', 'Bozüyük çevresi'], ['Eskişehir', 'Ayva bahçeleri']]),
  s('visne', 'Vişne', 'Prunus cerasus', ROS, 'meyve', '4–8 m', 'Nisan',
    'Ekşi meyvesiyle şurup, reçel ve komposto için aranan, bahar başında bembeyaz açan meyve ağacıdır.',
    ['Meyvesi sanayi ve gıdada yaygın', 'Soğuk iklimlere uyumlu', 'Arılara erken nektar'],
    [['Afyon', 'Afyonkarahisar vişnesi'], ['Kayseri', 'Develi bahçeleri'], ['Ankara', 'Nallıhan çevresi']]),
  s('seftali', 'Şeftali', 'Prunus persica', ROS, 'meyve', '3–6 m', 'Mart – Nisan',
    'Pembe çiçekleriyle bahar başında bahçeleri aydınlatan, sulu meyveli bir ağaçtır. Çin kökenli olup antik çağlardan beri Anadolu’da yetiştirilir.',
    ['Taze ve konserve olarak ihracat', 'Kıyı ve ova tarım ekonomisi', 'Çiçekleriyle bahar görsel şöleni'],
    [['Bursa', 'Gemlik ve Mudanya'], ['Çanakkale', 'Çan ve Biga'], ['Mersin', 'Silifke bahçeleri']]),
  s('erik', 'Erik', 'Prunus domestica', ROS, 'meyve', '4–8 m', 'Mart – Nisan',
    'Dallarını bembeyaz çiçeklerle donatan erik, kurutulmuş (kuru erik) ve reçel olarak yaygın tüketilen bir meyve ağacıdır.',
    ['Taze ve kuru erik olarak değerlendirilir', 'Soğuğa dayanıklı bahçe ağacı', 'Çiçekleri arıcılığa katkı sağlar'],
    [['Bilecik', 'Bozüyük ve Pazaryeri'], ['Bursa', 'Kestel ve Orhaneli'], ['Erzincan', 'Üzümlü ve Tercan']]),
  s('nar', 'Nar', 'Punica granatum', 'Narlar (Lythraceae)', 'meyve', '3–6 m', 'Mayıs – Haziran',
    'Parlak kırmızı çiçekleri ve yakut renkli taneli meyveleriyle Akdeniz ve Güneydoğu’nun simgesi olan meyve ağacıdır.',
    ['Meyvesi antioksidan zengini', 'Kurak koşullara çok dayanıklı', 'Nar ekşisi ve suyu olarak ekonomik değer'],
    [['Hatay', 'Samandağ ve Defne'], ['Antalya', 'Kumluca bahçeleri'], ['Muğla', 'Fethiye ve Dalaman']]),
  s('hurma', 'Trabzon Hurması', 'Diospyros kaki', 'Abanozgiller (Ebenaceae)', 'meyve', '6–12 m', 'Mayıs – Haziran',
    'Yapraklar döküldükten sonra turuncu meyveleri dallarda kalan ve kış sofralarını süsleyen Doğu Asya kökenli meyve ağacıdır.',
    ['Kış meyvesi olarak ekonomik değer', 'Sonbahar renkleriyle peyzaj değeri', 'Kuşlara kış besini'],
    [['Trabzon', 'Sahil bahçeleri'], ['Rize', 'Hopa ve Fındıklı'], ['Hatay', 'Samandağ bahçeleri']], 'Yabancı tür'),
  s('musmula', 'Muşmula', 'Mespilus germanica', ROS, 'meyve', '3–6 m', 'Mayıs',
    'Kış ayının başında “çürümüş” hale gelince yenen tatlı-ekşi meyveleriyle bilinen, görkemli beyaz çiçekli geleneksel meyve ağacıdır.',
    ['Kış meyvesi olarak geleneksel değer', 'Soğuk bölgelerde yetişir', 'Zengin çiçekleriyle böcek dostu'],
    [['Bolu', 'Köy bahçeleri'], ['Sakarya', 'Kocaali çevresi'], ['Zonguldak', 'Karadeniz Ereğli']]),
  s('ahlat', 'Ahlat', 'Pyrus elaeagnifolia', ROS, 'meyve', '4–8 m', 'Nisan – Mayıs',
    'Gümüşi yaprakları ve küçük armut biçimli meyveleriyle, Orta Anadolu bozkırının sembol ağaçlarından biridir. Armut ağaçlarına anaç olarak da kullanılır.',
    ['Bozkırda tek tek duran korunaklı gölge ağacı', 'Meyve ağaçlarına dayanıklı anaç', 'Kurağa çok dayanıklı yerli tür'],
    [['Konya', 'Karapınar çevresi'], ['Kırşehir', 'Kaman bozkırları'], ['Yozgat', 'Sorgun çevresi']]),
  s('yenidunya', 'Yenidünya', 'Eriobotrya japonica', ROS, 'meyve', '5–10 m', 'Ekim – Aralık',
    'Sonbaharda çiçek açıp ilkbaharda olgunlaşan, Akdeniz kıyısında yetişen turuncu meyveli her dem yeşil ağaçtır.',
    ['Erken ilkbahar meyvesi olarak değerli', 'Kış çiçekleriyle arılara nektar', 'Geniş yapraklarıyla serin gölge'],
    [['Antalya', 'Alanya ve Manavgat'], ['Mersin', 'Erdemli ve Silifke'], ['Hatay', 'Samandağ']]),
  s('portakal', 'Portakal', 'Citrus sinensis', RUT, 'meyve', '4–8 m', 'Nisan – Mayıs',
    'Akdeniz kıyılarının turuncu altın ağacı. Çiçekleri çok kokulu; Türkiye turunçgil üretiminde dünya liderlerindendir.',
    ['İhracat gelirinin önemli kalemi', 'Kış aylarında C vitamini kaynağı', 'Kokulu çiçekleriyle arıcılığa destek'],
    [['Adana', 'Ova bahçeleri'], ['Mersin', 'Erdemli ve Anamur'], ['Antalya', 'Finike portakalı — Coğrafi İşaret'], ['Hatay', 'Samandağ bahçeleri']], 'Coğrafi işaret'),
  s('limon', 'Limon', 'Citrus limon', RUT, 'meyve', '3–6 m', 'Yıl boyu',
    'Yıl boyunca çiçek ve meyve verebilen Akdeniz kıyısı turunçgilidir. Bahçelerde çiçekleri ve meyveleri aynı anda bulunabilir.',
    ['Yüksek C vitamini ve mutfak değeri', 'Kıyı tarım ekonomisinin ana ürünü', 'Hoş kokulu çiçekleri'],
    [['Mersin', 'Erdemli ve Silifke'], ['Adana', 'Kozan ve Ceyhan'], ['Antalya', 'Kumluca ve Finike']]),
  s('turunc', 'Turunç', 'Citrus aurantium', RUT, 'meyve', '4–8 m', 'Nisan – Mayıs',
    'Ekşi-acı meyveleri ve çok kokulu çiçekleriyle Akdeniz bahçelerinin, sokak ağaçlarının tanıdık türüdür. Kokulu çiçeklerinden turunç çiçeği suyu yapılır.',
    ['Çiçekleri parfüm ve çiçek suyunda kullanılır', 'Meyvesinden reçel yapılır', 'Kentlerde sokak ağacı olarak dikilir'],
    [['Hatay', 'Antakya sokakları'], ['Adana', 'Kent içi caddeler'], ['Mersin', 'Kıyı bahçeleri']]),
  s('karayemis', 'Karayemiş', 'Prunus laurocerasus', ROS, 'meyve', '4–8 m', 'Nisan – Mayıs',
    'Doğu Karadeniz’in nemli ormanlarında doğal yetişen, her dem yeşil, parlak yapraklı bir ağaçtır. Karayemiş (taflan) meyveleri tazedir.',
    ['Karadeniz mutfağında yöresel meyve', 'Her dem yeşil yaprakları rüzgâr perdesi', 'Orman altı katmanında yaban hayatına barınak'],
    [['Rize', 'Çamlıhemşin ormanları'], ['Trabzon', 'Sürmene yamaçları'], ['Artvin', 'Hopa ve Arhavi']]),
  s('hunnap', 'Hünnap', 'Ziziphus jujuba', 'Çaparigiller (Rhamnaceae)', 'meyve', '4–8 m', 'Mayıs – Haziran',
    'Küçük, tatlı kırmızı meyveleriyle tanınan, Orta Doğu’dan Anadolu’ya uzanan kuraklığa dayanıklı ağaçtır.',
    ['Meyveleri taze veya kurutulmuş olarak tüketilir', 'Kurak, taşlık yerlerde yetişir', 'Halk hekiminde geleneksel kullanım'],
    [['Hatay', 'Antakya bahçeleri'], ['Mardin', 'Savur çevresi'], ['Şanlıurfa', 'Harran ovası kenarları']]),
  s('mahlep', 'Mahlep', 'Prunus mahaleb', ROS, 'meyve', '3–8 m', 'Nisan – Mayıs',
    'Çekirdeğinden elde edilen mahlep baharatı çörek ve pasta tariflerinde kullanılır. Kurak yamaçlarda kendiliğinden yetişir.',
    ['Mahlep baharatı (çekirdek) mutfakta değerli', 'Kireçli taşlık yamaçlarda toprak tutar', 'Kiraz ve vişne için dayanıklı anaç'],
    [['Ankara', 'Kızılcahamam çevresi'], ['Kastamonu', 'Taşköprü'], ['Çorum', 'İskilip çevresi']]),
  s('kafkas-zelkovasi', 'Kafkas Zelkovası', 'Zelkova carpinifolia', 'Karaağaçgiller (Ulmaceae)', 'yaprakli', '20–35 m', 'Nisan',
    'Doğu Karadeniz ve Kafkaslar’ın relikt ağaçlarından; çok eski bir tür olup, Anadolu’nun kuzey vadilerinde kalıntı topluluklar halinde yaşar.',
    ['Dere vadilerinde toprak ve nem koruması', 'Relikt tür olarak bilimsel değeri', 'Odunu sert, mobilya yapımına uygun'],
    [['Artvin', 'Şavşat ve Artvin yamaçları'], ['Giresun', 'İç Karadeniz vadileri'], ['Trabzon', 'Maçka vadileri']], 'Relikt'),
  s('akdeniz-servisi', 'Akdeniz Servisi (Yatık)', 'Cupressus sempervirens var. horizontalis', CUP, 'ibreli', '15–25 m', 'Şubat – Mart',
    'Dikey değil dallarını yatay açan doğal Akdeniz servisi formudur. Akdeniz havzasında kıyı ve vadi yamaçlarına yayılır.',
    ['Kuraklığa çok dayanıklı', 'Rüzgâr perdesi ve peyzaj ağacı', 'Uzun ömür ve odun dayanıklılığı'],
    [['Antalya', 'Köprülü Kanyon çevresi'], ['Muğla', 'Fethiye ve Köyceğiz'], ['Mersin', 'Silifke ve Gülnar']]),
  s('memecik-zeytini', 'Memecik Zeytini', 'Olea europaea cv. Memecik', OLE, 'meyve', '6–12 m', 'Mayıs',
    'Ege’nin yağlık ve sofralık çeşidi. Memecik, Türkiye’nin yağlık zeytin üretiminin önemli çeşitlerindendir.',
    ['Kaliteli zeytinyağı üretimi', 'Kurak yamaç tarımının temeli', 'Asırlık anıt ağaçlar'],
    [['Aydın', 'Çine ve Köşk'], ['Muğla', 'Milas ve Bodrum'], ['İzmir', 'Urla ve Seferihisar']]),
  s('gemlik-zeytini', 'Gemlik Zeytini', 'Olea europaea cv. Gemlik', OLE, 'meyve', '5–10 m', 'Mayıs',
    'Marmara kıyılarının sofralık zeytin çeşidi. Sürme ve salamura tarzında hazırlanan kahvaltılık zeytin olarak ünlüdür.',
    ['Sofralık zeytin ihracatı', 'Marmara iklimine uyumlu', 'Kıyı yamaç tarımı için ideal'],
    [['Bursa', 'Gemlik ve Mudanya'], ['Yalova', 'Armutlu çevresi'], ['Balıkesir', 'Edremit körfezi']], 'Coğrafi işaret'),
  s('edremit-zeytini', 'Edremit Zeytini', 'Olea europaea cv. Edremit', OLE, 'meyve', '6–12 m', 'Mayıs',
    'Kazdağları eteklerinde yetişen yüksek kaliteli yağlık zeytin; çevre ekosistem ve turizmin önemli bir ayağıdır.',
    ['Natürel zeytinyağı üretimi', 'Kıyı ve yamaç ekonomisi', 'Zeytinli peyzaj turizmi'],
    [['Edremit', 'Zeytinli ve Altınoluk'], ['Ayvalık', 'Zeytin adaları çevresi'], ['Balıkesir', 'Burhaniye']], 'Coğrafi işaret'),
  s('mimoza', 'Mimoza', 'Acacia dealbata', FAB, 'yaprakli', '5–15 m', 'Ocak – Mart',
    'Şubatta ağaç boyunca sarı tüycüklü çiçeklerle dolan Avustralya kökenli, kıyı şeridinde yetişen süs ağacıdır.',
    ['Kış sonunda çiçeğiyle kıyı peyzajını renklendirir', 'Hızlı büyür', 'Azot bağlayıcı kökler'],
    [['Antalya', 'Kıyı parkları'], ['Mersin', 'Erdemli kıyıları'], ['Muğla', 'Fethiye ve Dalyan']], 'Yabancı tür'),
  s('kirim-ihlamuru', 'Kırım Ihlamuru', 'Tilia × euchlora', 'Ihlamurgiller (Malvaceae)', 'yaprakli', '15–25 m', 'Haziran',
    'Parlak yeşil yaprakları ve hoş kokulu çiçekleriyle tercih edilen melez ıhlamurdur. Kentlerde cadde ve park ağacı olarak yaygın dikilir.',
    ['Kent caddelerinde dayanıklı gölge', 'Arılara nektar', 'Çiçekleri çay olarak kullanılır'],
    [['İstanbul', 'Cadde ağaçlandırmaları'], ['Ankara', 'Kızılay ve Kuğulu Park'], ['Bursa', 'Atatürk caddesi']], 'Yabancı tür'),

  /* ---- İkinci grup ---- */
  s('igde', 'İğde', 'Elaeagnus angustifolia', 'İğdegiller (Elaeagnaceae)', 'meyve', '5–10 m', 'Mayıs – Haziran',
    'Gümüşi yaprakları ve çok kokulu küçük sarı çiçekleriyle bozkırın tanıdık ağacıdır. Tuzlu, kurak topraklarda bile yetişir; un kıvamındaki meyveleri yenir.',
    ['Tuzlu ve kurak topraklarda ağaçlandırma', 'Çiçekleri çok kokulu, arılara nektar', 'Meyveleri geleneksel olarak yenir ve kurutulur'],
    [['Ankara', 'Kent çevresi ve dere boyları'], ['Erzurum', 'Aras vadisi'], ['Iğdır', 'Aras ovası'], ['Konya', 'Tuz Gölü havzası']]),
  s('deniz-dikeni', 'Yalancı İğde (Deniz Dikeni)', 'Hippophae rhamnoides', 'İğdegiller (Elaeagnaceae)', 'meyve', '2–6 m', 'Nisan',
    'Parlak turuncu meyveleriyle dere yataklarını ve yüksek vadileri kaplayan dikenli çalımsı ağaçtır. Meyveleri C vitamini bakımından çok zengindir.',
    ['Meyveleri vitamin açısından zengin', 'Nehir yataklarında toprağı bağlar', 'Azot bağlayıcı kök yapısı'],
    [['Erzurum', 'Tortum ve Oltu vadileri'], ['Artvin', 'Çoruh Nehri yatağı'], ['Bayburt', 'Çoruh vadisi']]),
  s('firat-kavagi', 'Fırat Kavağı', 'Populus euphratica', SAL, 'yaprakli', '10–20 m', 'Mart – Nisan',
    'Yaprak şekli yaşa göre değişen, tuzlu ve sıcak nehir kıyılarında yaşayan nadir bir kavaktır. Güneydoğu Anadolu’nun nehir ormanlarının temel türüdür.',
    ['Nehir kıyısı ormanı oluşturur', 'Tuzlu ve kurak koşullara dayanıklı', 'Güneydoğu’da gölge ve odun kaynağı'],
    [['Şanlıurfa', 'Birecik Fırat kıyıları'], ['Gaziantep', 'Nizip Fırat vadisi'], ['Diyarbakır', 'Dicle kıyıları'], ['Şırnak', 'Cizre çevresi']]),
  s('hayit', 'Hayıt', 'Vitex agnus-castus', 'Ballıbabagiller (Lamiaceae)', 'maki', '2–5 m', 'Haziran – Eylül',
    'Yaz boyunca mavi-mor çiçek başakları açan, dere yataklarının ve kıyı kumullarının dayanıklı çalımsı ağacıdır. Meyveleri geleneksel olarak baharat ve bitkisel çay olarak kullanılır.',
    ['Yaz çiçekleriyle arılar için nektar', 'Dere yatağı ve kum zeminde kök tutar', 'Halk hekiminde geleneksel kullanım'],
    [['Muğla', 'Dalaman ve Köyceğiz kıyıları'], ['Antalya', 'Kıyı dere ağızları'], ['İzmir', 'Gediz kıyıları'], ['Mersin', 'Göksu deltası']]),
  s('zakkum', 'Zakkum', 'Nerium oleander', 'Zakkumgiller (Apocynaceae)', 'maki', '2–6 m', 'Mayıs – Eylül',
    'Kurak dere yataklarının bahar ve yaz boyunca pembe çiçeklerle donatan ve çok zehirli, her dem yeşil çalısıdır. Akdeniz kıyılarında çok yaygındır.',
    ['Kuraklığa ve sıcağa çok dayanıklı', 'Yol ve refüj peyzajında yaygın', 'Tüm kısımları zehirlidir, dikkat gerekir'],
    [['Antalya', 'Kent içi refüjler ve dere yatakları'], ['Mersin', 'Kıyı yolları'], ['Muğla', 'Dere yatakları']]),
  s('simsir', 'Şimşir', 'Buxus sempervirens', 'Şimşirgiller (Buxaceae)', 'maki', '2–8 m', 'Mart – Nisan',
    'Doğu Karadeniz ve Marmara’nın nemli ormanlarında yavaş büyüyen, çok sert odunlu her dem yeşil ağaçtır. Odunu geleneksel olarak tarak ve el sanatlarında değerlidir.',
    ['Çok sert ve ince dokulu odun', 'Her dem yeşil peyzaj ve çit bitkisi', 'Karadeniz orman altının koruması'],
    [['Artvin', 'Hopa ve Arhavi'], ['Rize', 'Çayeli ve Pazar'], ['Giresun', 'Eynesil çevresi'], ['Sinop', 'Ayancık çevresi']]),
  s('cobanpuskulu', 'Çobanpüskülü', 'Ilex colchica', 'Çobanpüskülügiller (Aquifoliaceae)', 'maki', '3–8 m', 'Mayıs',
    'Kış boyunca dallarda kalan parlak kırmızı meyveleriyle tanınan, her dem yeşil Kolhik ormanı alt katman ağacıdır. Karadeniz’in nemli vadilerinde yaşar.',
    ['Kış aylarında kuşlara besin', 'Orman altı ekosisteminin parçası', 'Her dem yeşil süs bitkisi'],
    [['Rize', 'Ayder ve Çamlıhemşin'], ['Trabzon', 'Maçka vadileri'], ['Artvin', 'Hopa ormanları']]),
  s('londra-cinari', 'Londra Çınarı', 'Platanus × acerifolia', 'Çınargiller (Platanaceae)', 'yaprakli', '20–35 m', 'Nisan – Mayıs',
    'Doğu ve Batı çınarının melezi olan, kentlerde cadde ağacı olarak çok dikilen dayanıklı gölge ağacıdır. Soyulan kabuğu benekli bir görünüm verir.',
    ['Kirliliğe dayanıklı güçlü gölge', 'Kent ısı adası etkisini azaltır', 'Çok yaygın cadde ağacı'],
    [['İstanbul', 'Cadde ve park dikimleri'], ['Ankara', 'Bulvarlar'], ['Bursa', 'Atatürk caddesi']], 'Melez · Kent ağacı'),
  s('buyuk-yapakli-ihlamur', 'Büyük Yapraklı Ihlamur', 'Tilia platyphyllos', 'Ihlamurgiller (Malvaceae)', 'yaprakli', '25–35 m', 'Haziran',
    'Geniş kalp yapraklı, kokulu çiçekleri ıhlamur çayının asıl kaynağı olan dağ ıhlamurudur. Nemli ve serin orman vadilerinde yaşar.',
    ['Ihlamur çayı hammaddesi', 'Arılara yoğun nektar', 'Serin ve geniş gölge'],
    [['Kırklareli', 'Istranca ormanları'], ['Bolu', 'Yenice ve Gölcük'], ['Bursa', 'Uludağ etekleri']]),
  s('kafkas-kizilagaci', 'Kafkas Kızılağacı', 'Alnus barbata', BET, 'yaprakli', '15–25 m', 'Şubat – Mart',
    'Doğu Karadeniz’in nemli yamaç ve dere boyu ormanlarının hızlı büyüyen ağacıdır. Köylerde yaygın yapı ve yakacak odunudur.',
    ['Azot bağlar, toprak zenginleştirir', 'Dere kıyılarında erozyonu önler', 'Hızlı odun üretimi'],
    [['Rize', 'Karadeniz dere boyları'], ['Artvin', 'Hopa ve Borçka'], ['Trabzon', 'Sürmene vadileri']]),
  s('kafkas-cevizi', 'Kafkas Kanatlı Cevizi', 'Pterocarya fraxinifolia', 'Cevizgiller (Juglandaceae)', 'yaprakli', '15–30 m', 'Nisan – Mayıs',
    'Sulak orman vadilerinde yaşayan relikt bir ağaçtır. Uzun, asılı çiçek başakları ve kanatlı meyveleriyle tanınır.',
    ['Nehir kıyısı ormanları için önemli relikt tür', 'Geniş taçla gölge', 'Sulak alan ekosisteminin parçası'],
    [['Artvin', 'Çoruh vadisi'], ['Giresun', 'Eynesil dere ağızları'], ['Rize', 'Fındıklı çevresi']], 'Relikt'),
  s('kara-hurma', 'Kara Hurma', 'Diospyros lotus', 'Abanozgiller (Ebenaceae)', 'meyve', '10–15 m', 'Mayıs – Haziran',
    'Küçük, koyu mavi-siyah meyveleri olan, Trabzon hurmasının yakın akrabası bir ağaçtır. Anadolu’da özellikle Karadeniz kıyısında köylerde yetişir.',
    ['Meyve ve süs ağacı', 'Hurma anacı olarak kullanılır', 'Kurak yamaçlarda yetişebilir'],
    [['Artvin', 'Çoruh vadisi'], ['Trabzon', 'Köy bahçeleri'], ['Rize', 'Kıyı kesimi']]),
  s('adi-disbudak', 'Adi Dışbudak', 'Fraxinus excelsior', OLE, 'yaprakli', '20–35 m', 'Nisan',
    'Siyah tomurcukları ve tüy gibi yaprakları ile tanınan, yüksek kaliteli odun veren dışbudaktır. Nemli ve besin zengini toprakları sever.',
    ['Spor aleti ve mobilya için çok değerli odun', 'Dere kenarı koruma', 'Orman altı çeşitliliğine katkı'],
    [['Kırklareli', 'Istranca ormanları'], ['Bolu', 'Köroğlu çevresi'], ['Sinop', 'Kuzey Anadolu']]),
  s('tatar-akcaagaci', 'Tatar Akçaağacı', 'Acer tataricum', ACE, 'yaprakli', '3–8 m', 'Mayıs',
    'Küçük boylu, kırmızı kanatlı meyveleri ve sonbahar renkleriyle dikkat çeken akçaağaçtır. Bozkır-orman geçiş kuşağında bulunur.',
    ['Sonbahar rengiyle peyzaj ağacı', 'Kurağa ve soğuğa dayanıklı', 'Arılara nektar'],
    [['Ankara', 'Kızılcahamam çevresi'], ['Kastamonu', 'Ilgaz yolu'], ['Bolu', 'Mudurnu']]),
  s('akdeniz-akcaagaci', 'Akdeniz Akçaağacı', 'Acer monspessulanum', ACE, 'yaprakli', '5–12 m', 'Nisan – Mayıs',
    'Üç loblu küçük yapraklarıyla kurak ve taşlı yamaçlarda yaşayan Akdeniz akçaağacıdır. Sonbaharda sarıya döner.',
    ['Kurak yamaçların koruması', 'Hafif ve dayanıklı odun', 'Sonbaharda sarı yaprak rengi'],
    [['Antalya', 'Toros eteklerinde'], ['Muğla', 'İç yamaçlar'], ['Isparta', 'Eğirdir çevresi']]),
  s('kapadokya-akcaagaci', 'Kapadokya Akçaağacı', 'Acer cappadocicum', ACE, 'yaprakli', '15–25 m', 'Nisan – Mayıs',
    'Elinin biçimine benzeyen beş-yedi loblu parlak yaprakları ile bilinen, Kafkasya ve Kuzey Anadolu’nun nemli orman akçaağacıdır. Sonbaharda altın sarısı olur.',
    ['Sonbahar rengi ile ünlü', 'Serin orman gölgesi', 'Polinatörler için bahar nektarı'],
    [['Artvin', 'Şavşat ormanları'], ['Rize', 'Çamlıhemşin'], ['Kastamonu', 'Küre Dağları']]),
  s('yabani-elma', 'Yabani Elma', 'Malus sylvestris', ROS, 'meyve', '5–10 m', 'Nisan – Mayıs',
    'Küçük, ekşi meyveleriyle köy kenarları ve orman kıyılarında kendiliğinden yetişen, kültür elmalarının atası sayılan ağaçtır.',
    ['Genetik kaynak olarak kültür elması ıslahında önemli', 'Meyveleri yaban hayatına besin', 'Çiçekleriyle bal arıları için nektar'],
    [['Bolu', 'Abant ve Mengen'], ['Kastamonu', 'İç Karadeniz'], ['Artvin', 'Borçka çevresi']]),
  s('adi-ardic', 'Adi Ardıç', 'Juniperus communis', CUP, 'ibreli', '1–8 m', 'Nisan – Mayıs',
    'Dünyada en geniş yayılışlı iğne yapraklı tür. Anadolu’nun yüksek dağlarında bodur ya da küçük ağaç olarak görülür; mavi meyveleri baharat olarak kullanılır.',
    ['Yüksek yamaçlarda erozyonu önler', 'Meyveleri (ardıç meyvesi) baharat ve geleneksel ilaçta kullanılır', 'Kış kuşlarına besin'],
    [['Erzurum', 'Palandöken'], ['Kars', 'Sarıkamış'], ['Bolu', 'Köroğlu Dağları']]),
  s('suriye-ardici', 'Suriye Ardıcı', 'Juniperus drupacea', CUP, 'ibreli', '10–20 m', 'Mart – Nisan',
    'Meyveleri büyük, kahverengi ve tatlıdır; Toros ve Amanos dağlarında doğal, çok eski bir ardıç türüdür. Bölge dışında nadirdir.',
    ['Nadir ve koruma değeri yüksek', 'Meyveleri yenilebilir', 'Dayanıklı ve uzun ömürlü odun'],
    [['Hatay', 'Amanos ve Belen'], ['Antalya', 'Batı Toroslar'], ['Isparta', 'Kuzey Toroslar']]),
  s('arizona-servisi', 'Arizona Servisi', 'Cupressus arizonica', CUP, 'ibreli', '10–20 m', 'Şubat – Mart',
    'Mavimsi gri-yeşil dokulu hızlı büyüyen yabancı servi. Kuraklığa çok dayanıklıdır; Anadolu’da peyzaj ve rüzgâr perdesinde yaygındır.',
    ['Çok kurak bölgelerde ağaçlandırma', 'Kent parklarında rüzgâr perdesi', 'Hızlı büyüme'],
    [['Ankara', 'Orman fidanlıkları ve parklar'], ['Konya', 'Kent ağaçlandırmaları'], ['Denizli', 'Park dikimleri']], 'Yabancı tür'),
  s('omur-agaci', 'Ömür Ağacı', 'Platycladus orientalis', CUP, 'ibreli', '8–15 m', 'Şubat – Mart',
    'Kelebek pulları gibi dikey dizilmiş dalcıkları olan, mezarlık ve bahçelerde sık dikilen Çin kökenli her dem yeşil ağaçtır.',
    ['Kuraklığa ve toprak fakirliğine dayanıklı', 'Peyzaj ve çit bitkisi', 'Uzun yaşar'],
    [['İstanbul', 'Mezarlıklar ve parklar'], ['Ankara', 'Kent içi parklar'], ['Konya', 'Mezarlıklar']], 'Yabancı tür'),
  s('atlas-sediri', 'Atlas Sediri', 'Cedrus atlantica', PIN, 'ibreli', '25–35 m', 'Eylül – Ekim',
    'Kuzey Afrika kökenli, mavimsi iğneli sedirdir. Türkiye’de park ve ağaçlandırmalarda Toros sedirine yakın bir görünümle dikilir.',
    ['Kuraklığa dayanıklı süs ağacı', 'Kokulu ve dayanıklı odun', 'Dağ ağaçlandırmasında alternatif'],
    [['Ankara', 'Parklar'], ['İstanbul', 'Koru ve bahçeler'], ['Bursa', 'Botanik Park']], 'Yabancı tür'),
  s('bataklik-servisi', 'Bataklık Servisi', 'Taxodium distichum', CUP, 'ibreli', '20–35 m', 'Mart – Nisan',
    'Kışın iğnelerini döken nadir bir ibrelidir; su içinde “soluk kökleri” oluşturur. Kuzey Amerika kökenli göl ve havuz kenarlarının ağacıdır.',
    ['Sulak alanlarda dikim', 'Sonbaharda bakır renkli yapraklar', 'Çok uzun ömürlü'],
    [['İstanbul', 'Göl ve havuz kenarları'], ['Sakarya', 'Parklar'], ['Bolu', 'Botanik bahçeler']], 'Yabancı tür'),
  s('trachycarpus', 'Çin Palmiyesi', 'Trachycarpus fortunei', 'Palmiyegiller (Arecaceae)', 'maki', '5–12 m', 'Nisan – Mayıs',
    'Soğuğa en dayanıklı palmiyelerden biri; Karadeniz ve Marmara kıyı kentlerinde sokak ve park ağacı olarak dikilir.',
    ['Soğuğa dayanıklı egzotik peyzaj', 'Kıyı iklimine uyum', 'Nektarıyla arılara katkı'],
    [['Rize', 'Kent parkları'], ['Trabzon', 'Sahil yolu'], ['İstanbul', 'Boğaz çevresi']], 'Yabancı tür'),
  s('kanarya-hurmasi', 'Kanarya Hurması', 'Phoenix canariensis', 'Palmiyegiller (Arecaceae)', 'maki', '10–20 m', 'Nisan – Mayıs',
    'Kalın gövdeli, görkemli taçlı palmiye; Akdeniz kıyı kentlerinin simgesidir. Kıyı cadde ve parklarında yaygın dikilir.',
    ['Kıyı peyzajının simgesi', 'Tuz ve rüzgâra dayanıklı', 'Turizm bölgelerinde değerli'],
    [['Antalya', 'Kaleiçi ve Konyaaltı'], ['İzmir', 'Kordon'], ['Muğla', 'Bodrum ve Marmaris']], 'Yabancı tür'),
  s('istranca-mesesi', 'Istranca Meşesi', 'Quercus hartwissiana', FAG, 'yaprakli', '15–30 m', 'Nisan – Mayıs',
    'Trakya’nın Istranca ormanlarında ve Karadeniz kıyılarında yaşayan, geniş yapraklı relikt bir meşedir. Nemli ve sisli ormanlarda büyür.',
    ['Istranca ormanlarının ana meşesi', 'Su toplama havzası koruyucusu', 'Kaliteli kereste'],
    [['Kırklareli', 'Istranca ormanları'], ['Iğneada', 'Longoz ormanları'], ['Sakarya', 'Karasu çevresi']], 'Relikt'),
  s('lubnan-mesesi', 'Lübnan Meşesi', 'Quercus libani', FAG, 'yaprakli', '5–12 m', 'Nisan – Mayıs',
    'Okaliptüs benzeri uzun, tırtıklı yapraklı bir meşedir. Güneydoğu Toroslar ve Hatay dağlarında yaygındır.',
    ['Yerel hayvan yemi (yaprak)', 'Kurak yamaçlarda toprak koruma', 'Palamutları yaban hayatı için önemli'],
    [['Hatay', 'Amanos Dağları'], ['Gaziantep', 'İslahiye çevresi'], ['Kahramanmaraş', 'Andırın']]),
  s('kil-mese', 'Kıl Meşe', 'Quercus brantii', FAG, 'yaprakli', '8–15 m', 'Nisan – Mayıs',
    'Zagros dağlarının uzantısı olan, Güneydoğu Anadolu’nun iç bölgelerinin meşe ormanlarını kuran kurağa dayanıklı meşedir.',
    ['Güneydoğu’nun ana orman ağacı', 'Kuraklıkta bile palamut verir', 'Yerel hayvancılık için yaprak ve meyve'],
    [['Siirt', 'Botan vadisi'], ['Şırnak', 'Cudi ve Gabar'], ['Diyarbakır', 'Ergani çevresi'], ['Batman', 'Hasankeyf çevresi']]),
  s('bittim', 'Bıttım', 'Pistacia atlantica', ANA, 'meyve', '5–12 m', 'Mart – Nisan',
    'Güneydoğu’nun kurak yamaçlarında kendiliğinden yetişen, dev boyutlara ulaşabilen yabani fıstıktır. Meyvelerinden menengiç kahvesi benzeri içecek ve yağ elde edilir.',
    ['Antep fıstığı için anaç olarak kullanılır', 'Meyveleri ve reçinesi kullanılır', 'Çok kuraklığa dayanıklı'],
    [['Mardin', 'Savur ve Midyat'], ['Siirt', 'Kurtalan çevresi'], ['Şanlıurfa', 'Siverek']]),
  s('keci-sogudu', 'Keçi Söğüdü', 'Salix caprea', SAL, 'yaprakli', '5–12 m', 'Mart – Nisan',
    'Pamuksu sarı erkek çiçekleriyle bahar başında arılar için ilk besin kaynağı olan söğüttür. Orman kenarları ve nemli yamaçlarda yaşar.',
    ['Erken bahar arı besini', 'Yangın ve açıklık sahalarında öncü tür', 'Yaban hayatına barınak'],
    [['Bolu', 'Köroğlu Dağları'], ['Kastamonu', 'Ilgaz'], ['Erzurum', 'Palandöken eteği']]),
  s('can-erigi', 'Can Eriği', 'Prunus cerasifera', ROS, 'meyve', '3–8 m', 'Mart – Nisan',
    'Kırmızı-mor yapraklı formlarıyla kent parklarında, sarı-kırmızı küçük meyveleriyle köylerde yetişen erik türüdür. Erken baharda bembeyaz çiçeklenir.',
    ['Erken bahar çiçeğiyle arılara katkı', 'Kentlerde kırmızı yapraklı süs ağacı', 'Meyveleri taze ve reçel için'],
    [['Ankara', 'Kent parkları'], ['Bursa', 'Köyler'], ['Eskişehir', 'Park dikimleri']]),
  s('kucuk-yapakli-ihlamur', 'Küçük Yapraklı Ihlamur', 'Tilia cordata', 'Ihlamurgiller (Malvaceae)', 'yaprakli', '20–30 m', 'Haziran – Temmuz',
    'Kuzey Anadolu’nun serin orman ıhlamuru; küçük kalp biçimli yaprakları ve kokulu çiçekleriyle tanınır. Ihlamur balının kaynaklarındandır.',
    ['Ihlamur balı ve çayı', 'Dağ ormanlarında gölge ve nem', 'Nektar zengini çiçekler'],
    [['Kastamonu', 'Küre Dağları'], ['Zonguldak', 'Batı Karadeniz'], ['Bolu', 'Yedigöller']]),
  /* ---- Üçüncü grup ---- */
  s('cay', 'Çay', 'Camellia sinensis', 'Çaygiller (Theaceae)', 'meyve', '1–3 m (budanmış)', 'Eylül – Kasım',
    'Doğu Karadeniz’in nemli ve asidik yamaçlarının simgesi olan her dem yeşil çalımsı bitkidir. Türkiye çay tarımı Rize ve çevresinde yoğunlaşır; budanmazsa küçük ağaç boyuna ulaşır.',
    ['Doğu Karadeniz ekonomisinin temel ürünü', 'Dik yamaçlarda toprak tutucu', 'Her dem yeşil yaprak örtüsü'],
    [['Rize', 'Çay üretiminin merkezi; Çayeli ve Ardeşen'], ['Trabzon', 'Of ve Sürmene'], ['Artvin', 'Hopa ve Arhavi'], ['Giresun', 'Batı sınırı çay bahçeleri']], 'Coğrafi işaret'),
  s('greyfurt', 'Greyfurt', 'Citrus × paradisi', RUT, 'meyve', '4–8 m', 'Nisan – Mayıs',
    'Akdeniz kıyılarında yetiştirilen, iri sarı-pembe meyveli turunçgildir. Kış aylarında meyve verir.',
    ['Kış meyvesi ve suyu olarak ihracat', 'Kıyı ovası tarım ekonomisi', 'Kokulu çiçekleriyle arıcılık'],
    [['Mersin', 'Erdemli ve Silifke'], ['Adana', 'Ova bahçeleri'], ['Hatay', 'Samandağ']]),
  s('himalaya-sediri', 'Himalaya Sediri', 'Cedrus deodara', PIN, 'ibreli', '30–50 m', 'Ekim – Kasım',
    'Sarkık dalları ve uzun yumuşak iğneleriyle tanınan, Himalaya kökenli sedirdir. Türkiye’de park ve bahçelerde süs ağacı olarak dikilir.',
    ['Süs ve gölge ağacı', 'Kokulu ve dayanıklı odun', 'Kentsel parklarda iğne yapraklı çeşitlilik'],
    [['İstanbul', 'Parklar ve koruluklar'], ['Ankara', 'Parklar'], ['Bursa', 'Botanik Park']], 'Yabancı tür'),
  s('duglas', 'Duglas Göknarı', 'Pseudotsuga menziesii', PIN, 'ibreli', '30–60 m', 'Nisan – Mayıs',
    'Kuzey Amerika’nın görkemli orman ağacıdır. Türkiye’de hızlı büyüyen ağaçlandırma türü olarak deneme sahalarında yer alır.',
    ['Çok hızlı büyüyen kereste ağacı', 'Dayanıklı yapı malzemesi', 'Yüksek karbon tutma'],
    [['Bolu', 'Deneme ağaçlandırmaları'], ['Sakarya', 'Orman fidanlıkları'], ['Kastamonu', 'Ormancılık deneme alanları']], 'Yabancı tür'),
  s('fenike-ardici', 'Fenike Ardıcı', 'Juniperus phoenicea', CUP, 'ibreli', '3–8 m', 'Mart – Nisan',
    'Kıyı kayalıkları ve kumullarının pul yapraklı, küçük sarı-kırmızı meyveli ardıcıdır. Akdeniz kıyılarında dalgalı sahillerin dayanıklı bitkisidir.',
    ['Kıyı kumullarında toprak bağlar', 'Tuz sprey ve rüzgâra dayanıklı', 'Kıyı ekosistemi için barınak'],
    [['Antalya', 'Kıyı kayalıkları'], ['Muğla', 'Datça ve Bodrum kıyıları'], ['Mersin', 'Anamur çevresi']]),
  s('dogu-kizilagaci', 'Doğu Kızılağacı', 'Alnus orientalis', BET, 'yaprakli', '10–20 m', 'Şubat – Mart',
    'Doğu Akdeniz’in nehir kıyısı ağacıdır; Hatay, Antalya ve Muğla’da dere boyları ve nemli vadilerde yaşar.',
    ['Dere kıyısı ormanları oluşturur', 'Azot bağlayıcı kökler', 'Taşkınlardan kıyı koruması'],
    [['Hatay', 'Asi Nehri ve Samandağ'], ['Antalya', 'Manavgat ve Alanya vadileri'], ['Muğla', 'Köyceğiz dere boyları']]),
  s('dogu-citlenbigi', 'Doğu Çitlenbiği', 'Celtis tournefortii', 'Kenevirgiller (Cannabaceae)', 'yaprakli', '4–10 m', 'Nisan – Mayıs',
    'Kurak taşlı yamaçların küçük boylu çitlenbiğidir; turuncu-kırmızı meyveleri vardır. İç Anadolu ve Güneydoğu’da yaygındır.',
    ['Kurak yamaçlarda toprak tutucu', 'Meyveleri kuşlar için besin', 'Dayanıklı süs ağacı'],
    [['Konya', 'Meram çevresi'], ['Aksaray', 'Ihlara vadisi'], ['Kayseri', 'Erciyes eteği']]),
  s('duman-agaci', 'Duman Ağacı', 'Cotinus coggygria', ANA, 'yaprakli', '3–6 m', 'Mayıs – Haziran',
    'Çiçek sonrası “duman” gibi görünen tüylü sapları ve sonbahar kırmızısıyla tanınır. Kurak, kireçli yamaçlarda doğal yetişir; boya ve tabaklama için kullanılmıştır.',
    ['Sonbaharda çarpıcı yaprak rengi', 'Geleneksel boyamacılıkta kullanılır', 'Kireçli taşlı yamaçları tutar'],
    [['Ankara', 'Kızılcahamam çevresi'], ['Çankırı', 'Ilgaz yamaçları'], ['Antalya', 'Toros eteği']]),
  s('gilaburu', 'Gilaburu', 'Viburnum opulus', 'Misk otugiller (Adoxaceae)', 'meyve', '3–5 m', 'Mayıs – Haziran',
    'Kırmızı salkım meyveleri kış başında olgunlaşan ve suyu içilen geleneksel bir çalımsı ağaçtır. Kayseri çevresinde ünlüdür.',
    ['Meyve suyu olarak ünlü yöresel ürün', 'Nemli vadilerde yaşar', 'Beyaz topak çiçekleriyle süs bitkisi'],
    [['Kayseri', 'Gilaburu üretimi; Sarıoğlan çevresi'], ['Sivas', 'Kızılırmak vadisi'], ['Tokat', 'Zile çevresi']], 'Coğrafi işaret'),
  s('murver', 'Mürver', 'Sambucus nigra', 'Misk otugiller (Adoxaceae)', 'yaprakli', '3–8 m', 'Mayıs – Haziran',
    'Beyaz krem rengi çiçek tabakları ve koyu mor meyveleriyle geleneksel şurup ve çay hammaddesidir. Nemli çalılık ve köy kenarlarında bulunur.',
    ['Çiçekleri şurup ve çay için kullanılır', 'Arılar ve böcekler için nektar', 'Meyveleri kuşlara besin'],
    [['Bolu', 'Abant çevresi'], ['Kastamonu', 'Küre Dağları'], ['Rize', 'Köy kenarları']]),
  s('kusburnu', 'Kuşburnu', 'Rosa canina', ROS, 'meyve', '1–3 m', 'Mayıs – Haziran',
    'Pembe-beyaz çiçekleri ve kış boyunca dallarda kalan kırmızı meyveleriyle her yerde tanınan yabani güldür. C vitamini bakımından çok zengindir.',
    ['Meyveleri çay ve reçel için kullanılır', 'Kuşlar için kış besini', 'Çalı örtüsü ile erozyonu önler'],
    [['Erzurum', 'Palandöken'], ['Bolu', 'Abant'], ['Sivas', 'Kızılırmak havzası']]),
  s('karacali', 'Karaçalı', 'Paliurus spina-christi', 'Çaparigiller (Rhamnaceae)', 'maki', '2–5 m', 'Mayıs – Temmuz',
    'Disk biçimli kanatlı meyveleri ve ikili dikenleriyle tanınan, kurak yamaçların dikenli çalımsı ağacıdır. Tarla kenarlarında doğal çit oluşturur.',
    ['Yamaçlarda erozyon engelleyici', 'Doğal çit', 'Yaz çiçekleri arılar için nektar'],
    [['Ankara', 'Kızılcahamam'], ['Konya', 'Meram'], ['Çanakkale', 'Biga yarımadası']]),
  s('katirtirnagi', 'Katırtırnağı', 'Spartium junceum', FAB, 'maki', '2–4 m', 'Mayıs – Temmuz',
    'Yaz boyunca parlak sarı kokulu çiçeklerle dolan, yaprakları çok az olan Akdeniz makisinin çalımsı bitkisidir. Yol kenarlarını sarıya boyar.',
    ['Kıyı yamaçlarında erozyon önleyici', 'Uzun yaz çiçek mevsimi ile arılara nektar', 'Kuraklığa çok dayanıklı'],
    [['Muğla', 'Datça ve Marmaris'], ['Antalya', 'Kemer ve Kumluca'], ['İzmir', 'Karaburun']]),
  s('sari-ormangulu', 'Sarı Ormangülü', 'Rhododendron luteum', 'Fundagiller (Ericaceae)', 'maki', '1–3 m', 'Nisan – Mayıs',
    'Sarı, çok kokulu çiçekleri bal arılarının zehirli “deli bal” üretmesine yol açan ormangülüdür. Karadeniz yaylalarında ve Kuzey Anadolu’nun yüksek yamaçlarında yetişir.',
    ['Yayla peyzajının simgesi', 'Dik yamaçlarda toprak koruma', 'Çiçekleri yoğun nektar verir ancak bal zehirli olabilir'],
    [['Trabzon', 'Yayla ve orman altı'], ['Artvin', 'Karagöl yöresi'], ['Rize', 'Yüksek yamaçlar']]),
];
